//! The WHATWG named character references (one table for the HTML tokenizer, XML-ish decoders and
//! JSX) and numeric character reference scanning. The table is generated by
//! `entities/generate-entities.mjs`.

mod table;

use table::{ENTRIES, NAMES, VALUES};

type Entry = (u16, u8, u16, u8, u8);

const XHTML: u8 = 1;

fn name_of(entry: &Entry) -> &'static [u8] {
    &NAMES.as_bytes()[entry.0 as usize..entry.0 as usize + entry.1 as usize]
}

fn value_of(entry: &Entry) -> &'static str {
    &VALUES[entry.2 as usize..entry.2 as usize + entry.3 as usize]
}

/// Longest named reference at the start of `input` (the bytes after `&`), as (consumed length,
/// replacement). Legacy references that end without `;` are included. Walks the sorted table one
/// byte at a time, narrowing the candidate range instead of searching per prefix.
pub fn longest_named(input: &[u8]) -> Option<(usize, &'static str)> {
    let names = NAMES.as_bytes();
    let mut range = ENTRIES;
    let mut best = None;
    for (depth, &byte) in input.iter().take(32).enumerate() {
        if !byte.is_ascii_alphanumeric() && byte != b';' {
            break;
        }
        let at = |entry: &Entry| names[entry.0 as usize + depth];
        // Candidates share input[..depth]; the one equal to it (if any) sorts first.
        let first = range.partition_point(|entry| entry.1 as usize <= depth || at(entry) < byte);
        let rest = &range[first..];
        let count = rest.partition_point(|entry| at(entry) == byte);
        if count == 0 {
            break;
        }
        range = &rest[..count];
        let head = range[0];
        if head.1 as usize == depth + 1 {
            best = Some((depth + 1, value_of(&head)));
        }
        if byte == b';' {
            break;
        }
    }
    best
}

/// The replacement for the exact reference `name` (without `&`; `;` included for the semicolon
/// form, absent for a legacy form).
pub fn named(name: &str) -> Option<&'static str> {
    let index = ENTRIES
        .binary_search_by(|entry| name_of(entry).cmp(name.as_bytes()))
        .ok()?;
    Some(value_of(&ENTRIES[index]))
}

/// The replacement for `name` (no `&`, no `;`) when it is one of the XHTML 1.0 entities, the set
/// JSX accepts. Two differ from the WHATWG table: `lang` and `rang` are the angle brackets
/// U+2329 / U+232A there.
pub fn xhtml(name: &str) -> Option<&'static str> {
    match name {
        "lang" => return Some("\u{2329}"),
        "rang" => return Some("\u{232a}"),
        _ => {}
    }
    let mut key = String::with_capacity(name.len() + 1);
    key.push_str(name);
    key.push(';');
    let index = ENTRIES
        .binary_search_by(|entry| name_of(entry).cmp(key.as_bytes()))
        .ok()?;
    let entry = &ENTRIES[index];
    (entry.4 & XHTML != 0).then(|| value_of(entry))
}

/// A numeric character reference scanned by [`char_ref`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CharRef {
    /// The code point; saturates to `u32::MAX` when the digits overflow.
    pub value: u32,
    /// Bytes consumed after the `&`: `#`, optional `x`, the digits and a `;` when present.
    pub len: usize,
    pub terminated: bool,
}

/// Scans `#123`, `#x1F` or `#X1F` (and a following `;`) at the start of `input`, the text after
/// `&`. `None` when it is not a numeric reference or has no digits.
pub fn char_ref(input: &str) -> Option<CharRef> {
    let rest = input.strip_prefix('#')?;
    let (radix, digits, prefix) = match rest.strip_prefix(['x', 'X']) {
        Some(hex) => (16, hex, 2),
        None => (10, rest, 1),
    };
    let count = digits
        .bytes()
        .take_while(|byte| (*byte as char).is_digit(radix))
        .count();
    if count == 0 {
        return None;
    }
    let value = u32::from_str_radix(&digits[..count], radix).unwrap_or(u32::MAX);
    let terminated = digits.as_bytes().get(count) == Some(&b';');
    Some(CharRef {
        value,
        len: prefix + count + usize::from(terminated),
        terminated,
    })
}

/// The character the HTML tokenizer produces for a numeric reference: C1 controls map through
/// windows-1252, and NUL, surrogates and out-of-range values become U+FFFD.
pub fn html_char(value: u32) -> char {
    const C1: [u32; 32] = [
        0x20ac, 0x81, 0x201a, 0x192, 0x201e, 0x2026, 0x2020, 0x2021, 0x2c6, 0x2030, 0x160, 0x2039,
        0x152, 0x8d, 0x17d, 0x8f, 0x90, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022, 0x2013, 0x2014,
        0x2dc, 0x2122, 0x161, 0x203a, 0x153, 0x9d, 0x17e, 0x178,
    ];
    let value = if (0x80..=0x9f).contains(&value) {
        C1[(value - 0x80) as usize]
    } else {
        value
    };
    char::from_u32(value)
        .filter(|&value| value != '\0')
        .unwrap_or('\u{fffd}')
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn named_lookups() {
        assert_eq!(longest_named(b"copy and"), Some((4, "\u{a9}")));
        assert_eq!(longest_named(b"copy;"), Some((5, "\u{a9}")));
        assert_eq!(longest_named(b"notit;"), Some((3, "\u{ac}")));
        assert_eq!(longest_named(b"nosuch;"), None);
        assert_eq!(named("amp;"), Some("&"));
        assert_eq!(xhtml("hellip"), Some("\u{2026}"));
        assert_eq!(xhtml("lang"), Some("\u{2329}"));
        assert_eq!(xhtml("Abreve"), None);
        assert_eq!(xhtml("amp"), Some("&"));
    }

    #[test]
    fn numeric_references() {
        assert_eq!(
            char_ref("#x41;b"),
            Some(CharRef {
                value: 0x41,
                len: 5,
                terminated: true
            })
        );
        assert_eq!(
            char_ref("#65"),
            Some(CharRef {
                value: 65,
                len: 3,
                terminated: false
            })
        );
        assert_eq!(char_ref("#99999999999;").map(|r| r.value), Some(u32::MAX));
        assert_eq!(char_ref("#x;"), None);
        assert_eq!(char_ref("#+1;"), None);
        assert_eq!(html_char(0x80), '\u{20ac}');
        assert_eq!(html_char(0), '\u{fffd}');
        assert_eq!(html_char(u32::MAX), '\u{fffd}');
    }
}
