print({i: i * i for i in range(5)})
print({k: v for k, v in zip("abc", range(3))})
print({k: v for k, v in {"a": 1, "b": 2, "c": 3}.items() if v % 2})
print({v: k for k, v in {"a": 1, "b": 2}.items()})
print({c: ord(c) for c in "hello"}, {c for c in "hello"} == set("helo"))
print({i % 3: i for i in range(10)})
print({i: [j for j in range(i)] for i in range(4)})
print({(i, j): i * j for i in range(3) for j in range(3) if i != j})
print({i: {j: i + j for j in range(2)} for i in range(3)})
nested = {"a": {"x": 1, "y": 2}, "b": {"x": 3, "y": 4}}
print({k: sum(v.values()) for k, v in nested.items()})
print({k: {ik: iv * 10 for ik, iv in v.items()} for k, v in nested.items()})
print({ik for v in nested.values() for ik in v} == {"x", "y"})
print([(k, ik) for k, v in nested.items() for ik in v])
print({k: [v["x"], v["y"]] for k, v in nested.items()})
flat = {f"{k}.{ik}": iv for k, v in nested.items() for ik, iv in v.items()}
print(flat)
words = ["apple", "bob", "cat", "apple", "bob", "apple"]
print({w: words.count(w) for w in words})
print({w: len(w) for w in sorted(set(words))})
print({len(w): w for w in words})
print({w[0]: [x for x in words if x[0] == w[0]] for w in words})
matrix = [[1, 2, 3], [4, 5, 6]]
print({(r, c): v for r, row in enumerate(matrix) for c, v in enumerate(row)})
print({i: i for i in range(3)} == {0: 0, 1: 1, 2: 2})
print({k: v for k, v in sorted({"b": 1, "a": 2}.items())})
print({k.upper(): v for k, v in {"a": 1}.items()}, {1: "a", 1.0: "b", True: "c"})
squares = {n: n ** 2 for n in range(1, 6)}
print({k: v for k, v in squares.items() if v > 5}, sum(squares.values()), max(squares, key=squares.get))
x = 10
print({x: x for x in range(2)}, x)
print({k: (lambda n: n + k)(1) for k in range(3)})
fns = {k: (lambda k=k: k * 2) for k in range(3)}
print({k: f() for k, f in fns.items()})
print({i: j for i, j in enumerate("abc", 1)}, dict(enumerate("ab")))
print({a: b for a, b in [(1, 2), (3, 4), (1, 5)]})
print({k: v for k, v in [("a", 1)] + [("b", 2)]})
print(len({i: None for i in range(100)}), list({i: None for i in "zyx"}))
print({str(i): i for i in range(3)}, {i: str(i) for i in range(3)})
print({k: v for k, v in {"a": None, "b": 0, "c": 1}.items() if v is not None})
print({True: 1, False: 0}, {None: 1}, {(1, (2, 3)): [4]}, {"": 0})
gen = ((k, v) for k, v in zip("ab", "cd"))
print(dict(gen))
print(dict((k, v * 2) for k, v in {"a": 1}.items()), dict.fromkeys(x for x in "aab"))
print(sorted({x * y for x in range(1, 4) for y in range(1, 4)}))
print({k: v for d in [{"a": 1}, {"b": 2}, {"a": 3}] for k, v in d.items()})
print({k: [n for n in range(v)] for k, v in {"p": 2, "q": 0}.items()})
print({k: v for k in "ab" for v in (1, 2)})
