// node:fs — Node 20.10's lib/fs.js and lib/internal/fs/* run as-is over lumen's filesystem binding.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/fsgen/gen.js (see tools/README.md).
//
// The Node sources below are verbatim, each wrapped as a CommonJS-style module; the few edits are
// marked `lumen:`. They reach the platform only through `internalBinding('fs')`, which this file
// implements over the Rust ops in src/fsb.rs (`__node.fsBinding()`), so validation, argument
// handling, error shapes, streams, FileHandle, Dir, cp, rm, and the promise API all behave as
// Node's own code does.
//
// The binding follows Node's calling convention. Each method takes its arguments, then `req`,
// then `ctx`:
//   - `req === undefined`: synchronous. On failure it fills `ctx` (errno/syscall) when `ctx` is an
//     object, and otherwise throws the uvException Node's C++ would build.
//   - `req instanceof FSReqCallback`: the worker-pool op runs, then `req.oncomplete(err, result)`.
//   - `req === kUsePromises`: returns a promise.
// Errors carry libuv's names and errno values (see `__uvErrmap` in preamble.js). Stats travel as
// the 18-slot Float64Array (or BigInt64Array) that Node's getStatsFromBinding reads.

const primordials = __primordials;
const isWindows = process.platform === "win32";
const fsb = __node.fsBinding();

// ---- the module table -------------------------------------------------------------------------
// `defineModule(id, fn)` registers a module body, which is evaluated on its first `require`.
// Cycles resolve as in CommonJS: a module is cached before its body runs.
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}
function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {} };
    moduleCache.set(id, module);
    fn(module, module.exports, require, internalBinding, primordials);
    return module.exports;
  }
  const value = builtinModule(id);
  moduleCache.set(id, { exports: value });
  return value;
}
function builtinModule(id) {
  switch (id) {
    case "buffer": case "path": case "stream": case "string_decoder": case "timers": case "util":
    case "util/types": case "url":
      return __builtins.get(id);
    case "events":
      return __builtins.get("events");
    case "internal/util/types":
      return __builtins.get("util").types;
    case "fs/promises":
      return require("fs").promises;
  }
  throw new Error(`lumen fs: internal module '${id}' is not available`);
}

// ---- internal/errors --------------------------------------------------------------------------

const kIsNodeError = Symbol("kIsNodeError");
// Node's SystemError: `new ERR_X({ syscall, code, message, path, dest, errno })`.
class SystemError extends Error {
  constructor(key, prefix, context) {
    super();
    let message = `${prefix}: ${context.syscall} returned ${context.code} (${context.message})`;
    if (context.path !== undefined) message += ` ${context.path}`;
    if (context.dest !== undefined) message += ` => ${context.dest}`;
    this.code = key;
    Object.defineProperties(this, {
      [kIsNodeError]: { value: true, enumerable: false, writable: false, configurable: true },
      name: { value: "SystemError", enumerable: false, writable: true, configurable: true },
      message: { value: message, enumerable: false, writable: true, configurable: true },
      info: { value: context, enumerable: true, configurable: true, writable: false },
      errno: {
        get() { return context.errno; },
        set: (value) => { context.errno = value; },
        enumerable: true, configurable: true,
      },
      syscall: {
        get() { return context.syscall; },
        set: (value) => { context.syscall = value; },
        enumerable: true, configurable: true,
      },
    });
    if (context.path !== undefined) {
      Object.defineProperty(this, "path", {
        get() { return context.path != null ? context.path.toString() : context.path; },
        set: (value) => { context.path = value ? Buffer.from(value.toString()) : undefined; },
        enumerable: true, configurable: true,
      });
    }
    if (context.dest !== undefined) {
      Object.defineProperty(this, "dest", {
        get() { return context.dest != null ? context.dest.toString() : context.dest; },
        set: (value) => { context.dest = value ? Buffer.from(value.toString()) : undefined; },
        enumerable: true, configurable: true,
      });
    }
    if (typeof this.stack === "string") {
      const nl = this.stack.indexOf("\n");
      this.stack = `SystemError [${key}]: ${message}${nl === -1 ? "" : this.stack.slice(nl)}`;
    }
  }
  toString() {
    return `${this.name} [${this.code}]: ${this.message}`;
  }
  [Symbol.for("nodejs.util.inspect.custom")](recurseTimes, ctx) {
    return __builtins.get("util").inspect(this, { ...ctx, getters: true, customInspect: false });
  }
}
const systemErrorCodes = {
  ERR_FS_CP_DIR_TO_NON_DIR: "Cannot overwrite directory with non-directory",
  ERR_FS_CP_EEXIST: "Target already exists",
  ERR_FS_CP_EINVAL: "Invalid src or dest",
  ERR_FS_CP_FIFO_PIPE: "Cannot copy a FIFO pipe",
  ERR_FS_CP_NON_DIR_TO_DIR: "Cannot overwrite non-directory with directory",
  ERR_FS_CP_SOCKET: "Cannot copy a socket file",
  ERR_FS_CP_SYMLINK_TO_SUBDIRECTORY: "Cannot overwrite symlink in subdirectory of self",
  ERR_FS_CP_UNKNOWN: "Cannot copy an unknown file type",
  ERR_FS_EISDIR: "Path is a directory",
  ERR_SYSTEM_ERROR: "A system error occurred",
};
const codes = { __proto__: __errors };
for (const key of Object.keys(systemErrorCodes)) {
  const prefix = systemErrorCodes[key];
  codes[key] = { [key]: class extends SystemError { constructor(ctx) { super(key, prefix, ctx); } } }[key];
}
function simpleCode(key, Base, format) {
  codes[key] = {
    [key]: function (...args) {
      const err = new Base(format(...args));
      err.code = key;
      if (typeof err.stack === "string") {
        err.stack = `${err.name} [${key}]${err.stack.slice(err.name.length)}`;
      }
      Object.defineProperty(err, "toString", {
        value() { return `${this.name} [${key}]: ${this.message}`; },
        enumerable: false, writable: true, configurable: true,
      });
      return err;
    },
  }[key];
}
if (!("ERR_FS_INVALID_SYMLINK_TYPE" in __errors)) {
  simpleCode("ERR_FS_INVALID_SYMLINK_TYPE", Error,
    (type) => `Symlink type must be one of "dir", "file", or "junction". Received "${type}"`);
}
if (!("ERR_INCOMPATIBLE_OPTION_PAIR" in __errors)) {
  simpleCode("ERR_INCOMPATIBLE_OPTION_PAIR", TypeError,
    (a, b) => `Option "${a}" cannot be used in combination with option "${b}"`);
}
if (!("ERR_INTERNAL_ASSERTION" in __errors)) {
  simpleCode("ERR_INTERNAL_ASSERTION", Error, (message) => {
    const suffix = "This is caused by either a bug in Node.js or incorrect usage of Node.js internals.\n" +
      "Please open an issue with this stack trace at https://github.com/nodejs/node/issues\n";
    return message === undefined ? suffix : `${message}\n${suffix}`;
  });
}

class AbortError extends Error {
  constructor(message = "The operation was aborted", options = undefined) {
    if (options !== undefined && typeof options !== "object") {
      throw new codes.ERR_INVALID_ARG_TYPE("options", "Object", options);
    }
    super(message, options);
    this.code = "ABORT_ERR";
    this.name = "AbortError";
  }
}

function aggregateTwoErrors(innerError, outerError) {
  if (innerError && outerError && innerError !== outerError) {
    if (Array.isArray(outerError.errors)) {
      outerError.errors.push(innerError);
      return outerError;
    }
    const err = new AggregateError([outerError, innerError], outerError.message);
    err.code = outerError.code;
    return err;
  }
  return innerError || outerError;
}

function uvErrmapGet(errno) {
  return __uvErrmap.get(errno);
}

// Node's uvException: `${code}: ${desc}, ${syscall} '${path}' -> '${dest}'`, with every other
// ctx key copied onto the error.
function uvException(ctx) {
  const { 0: code, 1: uvmsg } = uvErrmapGet(ctx.errno) || ["UNKNOWN", "unknown error"];
  let message = `${code}: ${ctx.message || uvmsg}, ${ctx.syscall}`;
  let path;
  let dest;
  if (ctx.path) {
    path = ctx.path.toString();
    message += ` '${path}'`;
  }
  if (ctx.dest) {
    dest = ctx.dest.toString();
    message += ` -> '${dest}'`;
  }
  const err = new Error(message);
  for (const prop of Object.keys(ctx)) {
    if (prop === "message" || prop === "path" || prop === "dest") continue;
    err[prop] = ctx[prop];
  }
  err.code = code;
  if (path) err.path = path;
  if (dest) err.dest = dest;
  return err;
}

const internalErrors = {
  codes, AbortError, aggregateTwoErrors, uvErrmapGet, uvException, SystemError,
  hideStackFrames: (fn) => fn,
};

// ---- internal/validators ----------------------------------------------------------------------

function isInt32(value) {
  return value === (value | 0);
}
function isUint32(value) {
  return value === (value >>> 0);
}
const octalReg = /^[0-7]+$/;
const modeDesc = "must be a 32-bit unsigned integer or an octal string";
function parseFileMode(value, name, def) {
  value ??= def;
  if (typeof value === "string") {
    if (octalReg.exec(value) === null) throw new codes.ERR_INVALID_ARG_VALUE(name, value, modeDesc);
    value = Number.parseInt(value, 8);
  }
  __validators.validateUint32(value, name);
  return value;
}
function validateEncoding(data, encoding) {
  const normalized = typeof encoding === "string" ? encoding.toLowerCase() : encoding;
  const length = data.length;
  if (normalized === "hex" && length % 2 !== 0) {
    throw new codes.ERR_INVALID_ARG_VALUE("encoding", encoding, `is invalid for data of length ${length}`);
  }
}
const internalValidators = { ...__validators, isInt32, isUint32, parseFileMode, validateEncoding };

// ---- internal/util ----------------------------------------------------------------------------

const kEmptyObject = Object.freeze({ __proto__: null });
function once(callback) {
  let called = false;
  return function (...args) {
    if (called) return;
    called = true;
    return Reflect.apply(callback, this, args);
  };
}
function defineLazyProperties(target, id, keys, enumerable = true) {
  const descriptors = { __proto__: null };
  let mod;
  for (let i = 0; i < keys.length; i++) {
    const key = keys[i];
    let lazyLoadedValue;
    function set(value) {
      Object.defineProperty(target, key, { __proto__: null, writable: true, value });
    }
    Object.defineProperty(set, "name", { __proto__: null, value: `set ${key}` });
    function get() {
      mod ??= require(id);
      if (lazyLoadedValue === undefined) {
        lazyLoadedValue = mod[key];
        set(lazyLoadedValue);
      }
      return lazyLoadedValue;
    }
    Object.defineProperty(get, "name", { __proto__: null, value: `get ${key}` });
    descriptors[key] = { __proto__: null, configurable: true, enumerable, get, set };
  }
  Object.defineProperties(target, descriptors);
}
function createDeferredPromise() {
  let resolve;
  let reject;
  const promise = new Promise((res, rej) => {
    resolve = res;
    reject = rej;
  });
  return { promise, resolve, reject };
}
// A blocking sleep (Node's is uv_sleep); rimrafSync backs off with it between retries.
function sleep(msec) {
  try {
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, msec);
  } catch {
    const end = Date.now() + msec;
    while (Date.now() < end);
  }
}
const internalUtil = {
  kEmptyObject,
  once,
  defineLazyProperties,
  createDeferredPromise,
  sleep,
  get promisify() { return __builtins.get("util").promisify; },
  get deprecate() { return __builtins.get("util").deprecate; },
  get customPromisifyArgs() { return __internals.get("customPromisifyArgs"); },
  SideEffectFreeRegExpPrototypeExec: (re, string) => RegExp.prototype.exec.call(re, string),
  lazyDOMException: (message, name) => new DOMException(message, name),
  emitExperimentalWarning(feature) {
    process.emitWarning(`${feature} is an experimental feature and might change at any time`, "ExperimentalWarning");
  },
};

// ---- the other internal modules the fs sources import -----------------------------------------

// internal/url: a WHATWG URL (or a URL-shaped object) with the file: scheme becomes its path.
function isURL(self) {
  return Boolean(self?.href && self.protocol && self.auth === undefined && self.path === undefined);
}
function toPathIfFileURL(fileURLOrPath) {
  if (!isURL(fileURLOrPath)) return fileURLOrPath;
  return __builtins.get("url").fileURLToPath(fileURLOrPath);
}

function assert(value, message) {
  if (!value) throw new codes.ERR_INTERNAL_ASSERTION(message);
}
assert.fail = (message) => {
  throw new codes.ERR_INTERNAL_ASSERTION(message);
};

// internal/event_target: Node's mixin that gives a non-EventEmitter base class the emitter API.
function EventEmitterMixin(Superclass) {
  const EventEmitter = __builtins.get("events");
  class MixedEventEmitter extends Superclass {
    constructor(...args) {
      super(...args);
      Reflect.apply(EventEmitter, this, []);
    }
  }
  const protoProps = Object.getOwnPropertyDescriptors(EventEmitter.prototype);
  delete protoProps.constructor;
  Object.defineProperties(MixedEventEmitter.prototype, protoProps);
  return MixedEventEmitter;
}

// internal/webstreams/adapters: a byte-chunk ReadableStream over a FileHandle's fd.
function newReadableStreamFromStreamBase(handle, strategy, options = kEmptyObject) {
  const { ondone = () => {} } = options;
  return new ReadableStream({
    async pull(controller) {
      let bytes;
      try {
        bytes = await fsb.readAsync(handle.fd, 65536, -1);
      } catch (e) {
        controller.error(bindingError(e, "read"));
        ondone(e);
        return;
      }
      if (bytes.length === 0) {
        controller.close();
        ondone();
        return;
      }
      controller.enqueue(bytes);
    },
    cancel() {
      ondone();
    },
  }, strategy);
}

const shims = {
  __proto__: null,
  "internal/errors": internalErrors,
  "internal/validators": internalValidators,
  "internal/util": internalUtil,
  "internal/url": { isURL, toPathIfFileURL, get fileURLToPath() { return __builtins.get("url").fileURLToPath; } },
  "internal/constants": { CHAR_FORWARD_SLASH: 47, CHAR_BACKWARD_SLASH: 92, CHAR_DOT: 46, CHAR_COLON: 58 },
  "internal/assert": assert,
  "internal/async_hooks": {
    defaultTriggerAsyncIdScope: (asyncId, fn, ...args) => Reflect.apply(fn, null, args),
    symbols: { owner_symbol: Symbol("owner_symbol") },
  },
  "internal/event_target": {
    EventEmitterMixin,
    get kResistStopPropagation() { return __internals.get("streams").kResistStopPropagation; },
  },
  "internal/streams/destroy": { get errorOrDestroy() { return __internals.get("streams").errorOrDestroy; } },
  "internal/streams/utils": { get isIterable() { return __internals.get("streams").isIterable; } },
  "internal/process/permission": { isEnabled: () => false, has: () => true },
  "internal/worker/js_transferable": {
    JSTransferable: class JSTransferable {},
    kDeserialize: Symbol("kDeserialize"),
    kTransfer: Symbol("kTransfer"),
    kTransferList: Symbol("kTransferList"),
  },
  "internal/webstreams/adapters": { newReadableStreamFromStreamBase },
  "internal/webstreams/readablestream": {
    get ReadableStream() { return globalThis.ReadableStream; },
    readableStreamCancel(stream) {
      if (!stream.locked) stream.cancel().catch(() => {});
    },
  },
  "internal/readline/interface": { get Interface() { return __builtins.get("readline").Interface; } },
  "internal/blob": {
    createBlobFromFilePath(path, options) {
      return new Blob([Buffer.from(bindingCall("open", () => fsb.readFile(P(path), 0), path))], options);
    },
  },
};
for (const id of Object.keys(shims)) moduleCache.set(id, { exports: shims[id] });

// ---- internalBinding('constants') -------------------------------------------------------------

const fsConstants = (() => {
  const common = {
    UV_FS_SYMLINK_DIR: 1, UV_FS_SYMLINK_JUNCTION: 2, O_RDONLY: 0, O_WRONLY: 1, O_RDWR: 2,
    UV_DIRENT_UNKNOWN: 0, UV_DIRENT_FILE: 1, UV_DIRENT_DIR: 2, UV_DIRENT_LINK: 3, UV_DIRENT_FIFO: 4,
    UV_DIRENT_SOCKET: 5, UV_DIRENT_CHAR: 6, UV_DIRENT_BLOCK: 7,
    EXTENSIONLESS_FORMAT_JAVASCRIPT: 0, EXTENSIONLESS_FORMAT_WASM: 1,
  };
  const perms = {
    S_IRWXU: 448, S_IRUSR: 256, S_IWUSR: 128, S_IXUSR: 64, S_IRWXG: 56, S_IRGRP: 32, S_IWGRP: 16,
    S_IXGRP: 8, S_IRWXO: 7, S_IROTH: 4, S_IWOTH: 2, S_IXOTH: 1,
  };
  const tail = {
    F_OK: 0, R_OK: 4, W_OK: 2, X_OK: 1,
    UV_FS_COPYFILE_EXCL: 1, COPYFILE_EXCL: 1, UV_FS_COPYFILE_FICLONE: 2, COPYFILE_FICLONE: 2,
    UV_FS_COPYFILE_FICLONE_FORCE: 4, COPYFILE_FICLONE_FORCE: 4,
  };
  if (isWindows) {
    // Exactly Node's win32 table (no S_IFBLK/S_IFSOCK, no O_SYNC family).
    return {
      ...common, S_IFMT: 61440, S_IFREG: 32768, S_IFDIR: 16384, S_IFCHR: 8192, S_IFIFO: 4096,
      S_IFLNK: 40960, O_CREAT: 256, O_EXCL: 1024, UV_FS_O_FILEMAP: 536870912, O_TRUNC: 512,
      O_APPEND: 8, S_IRUSR: 256, S_IWUSR: 128, ...tail,
    };
  }
  const types = { S_IFMT: 61440, S_IFREG: 32768, S_IFDIR: 16384, S_IFCHR: 8192, S_IFBLK: 24576, S_IFIFO: 4096, S_IFLNK: 40960, S_IFSOCK: 49152 };
  if (process.platform === "darwin" || process.platform === "ios") {
    return {
      ...common, ...types, O_CREAT: 512, O_EXCL: 2048, UV_FS_O_FILEMAP: 0, O_NOCTTY: 131072,
      O_TRUNC: 1024, O_APPEND: 8, O_DIRECTORY: 1048576, O_NOFOLLOW: 256, O_SYNC: 128,
      O_DSYNC: 4194304, O_SYMLINK: 2097152, O_NONBLOCK: 4, ...perms, ...tail,
    };
  }
  // Linux/Android. AArch64 swaps the O_DIRECTORY/O_NOFOLLOW/O_DIRECT bits.
  const arm = process.arch === "arm64" || process.arch === "arm";
  return {
    ...common, ...types, O_CREAT: 64, O_EXCL: 128, UV_FS_O_FILEMAP: 0, O_NOCTTY: 256, O_TRUNC: 512,
    O_APPEND: 1024, O_DIRECTORY: arm ? 16384 : 65536, O_NOATIME: 262144, O_NOFOLLOW: arm ? 32768 : 131072,
    O_SYNC: 1052672, O_DSYNC: 4096, O_DIRECT: arm ? 65536 : 16384, O_NONBLOCK: 2048, ...perms, ...tail,
  };
})();

// ---- internalBinding('fs') --------------------------------------------------------------------

const kUsePromises = Symbol("fs_use_promises_symbol");
const kFsStatsFieldsNumber = 18;
function FSReqCallback(bigint) {
  this.bigint = bigint;
  this.oncomplete = null;
  this.context = null;
}
const statValues = new Float64Array(kFsStatsFieldsNumber * 2);
const bigintStatValues = new BigInt64Array(kFsStatsFieldsNumber * 2);

// A path argument (string or Buffer; already namespaced on Windows) as the ops take it. A realm
// embedded in a host process has its own working directory, so relative paths resolve there.
function P(path) {
  const s = typeof path === "string" ? path : Buffer.from(path).toString("utf8");
  if (s === "" || isWindows) return s;
  if (s.charCodeAt(0) === 47) return s;
  const base = __node.realmCwd();
  return base === undefined ? s : __builtins.get("path").resolve(base, s);
}
// How a path appears in an error message: Node reports it without the `\\?\` namespace prefix.
function displayPath(path) {
  if (path === undefined || path === null) return undefined;
  const s = typeof path === "string" ? path : Buffer.from(path).toString("utf8");
  if (!isWindows) return s;
  if (s.startsWith("\\\\?\\UNC\\")) return `\\\\${s.slice(8)}`;
  if (s.startsWith("\\\\?\\")) return s.slice(4);
  return s;
}
// A binding failure (OpError with a libuv code) as Node's uvException.
function bindingError(e, syscall, path, dest) {
  const code = e?.code;
  if (typeof code !== "string" || !__uvCodes.has(code)) return e;
  const ctx = { errno: __uvCodes.get(code), code, syscall };
  if (path !== undefined) ctx.path = displayPath(path);
  if (dest !== undefined) ctx.dest = displayPath(dest);
  return uvException(ctx);
}
function bindingCall(syscall, fn, path, dest) {
  try {
    return fn();
  } catch (e) {
    throw bindingError(e, syscall, path, dest);
  }
}
function complete(req, err, value) {
  try {
    if (err) Reflect.apply(req.oncomplete, req, [err]);
    // Node passes the result only when there is one: a void op completes as oncomplete(null).
    else Reflect.apply(req.oncomplete, req, value === undefined ? [null] : [null, value]);
  } catch (e) {
    process.nextTick(() => {
      throw e;
    });
  }
}
// Run one binding call in the mode `req`/`ctx` select (see the header comment).
function dispatch(req, ctx, syscall, path, dest, sync, async, post) {
  if (req === undefined) {
    let result;
    try {
      result = sync();
    } catch (e) {
      if (ctx !== null && typeof ctx === "object") {
        const code = e?.code;
        if (typeof code === "string" && __uvCodes.has(code)) {
          ctx.errno = __uvCodes.get(code);
          ctx.code = code;
          ctx.syscall = syscall;
          return undefined;
        }
      }
      throw bindingError(e, syscall, path, dest);
    }
    return post === undefined ? result : post(result);
  }
  let promise;
  try {
    promise = async();
  } catch (e) {
    promise = Promise.reject(e);
  }
  if (req === kUsePromises) {
    return promise.then(
      post === undefined ? undefined : post,
      (e) => { throw bindingError(e, syscall, path, dest); },
    );
  }
  promise.then(
    (result) => {
      let value;
      try {
        value = post === undefined ? result : post(result);
      } catch (e) {
        complete(req, e);
        return;
      }
      complete(req, null, value);
    },
    (e) => complete(req, bindingError(e, syscall, path, dest)),
  );
  return undefined;
}

function toStatArray(values, bigint) {
  if (bigint) {
    const out = new BigInt64Array(kFsStatsFieldsNumber);
    for (let i = 0; i < kFsStatsFieldsNumber; i++) out[i] = BigInt(Math.trunc(values[i]));
    bigintStatValues.set(out);
    return out;
  }
  const out = new Float64Array(values);
  statValues.set(out);
  return out;
}
function encodeName(name, encoding) {
  if (encoding === "buffer") return Buffer.from(name, "utf8");
  if (!encoding || encoding === "utf8" || encoding === "utf-8") return name;
  return Buffer.from(name, "utf8").toString(encoding);
}
function viewOf(buffer, offset, length) {
  return new Uint8Array(buffer.buffer, buffer.byteOffset + offset, length);
}
function pos(position) {
  if (position === null || position === undefined) return -1;
  // Validated positions reach 2 ** 63 - 1; past MAX_SAFE_INTEGER they are all beyond any file's
  // end, and an f64 near 2 ** 63 would round to an offset the OS rejects as negative.
  const n = typeof position === "bigint" ? Number(position) : position;
  return n < 0 ? -1 : Math.min(n, Number.MAX_SAFE_INTEGER);
}
function concatBuffers(buffers) {
  const views = buffers.map((b) => viewOf(b, 0, b.byteLength));
  return Buffer.concat(views);
}
function scatter(buffers, bytes) {
  let off = 0;
  for (const b of buffers) {
    if (off >= bytes.length) break;
    const n = Math.min(b.byteLength, bytes.length - off);
    viewOf(b, 0, n).set(bytes.subarray(off, off + n));
    off += n;
  }
  return bytes.length;
}

// The native FileHandle: an fd whose close() is a promise.
class NativeFileHandle {
  constructor(fd) {
    this.fd = fd;
  }
  getAsyncId() {
    return -1;
  }
  close() {
    const fd = this.fd;
    this.fd = -1;
    return fsb.closeAsync(fd).then(undefined, (e) => { throw bindingError(e, "close"); });
  }
  releaseFD() {
    const fd = this.fd;
    this.fd = -1;
    return fd;
  }
}

// uv_fs_poll: a stat every `interval` ms; `onchange(status, [current ... previous])` when any field
// but atime changes, or the error status does.
function StatWatcherHandle(bigint) {
  this.bigint = bigint;
  this.onchange = null;
  this._timer = null;
  this._prev = null;
  this._busy = 0;
  this._refed = true;
}
StatWatcherHandle.prototype.start = function (path, interval) {
  const p = P(path);
  const poll = () => {
    let cur = null;
    let status = 0;
    try {
      cur = fsb.stat(p);
    } catch (e) {
      status = __uvCodes.get(e?.code) ?? __uvCodes.get("UNKNOWN");
    }
    const zero = new Array(kFsStatsFieldsNumber).fill(0);
    if (status !== 0) {
      if (this._busy !== status) {
        this._emit(status, zero, this._prev ?? zero);
        this._busy = status;
        this._prev = zero;
      }
      return;
    }
    if (this._busy !== 0 && (this._busy < 0 || !statEqual(this._prev, cur))) {
      this._emit(0, cur, this._prev);
    }
    this._prev = cur;
    this._busy = 1;
  };
  poll();
  this._timer = setInterval(poll, Math.max(1, interval));
  if (!this._refed) this._timer.unref();
  return 0;
};
StatWatcherHandle.prototype._emit = function (status, cur, prev) {
  const all = [...cur, ...prev];
  const arr = this.bigint ? BigInt64Array.from(all, (v) => BigInt(Math.trunc(v))) : new Float64Array(all);
  if (typeof this.onchange === "function") this.onchange(status, arr);
};
StatWatcherHandle.prototype.close = function () {
  if (this._timer) clearInterval(this._timer);
  this._timer = null;
};
StatWatcherHandle.prototype.ref = function () {
  this._refed = true;
  this._timer?.ref();
};
StatWatcherHandle.prototype.unref = function () {
  this._refed = false;
  this._timer?.unref();
};
StatWatcherHandle.prototype.getAsyncId = function () {
  return -1;
};
function statEqual(a, b) {
  // dev, mode, nlink, uid, gid, rdev, blksize, ino, size, blocks, then mtime/ctime/birthtime.
  for (let i = 0; i < kFsStatsFieldsNumber; i++) {
    if (i === 10 || i === 11) continue; // atime
    if (a[i] !== b[i]) return false;
  }
  return true;
}

const fsBinding = {
  kUsePromises,
  kFsStatsFieldsNumber,
  FSReqCallback,
  statValues,
  bigintStatValues,
  StatWatcher: StatWatcherHandle,
  FileHandle: NativeFileHandle,

  access(path, mode, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "access", path, undefined, () => fsb.access(p, mode), () => fsb.accessAsync(p, mode));
  },
  existsSync(path) {
    try {
      return fsb.exists(P(path));
    } catch {
      return false;
    }
  },
  open(path, flags, mode, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "open", path, undefined, () => fsb.open(p, flags, mode), () => fsb.openAsync(p, flags, mode));
  },
  openFileHandle(path, flags, mode, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "open", path, undefined, () => fsb.open(p, flags, mode),
      () => fsb.openAsync(p, flags, mode), (fd) => new NativeFileHandle(fd));
  },
  close(fd, req, ctx) {
    return dispatch(req, ctx, "close", undefined, undefined, () => fsb.close(fd), () => fsb.closeAsync(fd), () => undefined);
  },
  read(fd, buffer, offset, length, position, req, ctx) {
    const view = viewOf(buffer, offset, length);
    const at = pos(position);
    return dispatch(req, ctx, "read", undefined, undefined, () => fsb.read(fd, view, at),
      () => fsb.readAsync(fd, length, at).then((bytes) => {
        view.set(bytes);
        return bytes.length;
      }));
  },
  readBuffers(fd, buffers, position, req, ctx) {
    let at = pos(position);
    return dispatch(req, ctx, "read", undefined, undefined, () => {
      let total = 0;
      for (const b of buffers) {
        const n = fsb.read(fd, viewOf(b, 0, b.byteLength), at);
        total += n;
        if (at >= 0) at += n;
        if (n < b.byteLength) break;
      }
      return total;
    }, () => {
      const len = buffers.reduce((sum, b) => sum + b.byteLength, 0);
      return fsb.readAsync(fd, len, at).then((bytes) => scatter(buffers, bytes));
    });
  },
  writeBuffer(fd, buffer, offset, length, position, req, ctx) {
    const view = viewOf(buffer, offset, length);
    const at = pos(position);
    return dispatch(req, ctx, "write", undefined, undefined, () => fsb.write(fd, view, at), () => fsb.writeAsync(fd, view, at));
  },
  writeBuffers(fd, buffers, position, req, ctx) {
    const data = concatBuffers(buffers);
    const at = pos(position);
    return dispatch(req, ctx, "write", undefined, undefined, () => fsb.write(fd, data, at), () => fsb.writeAsync(fd, data, at));
  },
  writeString(fd, string, position, encoding, req, ctx) {
    const data = Buffer.from(string, encoding || "utf8");
    const at = pos(position);
    return dispatch(req, ctx, "write", undefined, undefined, () => fsb.write(fd, data, at), () => fsb.writeAsync(fd, data, at));
  },
  rename(from, to, req, ctx) {
    const a = P(from);
    const b = P(to);
    return dispatch(req, ctx, "rename", from, to, () => fsb.rename(a, b), () => fsb.renameAsync(a, b));
  },
  ftruncate(fd, len, req, ctx) {
    const n = Number(len);
    return dispatch(req, ctx, "ftruncate", undefined, undefined, () => fsb.ftruncate(fd, n), () => fsb.ftruncateAsync(fd, n));
  },
  rmdir(path, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "rmdir", path, undefined, () => fsb.rmdir(p), () => fsb.rmdirAsync(p));
  },
  mkdir(path, mode, recursive, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "mkdir", path, undefined, () => fsb.mkdir(p, mode, !!recursive),
      () => fsb.mkdirAsync(p, mode, !!recursive), (first) => (recursive && first != null ? displayPath(first) : undefined));
  },
  readdir(path, encoding, withTypes, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "scandir", path, undefined, () => fsb.readdir(p), () => fsb.readdirAsync(p),
      ([names, types]) => {
        const encoded = names.map((n) => encodeName(n, encoding));
        return withTypes ? [encoded, types] : encoded;
      });
  },
  internalModuleStat(path) {
    try {
      const st = fsb.statMaybe(P(path), true);
      if (st == null) return -2;
      return (st[1] & 0o170000) === 0o040000 ? 1 : 0;
    } catch {
      return -2;
    }
  },
  fstat(fd, bigint, req, ctx) {
    return dispatch(req, ctx, "fstat", undefined, undefined, () => fsb.fstat(fd), () => fsb.fstatAsync(fd),
      (v) => toStatArray(v, bigint));
  },
  lstat(path, bigint, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "lstat", path, undefined, () => fsb.lstat(p), () => fsb.lstatAsync(p),
      (v) => toStatArray(v, bigint));
  },
  stat(path, bigint, req, ctxOrThrow) {
    const p = P(path);
    if (req === undefined && ctxOrThrow === false) {
      const v = bindingCall("stat", () => fsb.statMaybe(p, true), path);
      return v == null ? undefined : toStatArray(v, bigint);
    }
    return dispatch(req, ctxOrThrow, "stat", path, undefined, () => fsb.stat(p), () => fsb.statAsync(p),
      (v) => toStatArray(v, bigint));
  },
  statfs(path, bigint, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "statfs", path, undefined, () => fsb.statfs(p), () => fsb.statfsAsync(p),
      (v) => (bigint ? BigInt64Array.from(v, (x) => BigInt(Math.trunc(x))) : new Float64Array(v)));
  },
  readlink(path, encoding, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "readlink", path, undefined, () => fsb.readlink(p), () => fsb.readlinkAsync(p),
      (s) => encodeName(displayPath(s), encoding));
  },
  symlink(target, path, flags, req, ctx) {
    const t = typeof target === "string" ? target : Buffer.from(target).toString("utf8");
    const p = P(path);
    return dispatch(req, ctx, "symlink", target, path, () => fsb.symlink(t, p, flags ?? 0),
      () => fsb.symlinkAsync(t, p, flags ?? 0));
  },
  link(existing, path, req, ctx) {
    const a = P(existing);
    const b = P(path);
    return dispatch(req, ctx, "link", existing, path, () => fsb.link(a, b), () => fsb.linkAsync(a, b));
  },
  unlink(path, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "unlink", path, undefined, () => fsb.unlink(p), () => fsb.unlinkAsync(p));
  },
  chmod(path, mode, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "chmod", path, undefined, () => fsb.chmod(p, mode), () => fsb.chmodAsync(p, mode));
  },
  fchmod(fd, mode, req, ctx) {
    return dispatch(req, ctx, "fchmod", undefined, undefined, () => fsb.fchmod(fd, mode), () => fsb.fchmodAsync(fd, mode));
  },
  chown(path, uid, gid, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "chown", path, undefined, () => fsb.chown(p, uid, gid, true), () => fsb.chownAsync(p, uid, gid, true));
  },
  lchown(path, uid, gid, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "lchown", path, undefined, () => fsb.chown(p, uid, gid, false), () => fsb.chownAsync(p, uid, gid, false));
  },
  fchown(fd, uid, gid, req, ctx) {
    return dispatch(req, ctx, "fchown", undefined, undefined, () => fsb.fchown(fd, uid, gid), () => fsb.fchownAsync(fd, uid, gid));
  },
  utimes(path, atime, mtime, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "utime", path, undefined, () => fsb.utimes(p, atime, mtime, true),
      () => fsb.utimesAsync(p, atime, mtime, true));
  },
  lutimes(path, atime, mtime, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "lutime", path, undefined, () => fsb.utimes(p, atime, mtime, false),
      () => fsb.utimesAsync(p, atime, mtime, false));
  },
  futimes(fd, atime, mtime, req, ctx) {
    return dispatch(req, ctx, "futime", undefined, undefined, () => fsb.futimes(fd, atime, mtime), () => fsb.futimesAsync(fd, atime, mtime));
  },
  fsync(fd, req, ctx) {
    return dispatch(req, ctx, "fsync", undefined, undefined, () => fsb.fsync(fd, false), () => fsb.fsyncAsync(fd, false));
  },
  fdatasync(fd, req, ctx) {
    return dispatch(req, ctx, "fdatasync", undefined, undefined, () => fsb.fsync(fd, true), () => fsb.fsyncAsync(fd, true));
  },
  mkdtemp(prefix, encoding, req, ctx) {
    const p = P(prefix).replace(/XXXXXX$/, "");
    const shown = `${displayPath(prefix)}XXXXXX`;
    return dispatch(req, ctx, "mkdtemp", shown, undefined, () => fsb.mkdtemp(p), () => fsb.mkdtempAsync(p),
      (s) => encodeName(displayPath(s), encoding));
  },
  realpath(path, encoding, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "realpath", path, undefined, () => fsb.realpath(p), () => fsb.realpathAsync(p),
      (s) => encodeName(displayPath(s), encoding));
  },
  copyFile(src, dest, mode, req, ctx) {
    const a = P(src);
    const b = P(dest);
    return dispatch(req, ctx, "copyfile", src, dest, () => fsb.copyFile(a, b, mode ?? 0), () => fsb.copyFileAsync(a, b, mode ?? 0));
  },
  readFileUtf8(path, flags) {
    if (typeof path === "number") {
      // An fd: read to the end from the current position.
      const chunks = [];
      for (;;) {
        const chunk = Buffer.allocUnsafe(65536);
        const n = bindingCall("read", () => fsb.read(path, chunk, -1));
        if (n === 0) break;
        chunks.push(chunk.subarray(0, n));
      }
      return Buffer.concat(chunks).toString("utf8");
    }
    const p = P(path);
    return bindingCall("open", () => fsb.readFileUtf8(p, flags), path);
  },
};

// internalBinding('fs_dir'): opendir reads the listing once; read() hands it out in pages of
// [name, type, name, type, ...], then null.
class DirHandle {
  constructor(names, types) {
    this.names = names;
    this.types = types;
    this.index = 0;
  }
  read(encoding, bufferSize, req, ctx) {
    const page = () => {
      if (this.index >= this.names.length) return null;
      const out = [];
      const end = Math.min(this.names.length, this.index + Math.max(1, bufferSize | 0));
      for (; this.index < end; this.index++) {
        out.push(encodeName(this.names[this.index], encoding), this.types[this.index]);
      }
      return out;
    };
    return dispatch(req, ctx, "scandir", undefined, undefined, page, () => Promise.resolve().then(page));
  }
  close(req, ctx) {
    this.names = [];
    return dispatch(req, ctx, "closedir", undefined, undefined, () => undefined, () => Promise.resolve());
  }
}
const fsDirBinding = {
  opendir(path, encoding, req, ctx) {
    const p = P(path);
    return dispatch(req, ctx, "opendir", path, undefined, () => fsb.readdir(p), () => fsb.readdirAsync(p),
      ([names, types]) => new DirHandle(names, types));
  },
  opendirSync(path) {
    const p = P(path);
    const [names, types] = bindingCall("opendir", () => fsb.readdir(p), path);
    return new DirHandle(names, types);
  },
};

// internalBinding('fs_event_wrap'): fs.watch by polling. A directory reports entries that appear
// or vanish as 'rename' and entries whose size or mtime moved as 'change' (with `recursive`, the
// whole subtree, names relative to the root); a file reports itself by basename.
const kWatchInterval = 50;
function FSEvent() {
  this.initialized = false;
  this.onchange = null;
  this._timer = null;
  this._refed = true;
}
function snapshotOf(p, isDir, recursive, sep) {
  const snap = new Map();
  if (!isDir) {
    try {
      const st = fsb.stat(p);
      snap.set("", `${st[8]}:${st[12]}:${st[13]}`);
    } catch {
      // gone: an empty snapshot
    }
    return snap;
  }
  const walk = (dir, prefix) => {
    let listing;
    try {
      listing = fsb.readdir(dir);
    } catch {
      return;
    }
    const [names, types] = listing;
    for (let i = 0; i < names.length; i++) {
      const rel = prefix + names[i];
      const full = dir + sep + names[i];
      let sig = String(types[i]);
      try {
        const st = fsb.lstat(full);
        // A directory's own mtime moves whenever an entry is added; watchers report the entry,
        // not the directory, so only existence counts for directories.
        sig = (st[1] & 0o170000) === 0o040000 ? "dir" : `${st[1]}:${st[8]}:${st[12]}:${st[13]}`;
      } catch {
        // raced with a delete
      }
      snap.set(rel, sig);
      if (recursive && types[i] === 2) walk(full, rel + sep);
    }
  };
  walk(p, "");
  return snap;
}
FSEvent.prototype.start = function (path, persistent, recursive, encoding) {
  const p = P(path);
  let st;
  try {
    st = fsb.stat(p);
  } catch (e) {
    return __uvCodes.get(e?.code) ?? __uvCodes.get("UNKNOWN");
  }
  const pathMod = __builtins.get("path");
  const sep = pathMod.sep;
  const isDir = (st[1] & 0o170000) === 0o040000;
  const base = pathMod.basename(displayPath(path));
  let prev = snapshotOf(p, isDir, recursive, sep);
  const emit = (eventType, name) => {
    if (this._timer === null || typeof this.onchange !== "function") return;
    const filename = encoding === "buffer" ? Buffer.from(name) :
      encoding && encoding !== "utf8" && encoding !== "utf-8" ? Buffer.from(name).toString(encoding) : name;
    this.onchange(0, eventType, filename);
  };
  this._timer = setInterval(() => {
    const cur = snapshotOf(p, isDir, recursive, sep);
    for (const [name, sig] of cur) {
      const old = prev.get(name);
      if (old === undefined) emit("rename", isDir ? name : base);
      else if (old !== sig) emit("change", isDir ? name : base);
    }
    for (const name of prev.keys()) {
      if (!cur.has(name)) emit("rename", isDir ? name : base);
    }
    prev = cur;
  }, kWatchInterval);
  if (!persistent) this._refed = false;
  if (!this._refed) this._timer.unref();
  this.initialized = true;
  return 0;
};
FSEvent.prototype.close = function () {
  if (this._timer) clearInterval(this._timer);
  this._timer = null;
  this.initialized = false;
};
FSEvent.prototype.ref = function () {
  this._refed = true;
  this._timer?.ref();
};
FSEvent.prototype.unref = function () {
  this._refed = false;
  this._timer?.unref();
};
FSEvent.prototype.getAsyncId = function () {
  return -1;
};

function internalBinding(name) {
  switch (name) {
    case "fs":
      return fsBinding;
    case "fs_dir":
      return fsDirBinding;
    case "fs_event_wrap":
      return { FSEvent };
    case "constants":
      return { fs: fsConstants, os: __builtins.get("os").constants };
    case "uv":
      return {
        UV_ENOSPC: __uvCodes.get("ENOSPC"),
        errname: (errno) => __uvErrmap.get(errno)?.[0],
        getErrorMap: () => __uvErrmap,
      };
  }
  throw new Error(`lumen fs: internalBinding('${name}') is not available`);
}

