// node:url and node:querystring — Node 20.11's lib/url.js, lib/querystring.js,
// lib/internal/querystring.js and the helper half of lib/internal/url.js, run as-is.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/urlgen/gen.js (see tools/README.md).
//
// Generated: the Node sources below are verbatim, each wrapped as a CommonJS-style module; edits
// are marked `lumen:`. The WHATWG `URL`/`URLSearchParams` classes are the globals lumen-web
// installs (its js/url.js is a port of Node's classes over the ada-derived parser in url.rs);
// `internalBinding('url')` hands out that parser's extra entry points (format, domainTo*), which
// lumen-web's URL keeps under a private symbol.

const primordials = __primordials;

// ---- the module table -------------------------------------------------------------------------
// `defineModule(id, fn)` registers a module body, which is evaluated on its first `require`.
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}
function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {} };
    moduleCache.set(id, module);
    fn(module, module.exports, require, internalBinding, primordials);
    return module.exports;
  }
  const value = builtinModule(id);
  moduleCache.set(id, { exports: value });
  return value;
}

const webUrl = globalThis.URL[Symbol.for("lumen.url.internals")];

function spliceOne(list, index) {
  for (; index + 1 < list.length; index++) list[index] = list[index + 1];
  list.pop();
}

function builtinModule(id) {
  switch (id) {
    case "buffer":
    case "path":
      return __builtins.get(id);
    case "internal/errors":
      return { codes: __errors };
    case "internal/validators":
      return __validators;
    case "internal/util":
      return { spliceOne, toUSVString: webUrl.toUSVString };
    case "internal/options":
      // `--pending-deprecation` is the only option lib/url.js reads.
      return {
        getOptionValue: (name) =>
          name === "--pending-deprecation" &&
          (process.execArgv.includes(name) || /(^|\s)--pending-deprecation(\s|$)/.test(process.env.NODE_OPTIONS || "")),
      };
    case "internal/idna":
      return { toASCII: webUrl.idnaToASCII, toUnicode: webUrl.idnaToUnicode };
  }
  throw new Error(`lumen url: internal module '${id}' is not available`);
}

function internalBinding(name) {
  if (name === "url") {
    return {
      URL: globalThis.URL,
      URLSearchParams: globalThis.URLSearchParams,
      updateActions: webUrl.updateActions,
      domainToASCII: webUrl.domainToASCII,
      domainToUnicode: webUrl.domainToUnicode,
      format: webUrl.format,
    };
  }
  throw new Error(`lumen url: internalBinding('${name}') is not available`);
}

defineModule("internal/constants", function (module, exports, require, internalBinding, primordials) {
  'use strict';

  const isWindows = process.platform === 'win32';

  module.exports = {
    // Alphabet chars.
    CHAR_UPPERCASE_A: 65, /* A */
    CHAR_LOWERCASE_A: 97, /* a */
    CHAR_UPPERCASE_Z: 90, /* Z */
    CHAR_LOWERCASE_Z: 122, /* z */
    CHAR_UPPERCASE_C: 67, /* C */
    CHAR_LOWERCASE_B: 98, /* b */
    CHAR_LOWERCASE_E: 101, /* e */
    CHAR_LOWERCASE_N: 110, /* n */

    // Non-alphabetic chars.
    CHAR_DOT: 46, /* . */
    CHAR_FORWARD_SLASH: 47, /* / */
    CHAR_BACKWARD_SLASH: 92, /* \ */
    CHAR_VERTICAL_LINE: 124, /* | */
    CHAR_COLON: 58, /* : */
    CHAR_QUESTION_MARK: 63, /* ? */
    CHAR_UNDERSCORE: 95, /* _ */
    CHAR_LINE_FEED: 10, /* \n */
    CHAR_CARRIAGE_RETURN: 13, /* \r */
    CHAR_TAB: 9, /* \t */
    CHAR_FORM_FEED: 12, /* \f */
    CHAR_EXCLAMATION_MARK: 33, /* ! */
    CHAR_HASH: 35, /* # */
    CHAR_SPACE: 32, /*   */
    CHAR_NO_BREAK_SPACE: 160, /* \u00A0 */
    CHAR_ZERO_WIDTH_NOBREAK_SPACE: 65279, /* \uFEFF */
    CHAR_LEFT_SQUARE_BRACKET: 91, /* [ */
    CHAR_RIGHT_SQUARE_BRACKET: 93, /* ] */
    CHAR_LEFT_ANGLE_BRACKET: 60, /* < */
    CHAR_RIGHT_ANGLE_BRACKET: 62, /* > */
    CHAR_LEFT_CURLY_BRACKET: 123, /* { */
    CHAR_RIGHT_CURLY_BRACKET: 125, /* } */
    CHAR_HYPHEN_MINUS: 45, /* - */
    CHAR_PLUS: 43, /* + */
    CHAR_DOUBLE_QUOTE: 34, /* " */
    CHAR_SINGLE_QUOTE: 39, /* ' */
    CHAR_PERCENT: 37, /* % */
    CHAR_SEMICOLON: 59, /* ; */
    CHAR_CIRCUMFLEX_ACCENT: 94, /* ^ */
    CHAR_GRAVE_ACCENT: 96, /* ` */
    CHAR_AT: 64, /* @ */
    CHAR_AMPERSAND: 38, /* & */
    CHAR_EQUAL: 61, /* = */

    // Digits
    CHAR_0: 48, /* 0 */
    CHAR_9: 57, /* 9 */

    EOL: isWindows ? '\r\n' : '\n',
  };
});

defineModule("internal/querystring", function (module, exports, require, internalBinding, primordials) {
  'use strict';

  const {
    Array,
    Int8Array,
    NumberPrototypeToString,
    StringPrototypeCharCodeAt,
    StringPrototypeSlice,
    StringPrototypeToUpperCase,
  } = primordials;

  const { ERR_INVALID_URI } = require('internal/errors').codes;

  const hexTable = new Array(256);
  for (let i = 0; i < 256; ++i)
    hexTable[i] = '%' +
                  StringPrototypeToUpperCase((i < 16 ? '0' : '') +
                                             NumberPrototypeToString(i, 16));

  const isHexTable = new Int8Array([
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 0 - 15
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 16 - 31
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 32 - 47
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, // 48 - 63
    0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 64 - 79
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 80 - 95
    0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 96 - 111
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 112 - 127
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 128 ...
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // ... 256
  ]);

  /**
   * @param {string} str
   * @param {Int8Array} noEscapeTable
   * @param {string[]} hexTable
   * @returns {string}
   */
  function encodeStr(str, noEscapeTable, hexTable) {
    const len = str.length;
    if (len === 0)
      return '';

    let out = '';
    let lastPos = 0;
    let i = 0;

    outer:
    for (; i < len; i++) {
      let c = StringPrototypeCharCodeAt(str, i);

      // ASCII
      while (c < 0x80) {
        if (noEscapeTable[c] !== 1) {
          if (lastPos < i)
            out += StringPrototypeSlice(str, lastPos, i);
          lastPos = i + 1;
          out += hexTable[c];
        }

        if (++i === len)
          break outer;

        c = StringPrototypeCharCodeAt(str, i);
      }

      if (lastPos < i)
        out += StringPrototypeSlice(str, lastPos, i);

      // Multi-byte characters ...
      if (c < 0x800) {
        lastPos = i + 1;
        out += hexTable[0xC0 | (c >> 6)] +
               hexTable[0x80 | (c & 0x3F)];
        continue;
      }
      if (c < 0xD800 || c >= 0xE000) {
        lastPos = i + 1;
        out += hexTable[0xE0 | (c >> 12)] +
               hexTable[0x80 | ((c >> 6) & 0x3F)] +
               hexTable[0x80 | (c & 0x3F)];
        continue;
      }
      // Surrogate pair
      ++i;

      // This branch should never happen because all URLSearchParams entries
      // should already be converted to USVString. But, included for
      // completion's sake anyway.
      if (i >= len)
        throw new ERR_INVALID_URI();

      const c2 = StringPrototypeCharCodeAt(str, i) & 0x3FF;

      lastPos = i + 1;
      c = 0x10000 + (((c & 0x3FF) << 10) | c2);
      out += hexTable[0xF0 | (c >> 18)] +
             hexTable[0x80 | ((c >> 12) & 0x3F)] +
             hexTable[0x80 | ((c >> 6) & 0x3F)] +
             hexTable[0x80 | (c & 0x3F)];
    }
    if (lastPos === 0)
      return str;
    if (lastPos < len)
      return out + StringPrototypeSlice(str, lastPos);
    return out;
  }

  module.exports = {
    encodeStr,
    hexTable,
    isHexTable,
  };
});

defineModule("querystring", function (module, exports, require, internalBinding, primordials) {
  'use strict';

  const {
    Array,
    ArrayIsArray,
    Int8Array,
    MathAbs,
    NumberIsFinite,
    ObjectKeys,
    String,
    StringPrototypeCharCodeAt,
    StringPrototypeSlice,
    decodeURIComponent,
  } = primordials;

  const { Buffer } = require('buffer');
  const {
    encodeStr,
    hexTable,
    isHexTable,
  } = require('internal/querystring');
  const QueryString = module.exports = {
    unescapeBuffer,
    // `unescape()` is a JS global, so we need to use a different local name
    unescape: qsUnescape,

    // `escape()` is a JS global, so we need to use a different local name
    escape: qsEscape,

    stringify,
    encode: stringify,

    parse,
    decode: parse,
  };

  const unhexTable = new Int8Array([
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 0 - 15
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 16 - 31
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 32 - 47
    +0, +1, +2, +3, +4, +5, +6, +7, +8, +9, -1, -1, -1, -1, -1, -1, // 48 - 63
    -1, 10, 11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 64 - 79
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 80 - 95
    -1, 10, 11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 96 - 111
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 112 - 127
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, // 128 ...
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  // ... 255
  ]);
  /**
   * A safe fast alternative to decodeURIComponent
   * @param {string} s
   * @param {boolean} decodeSpaces
   * @returns {string}
   */
  function unescapeBuffer(s, decodeSpaces) {
    const out = Buffer.allocUnsafe(s.length);
    let index = 0;
    let outIndex = 0;
    let currentChar;
    let nextChar;
    let hexHigh;
    let hexLow;
    const maxLength = s.length - 2;
    // Flag to know if some hex chars have been decoded
    let hasHex = false;
    while (index < s.length) {
      currentChar = StringPrototypeCharCodeAt(s, index);
      if (currentChar === 43 /* '+' */ && decodeSpaces) {
        out[outIndex++] = 32; // ' '
        index++;
        continue;
      }
      if (currentChar === 37 /* '%' */ && index < maxLength) {
        currentChar = StringPrototypeCharCodeAt(s, ++index);
        hexHigh = unhexTable[currentChar];
        if (!(hexHigh >= 0)) {
          out[outIndex++] = 37; // '%'
          continue;
        } else {
          nextChar = StringPrototypeCharCodeAt(s, ++index);
          hexLow = unhexTable[nextChar];
          if (!(hexLow >= 0)) {
            out[outIndex++] = 37; // '%'
            index--;
          } else {
            hasHex = true;
            currentChar = hexHigh * 16 + hexLow;
          }
        }
      }
      out[outIndex++] = currentChar;
      index++;
    }
    return hasHex ? out.slice(0, outIndex) : out;
  }

  /**
   * @param {string} s
   * @param {boolean} decodeSpaces
   * @returns {string}
   */
  function qsUnescape(s, decodeSpaces) {
    try {
      return decodeURIComponent(s);
    } catch {
      return QueryString.unescapeBuffer(s, decodeSpaces).toString();
    }
  }


  // These characters do not need escaping when generating query strings:
  // ! - . _ ~
  // ' ( ) *
  // digits
  // alpha (uppercase)
  // alpha (lowercase)
  const noEscape = new Int8Array([
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 0 - 15
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 16 - 31
    0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, // 32 - 47
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, // 48 - 63
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, // 64 - 79
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, // 80 - 95
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, // 96 - 111
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,  // 112 - 127
  ]);

  /**
   * QueryString.escape() replaces encodeURIComponent()
   * @see https://www.ecma-international.org/ecma-262/5.1/#sec-15.1.3.4
   * @param {any} str
   * @returns {string}
   */
  function qsEscape(str) {
    if (typeof str !== 'string') {
      if (typeof str === 'object')
        str = String(str);
      else
        str += '';
    }

    return encodeStr(str, noEscape, hexTable);
  }

  /**
   * @param {string | number | bigint | boolean | symbol | undefined | null} v
   * @returns {string}
   */
  function stringifyPrimitive(v) {
    if (typeof v === 'string')
      return v;
    if (typeof v === 'number' && NumberIsFinite(v))
      return '' + v;
    if (typeof v === 'bigint')
      return '' + v;
    if (typeof v === 'boolean')
      return v ? 'true' : 'false';
    return '';
  }

  /**
   * @param {string | number | bigint | boolean} v
   * @param {(v: string) => string} encode
   * @returns {string}
   */
  function encodeStringified(v, encode) {
    if (typeof v === 'string')
      return (v.length ? encode(v) : '');
    if (typeof v === 'number' && NumberIsFinite(v)) {
      // Values >= 1e21 automatically switch to scientific notation which requires
      // escaping due to the inclusion of a '+' in the output
      return (MathAbs(v) < 1e21 ? '' + v : encode('' + v));
    }
    if (typeof v === 'bigint')
      return '' + v;
    if (typeof v === 'boolean')
      return v ? 'true' : 'false';
    return '';
  }

  /**
   * @param {string | number | boolean | null} v
   * @param {(v: string) => string} encode
   * @returns {string}
   */
  function encodeStringifiedCustom(v, encode) {
    return encode(stringifyPrimitive(v));
  }

  /**
   * @param {Record<string, string | number | boolean
   * | ReadonlyArray<string | number | boolean> | null>} obj
   * @param {string} [sep]
   * @param {string} [eq]
   * @param {{ encodeURIComponent?: (v: string) => string }} [options]
   * @returns {string}
   */
  function stringify(obj, sep, eq, options) {
    sep = sep || '&';
    eq = eq || '=';

    let encode = QueryString.escape;
    if (options && typeof options.encodeURIComponent === 'function') {
      encode = options.encodeURIComponent;
    }
    const convert =
      (encode === qsEscape ? encodeStringified : encodeStringifiedCustom);

    if (obj !== null && typeof obj === 'object') {
      const keys = ObjectKeys(obj);
      const len = keys.length;
      let fields = '';
      for (let i = 0; i < len; ++i) {
        const k = keys[i];
        const v = obj[k];
        let ks = convert(k, encode);
        ks += eq;

        if (ArrayIsArray(v)) {
          const vlen = v.length;
          if (vlen === 0) continue;
          if (fields)
            fields += sep;
          for (let j = 0; j < vlen; ++j) {
            if (j)
              fields += sep;
            fields += ks;
            fields += convert(v[j], encode);
          }
        } else {
          if (fields)
            fields += sep;
          fields += ks;
          fields += convert(v, encode);
        }
      }
      return fields;
    }
    return '';
  }

  /**
   * @param {string} str
   * @returns {number[]}
   */
  function charCodes(str) {
    if (str.length === 0) return [];
    if (str.length === 1) return [StringPrototypeCharCodeAt(str, 0)];
    const ret = new Array(str.length);
    for (let i = 0; i < str.length; ++i)
      ret[i] = StringPrototypeCharCodeAt(str, i);
    return ret;
  }
  const defSepCodes = [38]; // &
  const defEqCodes = [61]; // =

  function addKeyVal(obj, key, value, keyEncoded, valEncoded, decode) {
    if (key.length > 0 && keyEncoded)
      key = decodeStr(key, decode);
    if (value.length > 0 && valEncoded)
      value = decodeStr(value, decode);

    if (obj[key] === undefined) {
      obj[key] = value;
    } else {
      const curValue = obj[key];
      // A simple Array-specific property check is enough here to
      // distinguish from a string value and is faster and still safe
      // since we are generating all of the values being assigned.
      if (curValue.pop)
        curValue[curValue.length] = value;
      else
        obj[key] = [curValue, value];
    }
  }

  /**
   * Parse a key/val string.
   * @param {string} qs
   * @param {string} sep
   * @param {string} eq
   * @param {{
   *   maxKeys?: number;
   *   decodeURIComponent?(v: string): string;
   *   }} [options]
   * @returns {Record<string, string | string[]>}
   */
  function parse(qs, sep, eq, options) {
    const obj = { __proto__: null };

    if (typeof qs !== 'string' || qs.length === 0) {
      return obj;
    }

    const sepCodes = (!sep ? defSepCodes : charCodes(String(sep)));
    const eqCodes = (!eq ? defEqCodes : charCodes(String(eq)));
    const sepLen = sepCodes.length;
    const eqLen = eqCodes.length;

    let pairs = 1000;
    if (options && typeof options.maxKeys === 'number') {
      // -1 is used in place of a value like Infinity for meaning
      // "unlimited pairs" because of additional checks V8 (at least as of v5.4)
      // has to do when using variables that contain values like Infinity. Since
      // `pairs` is always decremented and checked explicitly for 0, -1 works
      // effectively the same as Infinity, while providing a significant
      // performance boost.
      pairs = (options.maxKeys > 0 ? options.maxKeys : -1);
    }

    let decode = QueryString.unescape;
    if (options && typeof options.decodeURIComponent === 'function') {
      decode = options.decodeURIComponent;
    }
    const customDecode = (decode !== qsUnescape);

    let lastPos = 0;
    let sepIdx = 0;
    let eqIdx = 0;
    let key = '';
    let value = '';
    let keyEncoded = customDecode;
    let valEncoded = customDecode;
    const plusChar = (customDecode ? '%20' : ' ');
    let encodeCheck = 0;
    for (let i = 0; i < qs.length; ++i) {
      const code = StringPrototypeCharCodeAt(qs, i);

      // Try matching key/value pair separator (e.g. '&')
      if (code === sepCodes[sepIdx]) {
        if (++sepIdx === sepLen) {
          // Key/value pair separator match!
          const end = i - sepIdx + 1;
          if (eqIdx < eqLen) {
            // We didn't find the (entire) key/value separator
            if (lastPos < end) {
              // Treat the substring as part of the key instead of the value
              key += StringPrototypeSlice(qs, lastPos, end);
            } else if (key.length === 0) {
              // We saw an empty substring between separators
              if (--pairs === 0)
                return obj;
              lastPos = i + 1;
              sepIdx = eqIdx = 0;
              continue;
            }
          } else if (lastPos < end) {
            value += StringPrototypeSlice(qs, lastPos, end);
          }

          addKeyVal(obj, key, value, keyEncoded, valEncoded, decode);

          if (--pairs === 0)
            return obj;
          keyEncoded = valEncoded = customDecode;
          key = value = '';
          encodeCheck = 0;
          lastPos = i + 1;
          sepIdx = eqIdx = 0;
        }
      } else {
        sepIdx = 0;
        // Try matching key/value separator (e.g. '=') if we haven't already
        if (eqIdx < eqLen) {
          if (code === eqCodes[eqIdx]) {
            if (++eqIdx === eqLen) {
              // Key/value separator match!
              const end = i - eqIdx + 1;
              if (lastPos < end)
                key += StringPrototypeSlice(qs, lastPos, end);
              encodeCheck = 0;
              lastPos = i + 1;
            }
            continue;
          } else {
            eqIdx = 0;
            if (!keyEncoded) {
              // Try to match an (valid) encoded byte once to minimize unnecessary
              // calls to string decoding functions
              if (code === 37/* % */) {
                encodeCheck = 1;
                continue;
              } else if (encodeCheck > 0) {
                if (isHexTable[code] === 1) {
                  if (++encodeCheck === 3)
                    keyEncoded = true;
                  continue;
                } else {
                  encodeCheck = 0;
                }
              }
            }
          }
          if (code === 43/* + */) {
            if (lastPos < i)
              key += StringPrototypeSlice(qs, lastPos, i);
            key += plusChar;
            lastPos = i + 1;
            continue;
          }
        }
        if (code === 43/* + */) {
          if (lastPos < i)
            value += StringPrototypeSlice(qs, lastPos, i);
          value += plusChar;
          lastPos = i + 1;
        } else if (!valEncoded) {
          // Try to match an (valid) encoded byte (once) to minimize unnecessary
          // calls to string decoding functions
          if (code === 37/* % */) {
            encodeCheck = 1;
          } else if (encodeCheck > 0) {
            if (isHexTable[code] === 1) {
              if (++encodeCheck === 3)
                valEncoded = true;
            } else {
              encodeCheck = 0;
            }
          }
        }
      }
    }

    // Deal with any leftover key or value data
    if (lastPos < qs.length) {
      if (eqIdx < eqLen)
        key += StringPrototypeSlice(qs, lastPos);
      else if (sepIdx < sepLen)
        value += StringPrototypeSlice(qs, lastPos);
    } else if (eqIdx === 0 && key.length === 0) {
      // We ended on an empty substring
      return obj;
    }

    addKeyVal(obj, key, value, keyEncoded, valEncoded, decode);

    return obj;
  }


  /**
   * V8 does not optimize functions with try-catch blocks, so we isolate them here
   * to minimize the damage (Note: no longer true as of V8 5.4 -- but still will
   * not be inlined).
   * @param {string} s
   * @param {(v: string) => string} decoder
   * @returns {string}
   */
  function decodeStr(s, decoder) {
    try {
      return decoder(s);
    } catch {
      return QueryString.unescape(s, true);
    }
  }
});

defineModule("internal/url", function (module, exports, require, internalBinding, primordials) {
  'use strict';

  // lumen: the WHATWG URL / URLSearchParams classes are lumen-web's port of this module (the
  // globals); the rest below is verbatim from lib/internal/url.js.
  const {
    Boolean,
    Number,
    RegExpPrototypeSymbolReplace,
    SafeSet,
    StringPrototypeCharAt,
    StringPrototypeCharCodeAt,
    StringPrototypeCodePointAt,
    StringPrototypeIndexOf,
    StringPrototypeSlice,
    StringPrototypeStartsWith,
    decodeURIComponent,
  } = primordials;

  const {
    codes: {
      ERR_INVALID_ARG_TYPE,
      ERR_INVALID_ARG_VALUE,
      ERR_INVALID_FILE_URL_HOST,
      ERR_INVALID_FILE_URL_PATH,
      ERR_INVALID_URL_SCHEME,
      ERR_MISSING_ARGS,
    },
  } = require('internal/errors');
  const {
    CHAR_BACKWARD_SLASH,
    CHAR_FORWARD_SLASH,
    CHAR_LOWERCASE_A,
    CHAR_LOWERCASE_Z,
  } = require('internal/constants');
  const path = require('path');
  const { encodeStr } = require('internal/querystring');
  const { toUSVString } = require('internal/util');

  const { platform } = process;
  const isWindows = platform === 'win32';

  const bindingUrl = internalBinding('url');
  const { URL, URLSearchParams } = bindingUrl;
  const updateActions = bindingUrl.updateActions;

  const FORWARD_SLASH = /\//g;
  const SideEffectFreeRegExpPrototypeSymbolReplace = RegExpPrototypeSymbolReplace;

  const unsafeProtocol = new SafeSet([
    'javascript',
    'javascript:',
  ]);
  // Protocols that never have a hostname.
  const hostlessProtocol = new SafeSet([
    'javascript',
    'javascript:',
  ]);
  // Protocols that always contain a // bit.
  const slashedProtocol = new SafeSet([
    'http',
    'http:',
    'https',
    'https:',
    'ftp',
    'ftp:',
    'gopher',
    'gopher:',
    'file',
    'file:',
    'ws',
    'ws:',
    'wss',
    'wss:',
  ]);


  /**
   * Checks if a value has the shape of a WHATWG URL object.
   *
   * Using a symbol or instanceof would not be able to recognize URL objects
   * coming from other implementations (e.g. in Electron), so instead we are
   * checking some well known properties for a lack of a better test.
   *
   * We use `href` and `protocol` as they are the only properties that are
   * easy to retrieve and calculate due to the lazy nature of the getters.
   *
   * We check for `auth` and `path` attribute to distinguish legacy url instance with
   * WHATWG URL instance.
   * @param {*} self
   * @returns {self is URL}
   */
  function isURL(self) {
    return Boolean(self?.href && self.protocol && self.auth === undefined && self.path === undefined);
  }

  function domainToASCII(domain) {
    if (arguments.length < 1)
      throw new ERR_MISSING_ARGS('domain');

    // toUSVString is not needed.
    return bindingUrl.domainToASCII(`${domain}`);
  }

  function domainToUnicode(domain) {
    if (arguments.length < 1)
      throw new ERR_MISSING_ARGS('domain');

    // toUSVString is not needed.
    return bindingUrl.domainToUnicode(`${domain}`);
  }

  /**
   * Utility function that converts a URL object into an ordinary options object
   * as expected by the `http.request` and `https.request` APIs.
   * @param {URL} url
   * @returns {Record<string, unknown>}
   */
  function urlToHttpOptions(url) {
    const { hostname, pathname, port, username, password, search } = url;
    const options = {
      __proto__: null,
      ...url, // In case the url object was extended by the user.
      protocol: url.protocol,
      hostname: hostname && StringPrototypeStartsWith(hostname, '[') ?
        StringPrototypeSlice(hostname, 1, -1) :
        hostname,
      hash: url.hash,
      search: search,
      pathname: pathname,
      path: `${pathname || ''}${search || ''}`,
      href: url.href,
    };
    if (port !== '') {
      options.port = Number(port);
    }
    if (username || password) {
      options.auth = `${decodeURIComponent(username)}:${decodeURIComponent(password)}`;
    }
    return options;
  }

  function getPathFromURLWin32(url) {
    const hostname = url.hostname;
    let pathname = url.pathname;
    for (let n = 0; n < pathname.length; n++) {
      if (pathname[n] === '%') {
        const third = StringPrototypeCodePointAt(pathname, n + 2) | 0x20;
        if ((pathname[n + 1] === '2' && third === 102) || // 2f 2F /
            (pathname[n + 1] === '5' && third === 99)) {  // 5c 5C \
          throw new ERR_INVALID_FILE_URL_PATH(
            'must not include encoded \\ or / characters',
          );
        }
      }
    }
    pathname = SideEffectFreeRegExpPrototypeSymbolReplace(FORWARD_SLASH, pathname, '\\');
    pathname = decodeURIComponent(pathname);
    if (hostname !== '') {
      // If hostname is set, then we have a UNC path
      // Pass the hostname through domainToUnicode just in case
      // it is an IDN using punycode encoding. We do not need to worry
      // about percent encoding because the URL parser will have
      // already taken care of that for us. Note that this only
      // causes IDNs with an appropriate `xn--` prefix to be decoded.
      return `\\\\${domainToUnicode(hostname)}${pathname}`;
    }
    // Otherwise, it's a local path that requires a drive letter
    const letter = StringPrototypeCodePointAt(pathname, 1) | 0x20;
    const sep = StringPrototypeCharAt(pathname, 2);
    if (letter < CHAR_LOWERCASE_A || letter > CHAR_LOWERCASE_Z ||   // a..z A..Z
        (sep !== ':')) {
      throw new ERR_INVALID_FILE_URL_PATH('must be absolute');
    }
    return StringPrototypeSlice(pathname, 1);
  }

  function getPathFromURLPosix(url) {
    if (url.hostname !== '') {
      throw new ERR_INVALID_FILE_URL_HOST(platform);
    }
    const pathname = url.pathname;
    for (let n = 0; n < pathname.length; n++) {
      if (pathname[n] === '%') {
        const third = StringPrototypeCodePointAt(pathname, n + 2) | 0x20;
        if (pathname[n + 1] === '2' && third === 102) {
          throw new ERR_INVALID_FILE_URL_PATH(
            'must not include encoded / characters',
          );
        }
      }
    }
    return decodeURIComponent(pathname);
  }

  function fileURLToPath(path) {
    if (typeof path === 'string')
      path = new URL(path);
    else if (!isURL(path))
      throw new ERR_INVALID_ARG_TYPE('path', ['string', 'URL'], path);
    if (path.protocol !== 'file:')
      throw new ERR_INVALID_URL_SCHEME('file');
    return isWindows ? getPathFromURLWin32(path) : getPathFromURLPosix(path);
  }

  // The following characters are percent-encoded when converting from file path
  // to URL:
  // - %: The percent character is the only character not encoded by the
  //        `pathname` setter.
  // - \: Backslash is encoded on non-windows platforms since it's a valid
  //      character but the `pathname` setters replaces it by a forward slash.
  // - LF: The newline character is stripped out by the `pathname` setter.
  //       (See whatwg/url#419)
  // - CR: The carriage return character is also stripped out by the `pathname`
  //       setter.
  // - TAB: The tab character is also stripped out by the `pathname` setter.
  const percentRegEx = /%/g;
  const backslashRegEx = /\\/g;
  const newlineRegEx = /\n/g;
  const carriageReturnRegEx = /\r/g;
  const tabRegEx = /\t/g;
  const questionRegex = /\?/g;
  const hashRegex = /#/g;

  function encodePathChars(filepath) {
    if (StringPrototypeIndexOf(filepath, '%') !== -1)
      filepath = RegExpPrototypeSymbolReplace(percentRegEx, filepath, '%25');
    // In posix, backslash is a valid character in paths:
    if (!isWindows && StringPrototypeIndexOf(filepath, '\\') !== -1)
      filepath = RegExpPrototypeSymbolReplace(backslashRegEx, filepath, '%5C');
    if (StringPrototypeIndexOf(filepath, '\n') !== -1)
      filepath = RegExpPrototypeSymbolReplace(newlineRegEx, filepath, '%0A');
    if (StringPrototypeIndexOf(filepath, '\r') !== -1)
      filepath = RegExpPrototypeSymbolReplace(carriageReturnRegEx, filepath, '%0D');
    if (StringPrototypeIndexOf(filepath, '\t') !== -1)
      filepath = RegExpPrototypeSymbolReplace(tabRegEx, filepath, '%09');
    return filepath;
  }

  function pathToFileURL(filepath) {
    if (isWindows && StringPrototypeStartsWith(filepath, '\\\\')) {
      const outURL = new URL('file://');
      // UNC path format: \\server\share\resource
      const hostnameEndIndex = StringPrototypeIndexOf(filepath, '\\', 2);
      if (hostnameEndIndex === -1) {
        throw new ERR_INVALID_ARG_VALUE(
          'path',
          filepath,
          'Missing UNC resource path',
        );
      }
      if (hostnameEndIndex === 2) {
        throw new ERR_INVALID_ARG_VALUE(
          'path',
          filepath,
          'Empty UNC servername',
        );
      }
      const hostname = StringPrototypeSlice(filepath, 2, hostnameEndIndex);
      outURL.hostname = domainToASCII(hostname);
      outURL.pathname = encodePathChars(
        RegExpPrototypeSymbolReplace(backslashRegEx, StringPrototypeSlice(filepath, hostnameEndIndex), '/'));
      return outURL;
    }
    let resolved = path.resolve(filepath);
    // path.resolve strips trailing slashes so we must add them back
    const filePathLast = StringPrototypeCharCodeAt(filepath,
                                                   filepath.length - 1);
    if ((filePathLast === CHAR_FORWARD_SLASH ||
         (isWindows && filePathLast === CHAR_BACKWARD_SLASH)) &&
        resolved[resolved.length - 1] !== path.sep)
      resolved += '/';

    // Call encodePathChars first to avoid encoding % again for ? and #.
    resolved = encodePathChars(resolved);

    // Question and hash character should be included in pathname.
    // Therefore, encoding is required to eliminate parsing them in different states.
    // This is done as an optimization to not creating a URL instance and
    // later triggering pathname setter, which impacts performance
    if (StringPrototypeIndexOf(resolved, '?') !== -1)
      resolved = RegExpPrototypeSymbolReplace(questionRegex, resolved, '%3F');
    if (StringPrototypeIndexOf(resolved, '#') !== -1)
      resolved = RegExpPrototypeSymbolReplace(hashRegex, resolved, '%23');
    return new URL(`file://${resolved}`);
  }

  function toPathIfFileURL(fileURLOrPath) {
    if (!isURL(fileURLOrPath))
      return fileURLOrPath;
    return fileURLToPath(fileURLOrPath);
  }

  /**
   * This util takes a string containing a URL and return the URL origin,
   * its meant to avoid calls to `new URL` constructor.
   * @param {string} url
   * @returns {URL['origin']}
   */

  module.exports = {
    toUSVString,
    fileURLToPath,
    pathToFileURL,
    toPathIfFileURL,
    URL,
    URLSearchParams,
    domainToASCII,
    domainToUnicode,
    urlToHttpOptions,
    encodeStr,
    isURL,

    urlUpdateActions: updateActions,
    unsafeProtocol,
    hostlessProtocol,
    slashedProtocol,
  };
});

defineModule("url", function (module, exports, require, internalBinding, primordials) {
  'use strict';

  const {
    Boolean,
    Int8Array,
    ObjectKeys,
    StringPrototypeCharCodeAt,
    decodeURIComponent,
  } = primordials;

  const { toASCII } = require('internal/idna');
  const { encodeStr, hexTable } = require('internal/querystring');
  const querystring = require('querystring');

  const {
    ERR_INVALID_ARG_TYPE,
    ERR_INVALID_URL,
  } = require('internal/errors').codes;
  const {
    validateString,
    validateObject,
  } = require('internal/validators');

  // This ensures setURLConstructor() is called before the native
  // URL::ToObject() method is used.
  const { spliceOne } = require('internal/util');

  // WHATWG URL implementation provided by internal/url
  const {
    URL,
    URLSearchParams,
    domainToASCII,
    domainToUnicode,
    fileURLToPath,
    pathToFileURL: _pathToFileURL,
    urlToHttpOptions,
    unsafeProtocol,
    hostlessProtocol,
    slashedProtocol,
  } = require('internal/url');

  const bindingUrl = internalBinding('url');

  const { getOptionValue } = require('internal/options');

  // Original url.parse() API

  function Url() {
    this.protocol = null;
    this.slashes = null;
    this.auth = null;
    this.host = null;
    this.port = null;
    this.hostname = null;
    this.hash = null;
    this.search = null;
    this.query = null;
    this.pathname = null;
    this.path = null;
    this.href = null;
  }

  // Reference: RFC 3986, RFC 1808, RFC 2396

  // define these here so at least they only have to be
  // compiled once on the first module load.
  const protocolPattern = /^[a-z0-9.+-]+:/i;
  const portPattern = /:[0-9]*$/;
  const hostPattern = /^\/\/[^@/]+@[^@/]+/;

  // Special case for a simple path URL
  const simplePathPattern = /^(\/\/?(?!\/)[^?\s]*)(\?[^\s]*)?$/;

  const hostnameMaxLen = 255;
  const {
    CHAR_SPACE,
    CHAR_TAB,
    CHAR_CARRIAGE_RETURN,
    CHAR_LINE_FEED,
    CHAR_NO_BREAK_SPACE,
    CHAR_ZERO_WIDTH_NOBREAK_SPACE,
    CHAR_HASH,
    CHAR_FORWARD_SLASH,
    CHAR_LEFT_SQUARE_BRACKET,
    CHAR_RIGHT_SQUARE_BRACKET,
    CHAR_LEFT_ANGLE_BRACKET,
    CHAR_RIGHT_ANGLE_BRACKET,
    CHAR_LEFT_CURLY_BRACKET,
    CHAR_RIGHT_CURLY_BRACKET,
    CHAR_QUESTION_MARK,
    CHAR_DOUBLE_QUOTE,
    CHAR_SINGLE_QUOTE,
    CHAR_PERCENT,
    CHAR_SEMICOLON,
    CHAR_BACKWARD_SLASH,
    CHAR_CIRCUMFLEX_ACCENT,
    CHAR_GRAVE_ACCENT,
    CHAR_VERTICAL_LINE,
    CHAR_AT,
    CHAR_COLON,
  } = require('internal/constants');

  let urlParseWarned = false;

  function urlParse(url, parseQueryString, slashesDenoteHost) {
    if (!urlParseWarned && getOptionValue('--pending-deprecation')) {
      urlParseWarned = true;
      process.emitWarning(
        '`url.parse()` behavior is not standardized and prone to ' +
        'errors that have security implications. Use the WHATWG URL API ' +
        'instead. CVEs are not issued for `url.parse()` vulnerabilities.',
        'DeprecationWarning',
        'DEP0169',
      );
    }

    if (url instanceof Url) return url;

    const urlObject = new Url();
    urlObject.parse(url, parseQueryString, slashesDenoteHost);
    return urlObject;
  }

  function isIpv6Hostname(hostname) {
    return (
      StringPrototypeCharCodeAt(hostname, 0) === CHAR_LEFT_SQUARE_BRACKET &&
      StringPrototypeCharCodeAt(hostname, hostname.length - 1) ===
      CHAR_RIGHT_SQUARE_BRACKET
    );
  }

  // This prevents some common spoofing bugs due to our use of IDNA toASCII. For
  // compatibility, the set of characters we use here is the *intersection* of
  // "forbidden host code point" in the WHATWG URL Standard [1] and the
  // characters in the host parsing loop in Url.prototype.parse, with the
  // following additions:
  //
  // - ':' since this could cause a "protocol spoofing" bug
  // - '@' since this could cause parts of the hostname to be confused with auth
  // - '[' and ']' since this could cause a non-IPv6 hostname to be interpreted
  //   as IPv6 by isIpv6Hostname above
  //
  // [1]: https://url.spec.whatwg.org/#forbidden-host-code-point
  const forbiddenHostChars = /[\0\t\n\r #%/:<>?@[\\\]^|]/;
  // For IPv6, permit '[', ']', and ':'.
  const forbiddenHostCharsIpv6 = /[\0\t\n\r #%/<>?@\\^|]/;

  Url.prototype.parse = function parse(url, parseQueryString, slashesDenoteHost) {
    validateString(url, 'url');

    // Copy chrome, IE, opera backslash-handling behavior.
    // Back slashes before the query string get converted to forward slashes
    // See: https://code.google.com/p/chromium/issues/detail?id=25916
    let hasHash = false;
    let hasAt = false;
    let start = -1;
    let end = -1;
    let rest = '';
    let lastPos = 0;
    for (let i = 0, inWs = false, split = false; i < url.length; ++i) {
      const code = url.charCodeAt(i);

      // Find first and last non-whitespace characters for trimming
      const isWs = code < 33 ||
                   code === CHAR_NO_BREAK_SPACE ||
                   code === CHAR_ZERO_WIDTH_NOBREAK_SPACE;
      if (start === -1) {
        if (isWs)
          continue;
        lastPos = start = i;
      } else if (inWs) {
        if (!isWs) {
          end = -1;
          inWs = false;
        }
      } else if (isWs) {
        end = i;
        inWs = true;
      }

      // Only convert backslashes while we haven't seen a split character
      if (!split) {
        switch (code) {
          case CHAR_AT:
            hasAt = true;
            break;
          case CHAR_HASH:
            hasHash = true;
          // Fall through
          case CHAR_QUESTION_MARK:
            split = true;
            break;
          case CHAR_BACKWARD_SLASH:
            if (i - lastPos > 0)
              rest += url.slice(lastPos, i);
            rest += '/';
            lastPos = i + 1;
            break;
        }
      } else if (!hasHash && code === CHAR_HASH) {
        hasHash = true;
      }
    }

    // Check if string was non-empty (including strings with only whitespace)
    if (start !== -1) {
      if (lastPos === start) {
        // We didn't convert any backslashes

        if (end === -1) {
          if (start === 0)
            rest = url;
          else
            rest = url.slice(start);
        } else {
          rest = url.slice(start, end);
        }
      } else if (end === -1 && lastPos < url.length) {
        // We converted some backslashes and have only part of the entire string
        rest += url.slice(lastPos);
      } else if (end !== -1 && lastPos < end) {
        // We converted some backslashes and have only part of the entire string
        rest += url.slice(lastPos, end);
      }
    }

    if (!slashesDenoteHost && !hasHash && !hasAt) {
      // Try fast path regexp
      const simplePath = simplePathPattern.exec(rest);
      if (simplePath) {
        this.path = rest;
        this.href = rest;
        this.pathname = simplePath[1];
        if (simplePath[2]) {
          this.search = simplePath[2];
          if (parseQueryString) {
            this.query = querystring.parse(this.search.slice(1));
          } else {
            this.query = this.search.slice(1);
          }
        } else if (parseQueryString) {
          this.search = null;
          this.query = { __proto__: null };
        }
        return this;
      }
    }

    let proto = protocolPattern.exec(rest);
    let lowerProto;
    if (proto) {
      proto = proto[0];
      lowerProto = proto.toLowerCase();
      this.protocol = lowerProto;
      rest = rest.slice(proto.length);
    }

    // Figure out if it's got a host
    // user@server is *always* interpreted as a hostname, and url
    // resolution will treat //foo/bar as host=foo,path=bar because that's
    // how the browser resolves relative URLs.
    let slashes;
    if (slashesDenoteHost || proto || hostPattern.test(rest)) {
      slashes = rest.charCodeAt(0) === CHAR_FORWARD_SLASH &&
                rest.charCodeAt(1) === CHAR_FORWARD_SLASH;
      if (slashes && !(proto && hostlessProtocol.has(lowerProto))) {
        rest = rest.slice(2);
        this.slashes = true;
      }
    }

    if (!hostlessProtocol.has(lowerProto) &&
        (slashes || (proto && !slashedProtocol.has(proto)))) {

      // there's a hostname.
      // the first instance of /, ?, ;, or # ends the host.
      //
      // If there is an @ in the hostname, then non-host chars *are* allowed
      // to the left of the last @ sign, unless some host-ending character
      // comes *before* the @-sign.
      // URLs are obnoxious.
      //
      // ex:
      // http://a@b@c/ => user:a@b host:c
      // http://a@b?@c => user:a host:b path:/?@c

      let hostEnd = -1;
      let atSign = -1;
      let nonHost = -1;
      for (let i = 0; i < rest.length; ++i) {
        switch (rest.charCodeAt(i)) {
          case CHAR_TAB:
          case CHAR_LINE_FEED:
          case CHAR_CARRIAGE_RETURN:
            // WHATWG URL removes tabs, newlines, and carriage returns. Let's do that too.
            rest = rest.slice(0, i) + rest.slice(i + 1);
            i -= 1;
            break;
          case CHAR_SPACE:
          case CHAR_DOUBLE_QUOTE:
          case CHAR_PERCENT:
          case CHAR_SINGLE_QUOTE:
          case CHAR_SEMICOLON:
          case CHAR_LEFT_ANGLE_BRACKET:
          case CHAR_RIGHT_ANGLE_BRACKET:
          case CHAR_BACKWARD_SLASH:
          case CHAR_CIRCUMFLEX_ACCENT:
          case CHAR_GRAVE_ACCENT:
          case CHAR_LEFT_CURLY_BRACKET:
          case CHAR_VERTICAL_LINE:
          case CHAR_RIGHT_CURLY_BRACKET:
            // Characters that are never ever allowed in a hostname from RFC 2396
            if (nonHost === -1)
              nonHost = i;
            break;
          case CHAR_HASH:
          case CHAR_FORWARD_SLASH:
          case CHAR_QUESTION_MARK:
            // Find the first instance of any host-ending characters
            if (nonHost === -1)
              nonHost = i;
            hostEnd = i;
            break;
          case CHAR_AT:
            // At this point, either we have an explicit point where the
            // auth portion cannot go past, or the last @ char is the decider.
            atSign = i;
            nonHost = -1;
            break;
        }
        if (hostEnd !== -1)
          break;
      }
      start = 0;
      if (atSign !== -1) {
        this.auth = decodeURIComponent(rest.slice(0, atSign));
        start = atSign + 1;
      }
      if (nonHost === -1) {
        this.host = rest.slice(start);
        rest = '';
      } else {
        this.host = rest.slice(start, nonHost);
        rest = rest.slice(nonHost);
      }

      // pull out port.
      this.parseHost();

      // We've indicated that there is a hostname,
      // so even if it's empty, it has to be present.
      if (typeof this.hostname !== 'string')
        this.hostname = '';

      const hostname = this.hostname;

      // If hostname begins with [ and ends with ]
      // assume that it's an IPv6 address.
      const ipv6Hostname = isIpv6Hostname(hostname);

      // validate a little.
      if (!ipv6Hostname) {
        rest = getHostname(this, rest, hostname, url);
      }

      if (this.hostname.length > hostnameMaxLen) {
        this.hostname = '';
      } else {
        // Hostnames are always lower case.
        this.hostname = this.hostname.toLowerCase();
      }

      if (this.hostname !== '') {
        if (ipv6Hostname) {
          if (forbiddenHostCharsIpv6.test(this.hostname)) {
            throw new ERR_INVALID_URL(url);
          }
        } else {
          // IDNA Support: Returns a punycoded representation of "domain".
          // It only converts parts of the domain name that
          // have non-ASCII characters, i.e. it doesn't matter if
          // you call it with a domain that already is ASCII-only.
          this.hostname = toASCII(this.hostname);

          // Prevent two potential routes of hostname spoofing.
          // 1. If this.hostname is empty, it must have become empty due to toASCII
          //    since we checked this.hostname above.
          // 2. If any of forbiddenHostChars appears in this.hostname, it must have
          //    also gotten in due to toASCII. This is since getHostname would have
          //    filtered them out otherwise.
          // Rather than trying to correct this by moving the non-host part into
          // the pathname as we've done in getHostname, throw an exception to
          // convey the severity of this issue.
          if (this.hostname === '' || forbiddenHostChars.test(this.hostname)) {
            throw new ERR_INVALID_URL(url);
          }
        }
      }

      const p = this.port ? ':' + this.port : '';
      const h = this.hostname || '';
      this.host = h + p;

      // strip [ and ] from the hostname
      // the host field still retains them, though
      if (ipv6Hostname) {
        this.hostname = this.hostname.slice(1, -1);
        if (rest[0] !== '/') {
          rest = '/' + rest;
        }
      }
    }

    // Now rest is set to the post-host stuff.
    // Chop off any delim chars.
    if (!unsafeProtocol.has(lowerProto)) {
      // First, make 100% sure that any "autoEscape" chars get
      // escaped, even if encodeURIComponent doesn't think they
      // need to be.
      rest = autoEscapeStr(rest);
    }

    let questionIdx = -1;
    let hashIdx = -1;
    for (let i = 0; i < rest.length; ++i) {
      const code = rest.charCodeAt(i);
      if (code === CHAR_HASH) {
        this.hash = rest.slice(i);
        hashIdx = i;
        break;
      } else if (code === CHAR_QUESTION_MARK && questionIdx === -1) {
        questionIdx = i;
      }
    }

    if (questionIdx !== -1) {
      if (hashIdx === -1) {
        this.search = rest.slice(questionIdx);
        this.query = rest.slice(questionIdx + 1);
      } else {
        this.search = rest.slice(questionIdx, hashIdx);
        this.query = rest.slice(questionIdx + 1, hashIdx);
      }
      if (parseQueryString) {
        this.query = querystring.parse(this.query);
      }
    } else if (parseQueryString) {
      // No query string, but parseQueryString still requested
      this.search = null;
      this.query = { __proto__: null };
    }

    const useQuestionIdx =
      questionIdx !== -1 && (hashIdx === -1 || questionIdx < hashIdx);
    const firstIdx = useQuestionIdx ? questionIdx : hashIdx;
    if (firstIdx === -1) {
      if (rest.length > 0)
        this.pathname = rest;
    } else if (firstIdx > 0) {
      this.pathname = rest.slice(0, firstIdx);
    }
    if (slashedProtocol.has(lowerProto) &&
        this.hostname && !this.pathname) {
      this.pathname = '/';
    }

    // To support http.request
    if (this.pathname || this.search) {
      const p = this.pathname || '';
      const s = this.search || '';
      this.path = p + s;
    }

    // Finally, reconstruct the href based on what has been validated.
    this.href = this.format();
    return this;
  };

  let warnInvalidPort = true;
  function getHostname(self, rest, hostname, url) {
    for (let i = 0; i < hostname.length; ++i) {
      const code = hostname.charCodeAt(i);
      const isValid = (code !== CHAR_FORWARD_SLASH &&
                       code !== CHAR_BACKWARD_SLASH &&
                       code !== CHAR_HASH &&
                       code !== CHAR_QUESTION_MARK &&
                       code !== CHAR_COLON);

      if (!isValid) {
        // If leftover starts with :, then it represents an invalid port.
        // But url.parse() is lenient about it for now.
        // Issue a warning and continue.
        if (warnInvalidPort && code === CHAR_COLON) {
          const detail = `The URL ${url} is invalid. Future versions of Node.js will throw an error.`;
          process.emitWarning(detail, 'DeprecationWarning', 'DEP0170');
          warnInvalidPort = false;
        }
        self.hostname = hostname.slice(0, i);
        return `/${hostname.slice(i)}${rest}`;
      }
    }
    return rest;
  }

  // Escaped characters. Use empty strings to fill up unused entries.
  // Using Array is faster than Object/Map
  const escapedCodes = [
    /* 0 - 9 */ '', '', '', '', '', '', '', '', '', '%09',
    /* 10 - 19 */ '%0A', '', '', '%0D', '', '', '', '', '', '',
    /* 20 - 29 */ '', '', '', '', '', '', '', '', '', '',
    /* 30 - 39 */ '', '', '%20', '', '%22', '', '', '', '', '%27',
    /* 40 - 49 */ '', '', '', '', '', '', '', '', '', '',
    /* 50 - 59 */ '', '', '', '', '', '', '', '', '', '',
    /* 60 - 69 */ '%3C', '', '%3E', '', '', '', '', '', '', '',
    /* 70 - 79 */ '', '', '', '', '', '', '', '', '', '',
    /* 80 - 89 */ '', '', '', '', '', '', '', '', '', '',
    /* 90 - 99 */ '', '', '%5C', '', '%5E', '', '%60', '', '', '',
    /* 100 - 109 */ '', '', '', '', '', '', '', '', '', '',
    /* 110 - 119 */ '', '', '', '', '', '', '', '', '', '',
    /* 120 - 125 */ '', '', '', '%7B', '%7C', '%7D',
  ];

  // Automatically escape all delimiters and unwise characters from RFC 2396.
  // Also escape single quotes in case of an XSS attack.
  // Return the escaped string.
  function autoEscapeStr(rest) {
    let escaped = '';
    let lastEscapedPos = 0;
    for (let i = 0; i < rest.length; ++i) {
      // `escaped` contains substring up to the last escaped character.
      const escapedChar = escapedCodes[rest.charCodeAt(i)];
      if (escapedChar) {
        // Concat if there are ordinary characters in the middle.
        if (i > lastEscapedPos)
          escaped += rest.slice(lastEscapedPos, i);
        escaped += escapedChar;
        lastEscapedPos = i + 1;
      }
    }
    if (lastEscapedPos === 0)  // Nothing has been escaped.
      return rest;

    // There are ordinary characters at the end.
    if (lastEscapedPos < rest.length)
      escaped += rest.slice(lastEscapedPos);

    return escaped;
  }

  // Format a parsed object into a url string
  function urlFormat(urlObject, options) {
    // Ensure it's an object, and not a string url.
    // If it's an object, this is a no-op.
    // this way, you can call urlParse() on strings
    // to clean up potentially wonky urls.
    if (typeof urlObject === 'string') {
      urlObject = urlParse(urlObject);
    } else if (typeof urlObject !== 'object' || urlObject === null) {
      throw new ERR_INVALID_ARG_TYPE('urlObject',
                                     ['Object', 'string'], urlObject);
    } else if (urlObject instanceof URL) {
      let fragment = true;
      let unicode = false;
      let search = true;
      let auth = true;

      if (options) {
        validateObject(options, 'options');

        if (options.fragment != null) {
          fragment = Boolean(options.fragment);
        }

        if (options.unicode != null) {
          unicode = Boolean(options.unicode);
        }

        if (options.search != null) {
          search = Boolean(options.search);
        }

        if (options.auth != null) {
          auth = Boolean(options.auth);
        }
      }

      return bindingUrl.format(urlObject.href, fragment, unicode, search, auth);
    }

    return Url.prototype.format.call(urlObject);
  }

  // These characters do not need escaping:
  // ! - . _ ~
  // ' ( ) * :
  // digits
  // alpha (uppercase)
  // alpha (lowercase)
  const noEscapeAuth = new Int8Array([
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 0x00 - 0x0F
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 0x10 - 0x1F
    0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, // 0x20 - 0x2F
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, // 0x30 - 0x3F
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, // 0x40 - 0x4F
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, // 0x50 - 0x5F
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, // 0x60 - 0x6F
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, // 0x70 - 0x7F
  ]);

  Url.prototype.format = function format() {
    let auth = this.auth || '';
    if (auth) {
      auth = encodeStr(auth, noEscapeAuth, hexTable);
      auth += '@';
    }

    let protocol = this.protocol || '';
    let pathname = this.pathname || '';
    let hash = this.hash || '';
    let host = '';
    let query = '';

    if (this.host) {
      host = auth + this.host;
    } else if (this.hostname) {
      host = auth + (
        this.hostname.includes(':') && !isIpv6Hostname(this.hostname) ?
          '[' + this.hostname + ']' :
          this.hostname
      );
      if (this.port) {
        host += ':' + this.port;
      }
    }

    if (this.query !== null && typeof this.query === 'object') {
      query = querystring.stringify(this.query);
    }

    let search = this.search || (query && ('?' + query)) || '';

    if (protocol && protocol.charCodeAt(protocol.length - 1) !== 58/* : */)
      protocol += ':';

    let newPathname = '';
    let lastPos = 0;
    for (let i = 0; i < pathname.length; ++i) {
      switch (pathname.charCodeAt(i)) {
        case CHAR_HASH:
          if (i - lastPos > 0)
            newPathname += pathname.slice(lastPos, i);
          newPathname += '%23';
          lastPos = i + 1;
          break;
        case CHAR_QUESTION_MARK:
          if (i - lastPos > 0)
            newPathname += pathname.slice(lastPos, i);
          newPathname += '%3F';
          lastPos = i + 1;
          break;
      }
    }
    if (lastPos > 0) {
      if (lastPos !== pathname.length)
        pathname = newPathname + pathname.slice(lastPos);
      else
        pathname = newPathname;
    }

    // Only the slashedProtocols get the //.  Not mailto:, xmpp:, etc.
    // unless they had them to begin with.
    if (this.slashes || slashedProtocol.has(protocol)) {
      if (this.slashes || host) {
        if (pathname && pathname.charCodeAt(0) !== CHAR_FORWARD_SLASH)
          pathname = '/' + pathname;
        host = '//' + host;
      } else if (protocol.length >= 4 &&
                 protocol.charCodeAt(0) === 102/* f */ &&
                 protocol.charCodeAt(1) === 105/* i */ &&
                 protocol.charCodeAt(2) === 108/* l */ &&
                 protocol.charCodeAt(3) === 101/* e */) {
        host = '//';
      }
    }

    search = search.replace(/#/g, '%23');

    if (hash && hash.charCodeAt(0) !== CHAR_HASH)
      hash = '#' + hash;
    if (search && search.charCodeAt(0) !== CHAR_QUESTION_MARK)
      search = '?' + search;

    return protocol + host + pathname + search + hash;
  };

  function urlResolve(source, relative) {
    return urlParse(source, false, true).resolve(relative);
  }

  Url.prototype.resolve = function resolve(relative) {
    return this.resolveObject(urlParse(relative, false, true)).format();
  };

  function urlResolveObject(source, relative) {
    if (!source) return relative;
    return urlParse(source, false, true).resolveObject(relative);
  }

  Url.prototype.resolveObject = function resolveObject(relative) {
    if (typeof relative === 'string') {
      const rel = new Url();
      rel.parse(relative, false, true);
      relative = rel;
    }

    const result = new Url();
    const tkeys = ObjectKeys(this);
    for (let tk = 0; tk < tkeys.length; tk++) {
      const tkey = tkeys[tk];
      result[tkey] = this[tkey];
    }

    // Hash is always overridden, no matter what.
    // even href="" will remove it.
    result.hash = relative.hash;

    // If the relative url is empty, then there's nothing left to do here.
    if (relative.href === '') {
      result.href = result.format();
      return result;
    }

    // Hrefs like //foo/bar always cut to the protocol.
    if (relative.slashes && !relative.protocol) {
      // Take everything except the protocol from relative
      const rkeys = ObjectKeys(relative);
      for (let rk = 0; rk < rkeys.length; rk++) {
        const rkey = rkeys[rk];
        if (rkey !== 'protocol')
          result[rkey] = relative[rkey];
      }

      // urlParse appends trailing / to urls like http://www.example.com
      if (slashedProtocol.has(result.protocol) &&
          result.hostname && !result.pathname) {
        result.path = result.pathname = '/';
      }

      result.href = result.format();
      return result;
    }

    if (relative.protocol && relative.protocol !== result.protocol) {
      // If it's a known url protocol, then changing
      // the protocol does weird things
      // first, if it's not file:, then we MUST have a host,
      // and if there was a path
      // to begin with, then we MUST have a path.
      // if it is file:, then the host is dropped,
      // because that's known to be hostless.
      // anything else is assumed to be absolute.
      if (!slashedProtocol.has(relative.protocol)) {
        const keys = ObjectKeys(relative);
        for (let v = 0; v < keys.length; v++) {
          const k = keys[v];
          result[k] = relative[k];
        }
        result.href = result.format();
        return result;
      }

      result.protocol = relative.protocol;
      if (!relative.host &&
          !/^file:?$/.test(relative.protocol) &&
          !hostlessProtocol.has(relative.protocol)) {
        const relPath = (relative.pathname || '').split('/');
        while (relPath.length && !(relative.host = relPath.shift()));
        if (!relative.host) relative.host = '';
        if (!relative.hostname) relative.hostname = '';
        if (relPath[0] !== '') relPath.unshift('');
        if (relPath.length < 2) relPath.unshift('');
        result.pathname = relPath.join('/');
      } else {
        result.pathname = relative.pathname;
      }
      result.search = relative.search;
      result.query = relative.query;
      result.host = relative.host || '';
      result.auth = relative.auth;
      result.hostname = relative.hostname || relative.host;
      result.port = relative.port;
      // To support http.request
      if (result.pathname || result.search) {
        const p = result.pathname || '';
        const s = result.search || '';
        result.path = p + s;
      }
      result.slashes = result.slashes || relative.slashes;
      result.href = result.format();
      return result;
    }

    const isSourceAbs = (result.pathname && result.pathname.charAt(0) === '/');
    const isRelAbs = (
      relative.host || (relative.pathname && relative.pathname.charAt(0) === '/')
    );
    let mustEndAbs = (isRelAbs || isSourceAbs ||
                      (result.host && relative.pathname));
    const removeAllDots = mustEndAbs;
    let srcPath = (result.pathname && result.pathname.split('/')) || [];
    const relPath = (relative.pathname && relative.pathname.split('/')) || [];
    const noLeadingSlashes = result.protocol &&
        !slashedProtocol.has(result.protocol);

    // If the url is a non-slashed url, then relative
    // links like ../.. should be able
    // to crawl up to the hostname, as well.  This is strange.
    // result.protocol has already been set by now.
    // Later on, put the first path part into the host field.
    if (noLeadingSlashes) {
      result.hostname = '';
      result.port = null;
      if (result.host) {
        if (srcPath[0] === '') srcPath[0] = result.host;
        else srcPath.unshift(result.host);
      }
      result.host = '';
      if (relative.protocol) {
        relative.hostname = null;
        relative.port = null;
        result.auth = null;
        if (relative.host) {
          if (relPath[0] === '') relPath[0] = relative.host;
          else relPath.unshift(relative.host);
        }
        relative.host = null;
      }
      mustEndAbs = mustEndAbs && (relPath[0] === '' || srcPath[0] === '');
    }

    if (isRelAbs) {
      // it's absolute.
      if (relative.host || relative.host === '') {
        if (result.host !== relative.host) result.auth = null;
        result.host = relative.host;
        result.port = relative.port;
      }
      if (relative.hostname || relative.hostname === '') {
        if (result.hostname !== relative.hostname) result.auth = null;
        result.hostname = relative.hostname;
      }
      result.search = relative.search;
      result.query = relative.query;
      srcPath = relPath;
      // Fall through to the dot-handling below.
    } else if (relPath.length) {
      // it's relative
      // throw away the existing file, and take the new path instead.
      if (!srcPath) srcPath = [];
      srcPath.pop();
      srcPath = srcPath.concat(relPath);
      result.search = relative.search;
      result.query = relative.query;
    } else if (relative.search !== null && relative.search !== undefined) {
      // Just pull out the search.
      // like href='?foo'.
      // Put this after the other two cases because it simplifies the booleans
      if (noLeadingSlashes) {
        result.hostname = result.host = srcPath.shift();
        // Occasionally the auth can get stuck only in host.
        // This especially happens in cases like
        // url.resolveObject('mailto:local1@domain1', 'local2@domain2')
        const authInHost =
          result.host && result.host.indexOf('@') > 0 && result.host.split('@');
        if (authInHost) {
          result.auth = authInHost.shift();
          result.host = result.hostname = authInHost.shift();
        }
      }
      result.search = relative.search;
      result.query = relative.query;
      // To support http.request
      if (result.pathname !== null || result.search !== null) {
        result.path = (result.pathname ? result.pathname : '') +
                      (result.search ? result.search : '');
      }
      result.href = result.format();
      return result;
    }

    if (!srcPath.length) {
      // No path at all. All other things were already handled above.
      result.pathname = null;
      // To support http.request
      if (result.search) {
        result.path = '/' + result.search;
      } else {
        result.path = null;
      }
      result.href = result.format();
      return result;
    }

    // If a url ENDs in . or .., then it must get a trailing slash.
    // however, if it ends in anything else non-slashy,
    // then it must NOT get a trailing slash.
    let last = srcPath.slice(-1)[0];
    const hasTrailingSlash = (
      ((result.host || relative.host || srcPath.length > 1) &&
      (last === '.' || last === '..')) || last === '');

    // Strip single dots, resolve double dots to parent dir
    // if the path tries to go above the root, `up` ends up > 0
    let up = 0;
    for (let i = srcPath.length - 1; i >= 0; i--) {
      last = srcPath[i];
      if (last === '.') {
        spliceOne(srcPath, i);
      } else if (last === '..') {
        spliceOne(srcPath, i);
        up++;
      } else if (up) {
        spliceOne(srcPath, i);
        up--;
      }
    }

    // If the path is allowed to go above the root, restore leading ..s
    if (!mustEndAbs && !removeAllDots) {
      while (up--) {
        srcPath.unshift('..');
      }
    }

    if (mustEndAbs && srcPath[0] !== '' &&
        (!srcPath[0] || srcPath[0].charAt(0) !== '/')) {
      srcPath.unshift('');
    }

    if (hasTrailingSlash && (srcPath.join('/').substr(-1) !== '/')) {
      srcPath.push('');
    }

    const isAbsolute = srcPath[0] === '' ||
        (srcPath[0] && srcPath[0].charAt(0) === '/');

    // put the host back
    if (noLeadingSlashes) {
      result.hostname =
        result.host = isAbsolute ? '' : srcPath.length ? srcPath.shift() : '';
      // Occasionally the auth can get stuck only in host.
      // This especially happens in cases like
      // url.resolveObject('mailto:local1@domain1', 'local2@domain2')
      const authInHost = result.host && result.host.indexOf('@') > 0 ?
        result.host.split('@') : false;
      if (authInHost) {
        result.auth = authInHost.shift();
        result.host = result.hostname = authInHost.shift();
      }
    }

    mustEndAbs = mustEndAbs || (result.host && srcPath.length);

    if (mustEndAbs && !isAbsolute) {
      srcPath.unshift('');
    }

    if (!srcPath.length) {
      result.pathname = null;
      result.path = null;
    } else {
      result.pathname = srcPath.join('/');
    }

    // To support request.http
    if (result.pathname !== null || result.search !== null) {
      result.path = (result.pathname ? result.pathname : '') +
                    (result.search ? result.search : '');
    }
    result.auth = relative.auth || result.auth;
    result.slashes = result.slashes || relative.slashes;
    result.href = result.format();
    return result;
  };

  Url.prototype.parseHost = function parseHost() {
    let host = this.host;
    let port = portPattern.exec(host);
    if (port) {
      port = port[0];
      if (port !== ':') {
        this.port = port.slice(1);
      }
      host = host.slice(0, host.length - port.length);
    }
    if (host) this.hostname = host;
  };

  // When used internally, we are not obligated to associate TypeError with
  // this function, so non-strings can be rejected by underlying implementation.
  // Public API has to validate input and throw appropriate error.
  function pathToFileURL(path) {
    validateString(path, 'path');

    return _pathToFileURL(path);
  }

  module.exports = {
    // Original API
    Url,
    parse: urlParse,
    resolve: urlResolve,
    resolveObject: urlResolveObject,
    format: urlFormat,

    // WHATWG API
    URL,
    URLSearchParams,
    domainToASCII,
    domainToUnicode,

    // Utilities
    pathToFileURL,
    fileURLToPath,
    urlToHttpOptions,
  };
});

// ---- registration ------------------------------------------------------------------------------

__builtins.set("querystring", require("querystring"));
__builtins.set("url", require("url"));
