//! `_csv` on `lumen_common::csv`: the parser and writer are shared; this adapter converts
//! dialects, fields and errors.

/// CSV parsing and writing.
///
/// This module provides classes that assist in the reading and writing
/// of Comma Separated Value (CSV) files, and implements the interface
/// described by PEP 305.  Although many CSV files are simple to parse,
/// the format is not formally defined by a stable specification and
/// is subtle enough that parsing lines of a CSV file with something
/// like line.split(",") is bound to fail.  The module supports three
/// basic APIs: reading, writing, and registration of dialects.
///
///
/// DIALECT REGISTRATION:
///
/// Readers and writers support a dialect argument, which is a convenient
/// handle on a group of settings.  When the dialect argument is a string,
/// it identifies one of the dialects previously registered with the module.
/// If it is a class or instance, the attributes of the argument are used as
/// the settings for the reader or writer:
///
///     class excel:
///         delimiter = ','
///         quotechar = '"'
///         escapechar = None
///         doublequote = True
///         skipinitialspace = False
///         lineterminator = '\r\n'
///         quoting = QUOTE_MINIMAL
///
/// SETTINGS:
///
///     * quotechar - specifies a one-character string to use as the
///         quoting character.  It defaults to '"'.
///     * delimiter - specifies a one-character string to use as the
///         field separator.  It defaults to ','.
///     * skipinitialspace - specifies how to interpret spaces which
///         immediately follow a delimiter.  It defaults to False, which
///         means that spaces immediately following a delimiter is part
///         of the following field.
///     * lineterminator -  specifies the character sequence which should
///         terminate rows.
///     * quoting - controls when quotes should be generated by the writer.
///         It can take on any of the following module constants:
///
///         csv.QUOTE_MINIMAL means only when required, for example, when a
///             field contains either the quotechar or the delimiter
///         csv.QUOTE_ALL means that quotes are always placed around fields.
///         csv.QUOTE_NONNUMERIC means that quotes are always placed around
///             fields which do not parse as integers or floating point
///             numbers.
///         csv.QUOTE_STRINGS means that quotes are always placed around
///             fields which are strings.  Note that the Python value None
///             is not a string.
///         csv.QUOTE_NOTNULL means that quotes are only placed around fields
///             that are not the Python value None.
///         csv.QUOTE_NONE means that quotes are never placed around fields.
///     * escapechar - specifies a one-character string used to escape
///         the delimiter when quoting is set to QUOTE_NONE.
///     * doublequote - controls the handling of quotes inside fields.  When
///         True, two consecutive quotes are interpreted as one during read,
///         and when writing, each quote character embedded in the data is
///         written as two quotes
#[lumen_bind::module(name = "_csv")]
pub mod _csv {
    #![allow(clippy::new_ret_no_self)]
    use crate::bind::{is_instance, opaque_instance, type_object, KwArgs, Py, This};
    use crate::builtins::native::with_opaque;
    use crate::object::*;
    use crate::vm::{dict_set_str, Interp};
    use lumen_bind::Passed;
    use lumen_common::csv::{self as core, Quoting};

    struct State {
        error: Option<Obj>,
        dialects: Option<Obj>,
        field_limit: i64,
    }

    impl Default for State {
        fn default() -> Self {
            State {
                error: None,
                dialects: None,
                field_limit: 128 * 1024,
            }
        }
    }

    fn csv_error(it: &mut Interp, msg: &str) -> Obj {
        let cls = it
            .native_state::<State>()
            .error
            .clone()
            .unwrap_or_else(|| it.exc_type("Exception"));
        it.new_exc(&cls, vec![Value::str(msg)])
    }

    fn core_error(it: &mut Interp, e: core::Error) -> Obj {
        csv_error(it, &e.to_string())
    }

    fn registry(it: &mut Interp) -> Obj {
        if let Some(d) = it.native_state::<State>().dialects.clone() {
            return d;
        }
        let d = Object::new(Kind::Dict(std::cell::RefCell::new(
            crate::dict::PyDict::new(),
        )));
        it.native_state::<State>().dialects = Some(d.clone());
        d
    }

    fn registered(it: &mut Interp, name: &Value) -> R<Value> {
        let reg = Value::Obj(registry(it));
        match it.getitem(&reg, name) {
            Ok(v) => Ok(v),
            Err(e) if it.exc_is(&e, "KeyError") => Err(csv_error(it, "unknown dialect")),
            Err(e) => Err(e),
        }
    }

    const FIELDS: [&str; 8] = [
        "delimiter",
        "doublequote",
        "escapechar",
        "lineterminator",
        "quotechar",
        "quoting",
        "skipinitialspace",
        "strict",
    ];

    fn one_char(it: &mut Interp, name: &str, v: &Value, or_none: bool) -> R<Option<char>> {
        if or_none && v.is_none() {
            return Ok(None);
        }
        let Some(s) = v.as_str() else {
            let t = it.tp_name_of(v);
            let what = if or_none { "string or None" } else { "string" };
            return Err(it.type_error(&format!("\"{name}\" must be {what}, not {t}")));
        };
        let mut chars = s.chars();
        match (chars.next(), chars.next()) {
            (Some(c), None) => Ok(Some(c)),
            _ => Err(it.type_error(&format!("\"{name}\" must be a 1-character string"))),
        }
    }

    /// `_csv.Dialect(dialect, **fmtparams)`'s settings: each given value, else the base
    /// dialect's attribute, else the default.
    fn settings(
        it: &mut Interp,
        base: Option<&Value>,
        given: [Option<Value>; 8],
    ) -> R<core::Dialect> {
        let mut vals = given;
        if let Some(b) = base {
            for (slot, name) in vals.iter_mut().zip(FIELDS) {
                if slot.is_none() {
                    *slot = it.get_attr_str(b, name).ok();
                }
            }
        }
        let [delimiter, doublequote, escapechar, lineterminator, quotechar, quoting, skipinitialspace, strict] =
            vals;
        let mut d = core::Dialect::default();
        if let Some(v) = &delimiter {
            d.delimiter = one_char(it, "delimiter", v, false)?.unwrap_or(',');
        }
        if let Some(v) = &doublequote {
            d.doublequote = it.truthy(v)?;
        }
        if let Some(v) = &escapechar {
            d.escapechar = one_char(it, "escapechar", v, true)?;
        }
        match &lineterminator {
            Some(v) if v.is_none() => return Err(it.type_error("lineterminator must be set")),
            Some(v) => match v.as_str() {
                Some(s) => d.lineterminator = s.to_string(),
                None => return Err(it.type_error("\"lineterminator\" must be a string")),
            },
            None => {}
        }
        if let Some(v) = &quotechar {
            d.quotechar = one_char(it, "quotechar", v, true)?;
        }
        if let Some(v) = &quoting {
            let n = match v {
                Value::Int(n) => *n,
                Value::Obj(o)
                    if matches!(o.kind, Kind::Int(_))
                        && o.cls
                            .as_ref()
                            .is_none_or(|c| std::rc::Rc::ptr_eq(c, &it.types.int)) =>
                {
                    i64::MAX
                }
                _ => return Err(it.type_error("\"quoting\" must be an integer")),
            };
            d.quoting =
                Quoting::from_i64(n).ok_or_else(|| it.type_error("bad \"quoting\" value"))?;
        }
        if let Some(v) = &skipinitialspace {
            d.skipinitialspace = it.truthy(v)?;
        }
        if let Some(v) = &strict {
            d.strict = it.truthy(v)?;
        }
        if quotechar.as_ref().is_some_and(Value::is_none) && quoting.is_none() {
            d.quoting = Quoting::None;
        }
        if d.quoting != Quoting::None && d.quotechar.is_none() {
            return Err(it.type_error("quotechar must be set if quoting enabled"));
        }
        Ok(d)
    }

    /// CSV dialect
    ///
    /// The Dialect type records CSV parsing and generation options.
    #[class(name = "Dialect", module = "_csv")]
    pub struct Dialect {
        d: core::Dialect,
    }

    fn char_or_none(c: Option<char>) -> Value {
        c.map_or(Value::None, |c| Value::string(c.to_string()))
    }

    #[methods]
    impl Dialect {
        #[constructor]
        #[allow(clippy::too_many_arguments)]
        fn new(
            cls: This<Value>,
            it: &mut Interp,
            #[kw] dialect: Option<&Value>,
            #[kw] delimiter: Passed<&Value>,
            #[kw] doublequote: Passed<&Value>,
            #[kw] escapechar: Passed<&Value>,
            #[kw] lineterminator: Passed<&Value>,
            #[kw] quotechar: Passed<&Value>,
            #[kw] quoting: Passed<&Value>,
            #[kw] skipinitialspace: Passed<&Value>,
            #[kw] strict: Passed<&Value>,
        ) -> R<Value> {
            let given = [
                delimiter,
                doublequote,
                escapechar,
                lineterminator,
                quotechar,
                quoting,
                skipinitialspace,
                strict,
            ]
            .map(|v| v.0.cloned());
            let base = match dialect {
                Some(v) if v.as_str().is_some() => Some(registered(it, v)?),
                Some(v) => Some(v.clone()),
                None => None,
            };
            if let Some(b) = &base {
                if is_instance::<Dialect>(it, b) && given.iter().all(Option::is_none) {
                    return Ok(b.clone());
                }
            }
            let d = settings(it, base.as_ref(), given)?;
            let Value::Obj(cls) = &cls.0 else {
                unreachable!()
            };
            Ok(opaque_instance(cls, Dialect { d }))
        }

        #[getter]
        fn delimiter(&self) -> Value {
            Value::string(self.d.delimiter.to_string())
        }

        #[getter]
        fn escapechar(&self) -> Value {
            char_or_none(self.d.escapechar)
        }

        #[getter]
        fn quotechar(&self) -> Value {
            char_or_none(self.d.quotechar)
        }

        #[getter]
        fn lineterminator(&self) -> String {
            self.d.lineterminator.clone()
        }

        #[getter]
        fn quoting(&self) -> i64 {
            self.d.quoting as i64
        }

        #[getter]
        fn doublequote(&self) -> bool {
            self.d.doublequote
        }

        #[getter]
        fn skipinitialspace(&self) -> bool {
            self.d.skipinitialspace
        }

        #[getter]
        fn strict(&self) -> bool {
            self.d.strict
        }

        /// raises an exception to avoid pickling
        #[method(name = "__reduce__")]
        fn reduce(slf: This<Value>, it: &mut Interp, #[varargs] args: &[Value]) -> R<Value> {
            let _ = args;
            reduce_error(it, &slf.0)
        }

        /// raises an exception to avoid pickling
        #[method(name = "__reduce_ex__")]
        fn reduce_ex(slf: This<Value>, it: &mut Interp, #[varargs] args: &[Value]) -> R<Value> {
            let _ = args;
            reduce_error(it, &slf.0)
        }
    }

    fn reduce_error(it: &mut Interp, v: &Value) -> R<Value> {
        let t = it.type_of(v);
        let name = it.type_name(&t);
        Err(it.type_error(&format!("cannot pickle '{name}' instances")))
    }

    /// The `Dialect` for a reader, writer or registration: `Dialect(dialect, **kwargs)`.
    fn call_dialect(
        it: &mut Interp,
        dialect: Option<&Value>,
        kw: Vec<(Obj, Value)>,
    ) -> R<(Value, core::Dialect)> {
        let cls = Value::Obj(type_object::<Dialect>(it));
        let v = it.call(&cls, dialect.into_iter().cloned().collect(), kw)?;
        let d = with_opaque::<Dialect, _>(&v, |d| d.d.clone()).unwrap_or_default();
        Ok((v, d))
    }

    fn unpack<'a>(it: &mut Interp, args: &'a [Value]) -> R<(&'a Value, Option<&'a Value>)> {
        match args {
            [a] => Ok((a, None)),
            [a, b] => Ok((a, Some(b))),
            [] => Err(it.type_error(" expected at least 1 argument, got 0")),
            _ => Err(it.type_error(&format!(
                " expected at most 2 arguments, got {}",
                args.len()
            ))),
        }
    }

    /// CSV reader
    ///
    /// Reader objects are responsible for reading and parsing tabular data
    /// in CSV format.
    #[class(name = "reader", module = "_csv", skip(py))]
    pub struct Reader {
        input: Value,
        dialect: Value,
        d: core::Dialect,
        parser: core::Parser,
        line_num: u64,
    }

    #[methods]
    impl Reader {
        #[proto(iter)]
        fn iter(slf: This<Value>) -> Value {
            slf.0
        }

        #[proto(next)]
        fn next(slf: This<Py<Self>>, it: &mut Interp) -> R<Option<Value>> {
            let r = slf.0;
            let (input, d) = r.with(it, |s| {
                s.parser.reset();
                (s.input.clone(), s.d.clone())
            })?;
            loop {
                let Some(line) = it.iter_next(&input)? else {
                    let pending = r
                        .with(it, |s| s.parser.finish(&d))?
                        .map_err(|e| core_error(it, e))?;
                    if !pending {
                        return Ok(None);
                    }
                    break;
                };
                let Some(text) = line.as_str() else {
                    let t = it.tp_name_of(&line);
                    return Err(csv_error(it, &format!("iterator should return strings, not {t} (the file should be opened in text mode)")));
                };
                let limit = it.native_state::<State>().field_limit;
                let done = r.with(it, |s| {
                    s.line_num += 1;
                    s.parser
                        .feed_line(&d, text, limit)
                        .map(|_| s.parser.record_done())
                })?;
                if done.map_err(|e| core_error(it, e))? {
                    break;
                }
            }
            let fields = r.with(it, |s| s.parser.take_fields())?;
            let mut out = Vec::with_capacity(fields.len());
            for f in fields {
                if f.null {
                    out.push(Value::None);
                    continue;
                }
                let v = Value::string(f.text);
                out.push(match f.numeric {
                    true => {
                        let float = Value::Obj(it.types.float.clone());
                        it.call(&float, vec![v], Vec::new())?
                    }
                    false => v,
                });
            }
            Ok(Some(Value::list(out)))
        }

        #[getter]
        fn dialect(&self) -> Value {
            self.dialect.clone()
        }

        #[getter]
        fn line_num(&self) -> u64 {
            self.line_num
        }
    }

    /// CSV writer
    ///
    /// Writer objects are responsible for generating tabular data
    /// in CSV format from sequence input.
    #[class(name = "writer", module = "_csv", skip(py))]
    pub struct Writer {
        write: Value,
        dialect: Value,
        d: core::Dialect,
    }

    fn write_row(it: &mut Interp, write: &Value, d: &core::Dialect, row: &Value) -> R<Value> {
        let iter = match it.get_iter(row) {
            Ok(i) => i,
            Err(e) if it.exc_is(&e, "TypeError") => {
                let t = it.tp_name_of(row);
                return Err(csv_error(it, &format!("iterable expected, not {t}")));
            }
            Err(e) => return Err(e),
        };
        let mut w = core::RowWriter::default();
        while let Some(field) = it.iter_next(&iter)? {
            let is_str = field.as_str().is_some();
            let quoted = match d.quoting {
                Quoting::NonNumeric => !it.number_check(&field),
                Quoting::All => true,
                Quoting::Strings => is_str,
                Quoting::NotNull => !field.is_none(),
                Quoting::Minimal | Quoting::None => false,
            };
            let text = match &field {
                Value::None => None,
                v if is_str => v.as_str().map(str::to_string),
                v => Some(it.str_of(v)?),
            };
            w.append(d, text.as_deref(), quoted)
                .map_err(|e| core_error(it, e))?;
        }
        let line = w.finish(d).map_err(|e| core_error(it, e))?;
        it.call(write, vec![Value::string(line)], Vec::new())
    }

    #[methods]
    impl Writer {
        /// writerow(iterable)
        ///
        /// Construct and write a CSV record from an iterable of fields.  Non-string
        /// elements will be converted to string.
        fn writerow(slf: This<Py<Self>>, it: &mut Interp, row: &Value) -> R<Value> {
            let (write, d) = slf.0.with(it, |s| (s.write.clone(), s.d.clone()))?;
            write_row(it, &write, &d, row)
        }

        /// writerows(iterable of iterables)
        ///
        /// Construct and write a series of iterables to a csv file.  Non-string
        /// elements will be converted to string.
        fn writerows(slf: This<Py<Self>>, it: &mut Interp, rows: &Value) -> R<()> {
            let (write, d) = slf.0.with(it, |s| (s.write.clone(), s.d.clone()))?;
            let iter = it.get_iter(rows)?;
            while let Some(row) = it.iter_next(&iter)? {
                write_row(it, &write, &d, &row)?;
            }
            Ok(())
        }

        #[getter]
        fn dialect(&self) -> Value {
            self.dialect.clone()
        }
    }

    ///     csv_reader = reader(iterable [, dialect='excel']
    ///                         [optional keyword args])
    ///     for row in csv_reader:
    ///         process(row)
    ///
    /// The "iterable" argument can be any object that returns a line
    /// of input for each iteration, such as a file object or a list.  The
    /// optional "dialect" parameter is discussed below.  The function
    /// also accepts optional keyword arguments which override settings
    /// provided by the dialect.
    ///
    /// The returned object is an iterator.  Each iteration returns a row
    /// of the CSV file (which can span multiple input lines).
    #[op(hint(py(text_signature = "")))]
    fn reader(it: &mut Interp, #[varargs] args: &[Value], #[varkw] kw: KwArgs) -> R<Value> {
        let (iterable, dialect) = unpack(it, args)?;
        let input = it.get_iter(iterable)?;
        let (dialect, d) = call_dialect(it, dialect, kw.to_vec())?;
        let cls = type_object::<Reader>(it);
        Ok(opaque_instance(
            &cls,
            Reader {
                input,
                dialect,
                d,
                parser: core::Parser::default(),
                line_num: 0,
            },
        ))
    }

    ///     csv_writer = csv.writer(fileobj [, dialect='excel']
    ///                             [optional keyword args])
    ///     for row in sequence:
    ///         csv_writer.writerow(row)
    ///
    ///     [or]
    ///
    ///     csv_writer = csv.writer(fileobj [, dialect='excel']
    ///                             [optional keyword args])
    ///     csv_writer.writerows(rows)
    ///
    /// The "fileobj" argument can be any object that supports the file API.
    #[op(hint(py(text_signature = "")))]
    fn writer(it: &mut Interp, #[varargs] args: &[Value], #[varkw] kw: KwArgs) -> R<Value> {
        let (file, dialect) = unpack(it, args)?;
        let write = match it.get_attr_str(file, "write") {
            Ok(w) if it.is_callable(&w) => w,
            Err(e) if !it.exc_is(&e, "AttributeError") => return Err(e),
            _ => return Err(it.type_error("argument 1 must have a \"write\" method")),
        };
        let (dialect, d) = call_dialect(it, dialect, kw.to_vec())?;
        let cls = type_object::<Writer>(it);
        Ok(opaque_instance(&cls, Writer { write, dialect, d }))
    }

    /// Create a mapping from a string name to a dialect class.
    ///     dialect = csv.register_dialect(name[, dialect[, **fmtparams]])
    #[op(hint(py(text_signature = "")))]
    fn register_dialect(it: &mut Interp, #[varargs] args: &[Value], #[varkw] kw: KwArgs) -> R<()> {
        let (name, dialect) = unpack(it, args)?;
        if name.as_str().is_none() {
            return Err(it.type_error("dialect name must be a string"));
        }
        let (dialect, _) = call_dialect(it, dialect, kw.to_vec())?;
        let reg = Value::Obj(registry(it));
        it.setitem(&reg, name.clone(), dialect)
    }

    /// Delete the name/dialect mapping associated with a string name.
    ///
    ///     csv.unregister_dialect(name)
    #[op]
    fn unregister_dialect(it: &mut Interp, #[kw] name: &Value) -> R<()> {
        let reg = Value::Obj(registry(it));
        match it.delitem(&reg, name) {
            Ok(()) => Ok(()),
            Err(e) if it.exc_is(&e, "KeyError") => Err(csv_error(it, "unknown dialect")),
            Err(e) => Err(e),
        }
    }

    /// Return the dialect instance associated with name.
    ///
    ///     dialect = csv.get_dialect(name)
    #[op]
    fn get_dialect(it: &mut Interp, #[kw] name: &Value) -> R<Value> {
        registered(it, name)
    }

    /// Return a list of all known dialect names.
    ///
    ///     names = csv.list_dialects()
    #[op]
    fn list_dialects(it: &mut Interp) -> R<Value> {
        let reg = Value::Obj(registry(it));
        let keys = it.call_method(&reg, "keys", Vec::new())?;
        Ok(Value::list(it.iterate_to_vec(&keys)?))
    }

    /// Sets an upper limit on parsed fields.
    ///
    ///     csv.field_size_limit([limit])
    ///
    /// Returns old limit. If limit is not given, no new limit is set and
    /// the old limit is returned
    #[op]
    fn field_size_limit(it: &mut Interp, #[kw] new_limit: Option<&Value>) -> R<i64> {
        let old = it.native_state::<State>().field_limit;
        if let Some(v) = new_limit {
            let exact_int = match v {
                Value::Int(_) => true,
                Value::Obj(o) => {
                    matches!(o.kind, Kind::Int(_))
                        && o.cls
                            .as_ref()
                            .is_none_or(|c| std::rc::Rc::ptr_eq(c, &it.types.int))
                }
                _ => false,
            };
            if !exact_int {
                return Err(it.type_error("limit must be an integer"));
            }
            let n = it.index_of(v)?;
            it.native_state::<State>().field_limit = n;
        }
        Ok(old)
    }

    #[init]
    fn init(it: &mut Interp, m: &Value) {
        let Value::Obj(m) = m else { return };
        let d = it.module_dict(m);
        let exc = it.exc_type("Exception");
        let error =
            crate::builtins::native::new_type(it, "_csv", "Error", Some(&exc), Layout::Exception);
        it.native_state::<State>().error = Some(error.clone());
        dict_set_str(&d, "Error", Value::Obj(error));
        let reg = registry(it);
        dict_set_str(&d, "_dialects", Value::Obj(reg));
        for (name, q) in Quoting::NAMES {
            dict_set_str(&d, name, Value::Int(q as i64));
        }
        let reader = type_object::<Reader>(it);
        dict_set_str(&d, "Reader", Value::Obj(reader));
        let writer = type_object::<Writer>(it);
        dict_set_str(&d, "Writer", Value::Obj(writer));
    }
}
