// node:crypto and the WebCrypto API — Node 20.11's lib/crypto.js and lib/internal/crypto/*.js, run
// as-is over lumen's RustCrypto-backed native ops.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/cryptogen/gen.js (see tools/README.md).
//
// Generated: the Node sources below are verbatim, each wrapped as a CommonJS-style module; the few
// edits are marked `lumen:`. They reach the platform only through `internalBinding('crypto')`, the
// object the binding files (tools/cryptogen/binding/*.js) build over the `__cryptoBinding` ops
// (src/crypto/*.rs). lumen carries no cryptography of its own: every primitive is a RustCrypto
// crate, on every platform.

const primordials = __primordials;
const isWindows = process.platform === "win32";

// ---- the module table -------------------------------------------------------------------------
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}
function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {} };
    moduleCache.set(id, module);
    fn(module, module.exports, require, internalBinding, primordials);
    return module.exports;
  }
  const value = builtinModule(id);
  moduleCache.set(id, { exports: value });
  return value;
}
function builtinModule(id) {
  switch (id) {
    case "buffer": case "stream": case "string_decoder": case "util": case "events":
      return __builtins.get(id);
    case "internal/util/types":
      return __builtins.get("util").types;
    case "internal/util/inspect":
      return { inspect: __builtins.get("util").inspect };
    case "_tls_common":
      return __builtins.get("tls");
  }
  throw new Error(`lumen crypto: internal module '${id}' is not available`);
}

const { Buffer } = __builtins.get("buffer");
const codes = __errors;

// ---- error codes the shared table lacks -------------------------------------------------------
{
  const plain = (key, message, Base) => {
    if (codes[key]) return;
    codes[key] = {
      [key]: function (...args) {
        let i = 0;
        const text = typeof message === "function" ? message(...args) :
          message.replace(/%s/g, () => String(args[i++]));
        return __nodeError(Base, key, text);
      },
    }[key];
  };
  plain("ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED", "Custom engines not supported by this OpenSSL", Error);
  plain("ERR_CRYPTO_ECDH_INVALID_FORMAT", "Invalid ECDH format: %s", TypeError);
  plain("ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY", "Public key is not valid for specified curve", Error);
  plain("ERR_CRYPTO_ENGINE_UNKNOWN", 'Engine "%s" was not found', Error);
  plain("ERR_CRYPTO_FIPS_FORCED", "Cannot set FIPS mode, it was forced with --force-fips at startup.", Error);
  plain("ERR_CRYPTO_INCOMPATIBLE_KEY", "Incompatible %s: %s", Error);
  plain("ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS", "The selected key encoding %s %s.", Error);
  plain("ERR_CRYPTO_INVALID_JWK", "Invalid JWK data", TypeError);
  plain("ERR_CRYPTO_INVALID_KEY_OBJECT_TYPE", "Invalid key object type %s, expected %s.", TypeError);
  plain("ERR_CRYPTO_SCRYPT_INVALID_PARAMETER", "Invalid scrypt parameter", Error);
  plain("ERR_CRYPTO_SCRYPT_NOT_SUPPORTED", "Scrypt algorithm not supported", Error);
  plain("ERR_CRYPTO_SIGN_KEY_REQUIRED", "No key provided to sign", Error);
  plain("ERR_INCOMPATIBLE_OPTION_PAIR", 'Option "%s" cannot be used in combination with option "%s"', TypeError);
  plain("ERR_OSSL_BN_BITS_TOO_SMALL", "bits too small", Error);
}
const internalErrors = { codes, hideStackFrames: (fn) => fn };

// ---- internal/util and friends ----------------------------------------------------------------

const kEmptyObject = Object.freeze({ __proto__: null });
const kEnumerableProperty = { __proto__: null, enumerable: true };
Object.freeze(kEnumerableProperty);

function cachedResult(fn) {
  let result;
  return () => {
    if (result === undefined) result = fn();
    return result.slice();
  };
}

function filterDuplicateStrings(items, low) {
  const map = new Map();
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const key = item.toLowerCase();
    if (low) {
      map.set(key, key);
    } else {
      map.set(key, map.get(key) === undefined ? item : key);
    }
  }
  return [...map.values()].sort();
}

function normalizeEncoding(enc) {
  if (enc == null || enc === "utf8" || enc === "utf-8") return "utf8";
  switch (String(enc).toLowerCase()) {
    case "utf8": case "utf-8": return "utf8";
    case "ucs2": case "ucs-2": case "utf16le": case "utf-16le": return "utf16le";
    case "latin1": case "binary": return "latin1";
    case "base64": case "base64url": case "hex": case "ascii":
      return String(enc).toLowerCase();
    default: return undefined;
  }
}

const emittedExperimental = new Set();
const internalUtil = {
  kEmptyObject,
  kEnumerableProperty,
  cachedResult,
  filterDuplicateStrings,
  normalizeEncoding,
  customInspectSymbol: Symbol.for("nodejs.util.inspect.custom"),
  assertCrypto() {},
  lazyDOMException: (message, name) => new DOMException(message, name),
  deprecate: (fn, msg, code) => __builtins.get("util").deprecate(fn, msg, code),
  get promisify() { return __builtins.get("util").promisify; },
  get customPromisifyArgs() { return __internals.get("customPromisifyArgs"); },
  emitExperimentalWarning(feature) {
    if (emittedExperimental.has(feature)) return;
    emittedExperimental.add(feature);
    process.emitWarning(`${feature} is an experimental feature and might change at any time`, "ExperimentalWarning");
  },
  setOwnProperty(obj, key, value) {
    return Object.defineProperty(obj, key, {
      __proto__: null, configurable: true, enumerable: true, value, writable: true,
    });
  },
};

const optionDefaults = {
  "--secure-heap": 0,
  "--secure-heap-min": 2,
  "--force-fips": false,
  "--enable-fips": false,
  "--pending-deprecation": false,
};
function getOptionValue(name) {
  const parsed = process[Symbol.for("lumen.options")];
  if (parsed !== undefined && Object.hasOwn(parsed, name)) return parsed[name];
  return optionDefaults[name];
}

function internalAssert(value, message) {
  if (!value) throw new codes.ERR_INTERNAL_ASSERTION(message);
}
internalAssert.fail = (message) => {
  throw new codes.ERR_INTERNAL_ASSERTION(message);
};

// Objects that structuredClone / MessagePort transfer rebuild from their `kClone` data.
const kClone = Symbol("kClone");
const kDeserialize = Symbol("kDeserialize");
class JSTransferable {}
function makeTransferable(obj) {
  return obj;
}

const shims = {
  __proto__: null,
  "internal/errors": internalErrors,
  "internal/util": internalUtil,
  "internal/options": { getOptionValue },
  "internal/assert": internalAssert,
  "internal/buffer": { FastBuffer: function FastBuffer(arrayBuffer, byteOffset, length) {
    return Buffer.from(arrayBuffer, byteOffset, length);
  } },
  "internal/encoding": { get TextDecoder() { return globalThis.TextDecoder; }, get TextEncoder() { return globalThis.TextEncoder; } },
  "internal/worker": { ownsProcessState: true },
  "internal/worker/js_transferable": { JSTransferable, kClone, kDeserialize, makeTransferable },
};
for (const id of Object.keys(shims)) moduleCache.set(id, { exports: shims[id] });

