// node:net, node:http and node:https — Node 20.11's lib/net.js, lib/_http_*.js, lib/http.js,
// lib/https.js and the internal modules they import, run as-is over lumen's socket ops.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/netgen/gen.js (see tools/README.md).
//
// Generated: the Node sources below are verbatim, each wrapped as a CommonJS-style module; the
// few edits are marked `lumen:`. They reach the platform only through the internalBinding()
// objects this file implements:
//   - tcp_wrap / pipe_wrap / stream_wrap: libuv-style stream handles over the `__net` ops
//     (net.rs). A handle reads with one blocking read in flight at a time, re-armed while
//     `readStart()` is on; data that lands after `readStop()` is held until the next
//     `readStart()`. Writes are always asynchronous (kLastWriteWasAsync = 1).
//   - http_parser: an llhttp-compatible HTTP/1.x parser (HTTPParser + ConnectionsList) in JS,
//     with llhttp's callbacks, return-value protocol, error codes and upgrade handling.
//   - uv, block_list, trace_events, symbols: small tables and value types.
// Errors carry libuv's names and errno values (see `__uvErrmap` in preamble.js).

const primordials = __primordials;
const isWindows = process.platform === "win32";

// ---- the module table -------------------------------------------------------------------------
// `defineModule(id, fn)` registers a module body, which is evaluated on its first `require`.
// Cycles resolve as in CommonJS: a module is cached before its body runs.
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}
function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {} };
    moduleCache.set(id, module);
    fn(module, module.exports, require, internalBinding, primordials);
    return module.exports;
  }
  const value = builtinModule(id);
  moduleCache.set(id, { exports: value });
  return value;
}
function builtinModule(id) {
  switch (id) {
    case "buffer": case "events": case "stream": case "timers": case "util": case "dns": case "tls":
    case "async_hooks": case "diagnostics_channel": case "path": case "cluster":
      return __builtins.get(id);
    case "internal/util/types":
      return __builtins.get("util").types;
    case "internal/util/inspect":
      return { inspect: __builtins.get("util").inspect };
    case "internal/url": {
      const url = __builtins.get("url");
      const isURL = (self) => Boolean(self?.href && self.protocol && self.auth === undefined && self.path === undefined);
      return { URL, urlToHttpOptions: url.urlToHttpOptions, isURL };
    }
  }
  throw new Error(`lumen net: internal module '${id}' is not available`);
}

const { Buffer } = __builtins.get("buffer");
const { codes } = { codes: __errors };

// ---- internal/errors --------------------------------------------------------------------------

const uvUnmappedError = ["UNKNOWN", "unknown error"];
function uvErrmapGet(errno) {
  return __uvErrmap.get(errno);
}
function getSystemErrorName(errno) {
  const entry = __uvErrmap.get(errno);
  return entry ? entry[0] : `Unknown system error ${errno}`;
}
function uvException(ctx) {
  const { 0: code, 1: uvmsg } = uvErrmapGet(ctx.errno) || uvUnmappedError;
  let message = `${code}: ${ctx.message || uvmsg}, ${ctx.syscall}`;
  let path, dest;
  if (ctx.path) {
    path = ctx.path.toString();
    message += ` '${path}'`;
  }
  if (ctx.dest) {
    dest = ctx.dest.toString();
    message += ` -> '${dest}'`;
  }
  const err = new Error(message);
  for (const prop of Object.keys(ctx)) {
    if (prop === "message" || prop === "path" || prop === "dest") continue;
    err[prop] = ctx[prop];
  }
  err.code = code;
  if (path) err.path = path;
  if (dest) err.dest = dest;
  return err;
}
function uvExceptionWithHostPort(err, syscall, address, port) {
  const { 0: code, 1: uvmsg } = uvErrmapGet(err) || uvUnmappedError;
  const message = `${syscall} ${code}: ${uvmsg}`;
  let details = "";
  if (port && port > 0) details = ` ${address}:${port}`;
  else if (address) details = ` ${address}`;
  const ex = new Error(`${message}${details}`);
  ex.code = code;
  ex.errno = err;
  ex.syscall = syscall;
  ex.address = address;
  if (port) ex.port = port;
  return ex;
}
function errnoException(err, syscall, original) {
  const code = getSystemErrorName(err);
  const message = original ? `${syscall} ${code} ${original}` : `${syscall} ${code}`;
  const ex = new Error(message);
  ex.errno = err;
  ex.code = code;
  ex.syscall = syscall;
  return ex;
}
function exceptionWithHostPort(err, syscall, address, port, additional) {
  const code = getSystemErrorName(err);
  let details = "";
  if (port && port > 0) details = ` ${address}:${port}`;
  else if (address) details = ` ${address}`;
  if (additional) details += ` - Local (${additional})`;
  const ex = new Error(`${syscall} ${code}${details}`);
  ex.errno = err;
  ex.code = code;
  ex.syscall = syscall;
  ex.address = address;
  if (port) ex.port = port;
  return ex;
}
function dnsException(code, syscall, hostname) {
  let errno;
  if (typeof code === "number") {
    errno = code;
    if (code === __uvCodes.get("EAI_NODATA") || code === __uvCodes.get("EAI_NONAME")) code = "ENOTFOUND";
    else code = getSystemErrorName(code);
  }
  const ex = new Error(`${syscall} ${code}${hostname ? ` ${hostname}` : ""}`);
  ex.errno = errno;
  ex.code = code;
  ex.syscall = syscall;
  if (hostname) ex.hostname = hostname;
  return ex;
}
function connResetException(msg) {
  const ex = new Error(msg);
  ex.code = "ECONNRESET";
  return ex;
}
function aggregateErrors(errors, message, code) {
  const err = new AggregateError(errors, message);
  err.code = errors[0]?.code;
  return err;
}
function genericNodeError(message, errorProperties) {
  const err = new Error(message);
  Object.assign(err, errorProperties);
  return err;
}
const internalErrors = {
  codes, uvErrmapGet, uvException, uvExceptionWithHostPort, errnoException, exceptionWithHostPort,
  dnsException, connResetException, aggregateErrors, genericNodeError,
  hideStackFrames: (fn) => fn,
};

// ---- internal/util, internal/async_hooks, internal/timers and friends ---------------------------

const kEmptyObject = Object.freeze({ __proto__: null });
function once(callback) {
  let called = false;
  return function (...args) {
    if (called) return;
    called = true;
    return Reflect.apply(callback, this, args);
  };
}
const internalUtil = {
  kEmptyObject,
  once,
  customInspectSymbol: Symbol.for("nodejs.util.inspect.custom"),
  // lumen wraps no raw OS descriptors as sockets, so no fd is a TCP or PIPE handle.
  guessHandleType: (_fd) => "UNKNOWN",
  normalizeEncoding: (enc) => __builtins.get("util")._normalizeEncoding?.(enc) ?? normalizeEncoding(enc),
  assertCrypto() {},
  deprecate: (fn, msg, code) => __builtins.get("util").deprecate(fn, msg, code),
  get promisify() { return __builtins.get("util").promisify; },
  spliceOne(list, index) {
    for (; index + 1 < list.length; index++) list[index] = list[index + 1];
    list.pop();
  },
};
function normalizeEncoding(enc) {
  if (enc == null || enc === "utf8" || enc === "utf-8") return "utf8";
  switch (String(enc).toLowerCase()) {
    case "utf8": case "utf-8": return "utf8";
    case "ucs2": case "ucs-2": case "utf16le": case "utf-16le": return "utf16le";
    case "latin1": case "binary": return "latin1";
    case "base64": case "base64url": case "hex": case "ascii":
      return String(enc).toLowerCase();
    default: return undefined;
  }
}

let asyncIdCounter = 100;
const newAsyncId = () => ++asyncIdCounter;
const asyncHookSymbols = {
  async_id_symbol: Symbol("asyncId"),
  trigger_async_id_symbol: Symbol("triggerAsyncId"),
  owner_symbol: Symbol("owner_symbol"),
  handle_onclose: Symbol("handle_onclose"),
  resource_symbol: Symbol("resource"),
};
const internalAsyncHooks = {
  newAsyncId,
  defaultTriggerAsyncIdScope: (asyncId, fn, ...args) => Reflect.apply(fn, null, args),
  getOrSetAsyncId(object) {
    if (Object.prototype.hasOwnProperty.call(object, asyncHookSymbols.async_id_symbol)) {
      return object[asyncHookSymbols.async_id_symbol];
    }
    return object[asyncHookSymbols.async_id_symbol] = newAsyncId();
  },
  symbols: asyncHookSymbols,
};

const TIMEOUT_MAX = 2 ** 31 - 1;
const internalTimers = {
  kTimeout: Symbol("timeout"),
  setUnrefTimeout(callback, after) {
    const timer = setTimeout(callback, after);
    if (timer && typeof timer.unref === "function") timer.unref();
    return timer;
  },
  getTimerDuration(msecs, name) {
    __validators.validateNumber(msecs, name);
    if (msecs < 0 || !Number.isFinite(msecs)) {
      throw new codes.ERR_OUT_OF_RANGE(name, "a non-negative finite number", msecs);
    }
    if (msecs > TIMEOUT_MAX) {
      process.emitWarning(`${msecs} does not fit into a 32-bit signed integer.` +
                          `\nTimer duration was truncated to ${TIMEOUT_MAX}.`, "TimeoutOverflowWarning");
      return TIMEOUT_MAX;
    }
    return msecs;
  },
};

function internalAssert(value, message) {
  if (!value) throw new codes.ERR_INTERNAL_ASSERTION(message);
}
internalAssert.fail = (message) => {
  throw new codes.ERR_INTERNAL_ASSERTION(message);
};

// Node's option defaults (lumen takes none of these from the command line).
const optionDefaults = {
  "--network-family-autoselection": true,
  "--network-family-autoselection-attempt-timeout": 250,
  "--insecure-http-parser": false,
  "--max-http-header-size": 16 * 1024,
  "--pending-deprecation": false,
};
function getOptionValue(name) {
  if (name === "--insecure-http-parser" || name === "--pending-deprecation") {
    const argv = process.execArgv || [];
    const env = process.env?.NODE_OPTIONS || "";
    if (argv.includes(name) || env.split(/\s+/).includes(name)) return true;
  }
  if (name === "--max-http-header-size") {
    for (const a of process.execArgv || []) {
      if (a.startsWith("--max-http-header-size=")) return Number(a.slice(23));
    }
  }
  return optionDefaults[name];
}

class JSTransferable {}
const kClone = Symbol("kClone");
const kDeserialize = Symbol("kDeserialize");

const shims = {
  __proto__: null,
  "internal/errors": internalErrors,
  "internal/util": internalUtil,
  "internal/async_hooks": internalAsyncHooks,
  "internal/timers": internalTimers,
  "internal/assert": internalAssert,
  "internal/options": { getOptionValue },
  "internal/perf/observe": { hasObserver: () => false, startPerf() {}, stopPerf() {} },
  "internal/process/task_queues": { queueMicrotask: globalThis.queueMicrotask },
  "internal/streams/state": {
    getDefaultHighWaterMark: (objectMode) => __builtins.get("stream").getDefaultHighWaterMark(objectMode),
  },
  "internal/util/debuglog": {
    debuglog: (set, cb) => __builtins.get("util").debuglog(set, cb),
  },
  // `new FastBuffer(arrayBuffer, offset, length)`: a Buffer view over those bytes (no copy).
  "internal/buffer": { FastBuffer: function FastBuffer(arrayBuffer, byteOffset, length) {
    return Buffer.from(arrayBuffer, byteOffset, length);
  } },
  "internal/worker/js_transferable": { JSTransferable, kClone, kDeserialize },
};
for (const id of Object.keys(shims)) moduleCache.set(id, { exports: shims[id] });

// ---- internalBinding('uv') --------------------------------------------------------------------

const uvBinding = { errname: getSystemErrorName, getErrorMap: () => __uvErrmap };
for (const [errno, [name]] of __uvErrmap) uvBinding[`UV_${name}`] = errno;
const UV_EOF = uvBinding.UV_EOF;
const UV_EBADF = uvBinding.UV_EBADF;
const UV_ENOTCONN = uvBinding.UV_ENOTCONN;
const UV_EINVAL = uvBinding.UV_EINVAL;
const UV_ENOTSUP = uvBinding.UV_ENOTSUP;

// A native op error (`{ code: 'ECONNREFUSED', ... }`) as the libuv errno the handles report.
function errnoOf(error) {
  const code = error && error.code;
  if (typeof code === "string") {
    const errno = __uvCodes.get(code);
    if (errno !== undefined) return errno;
    if (code === "ENOTFOUND") return __uvCodes.get("EAI_NONAME");
  }
  return uvBinding.UV_UNKNOWN;
}

// ---- internalBinding('stream_wrap') -----------------------------------------------------------

const kReadBytesOrError = 0;
const kArrayBufferOffset = 1;
const kBytesWritten = 2;
const kLastWriteWasAsync = 3;
const streamBaseState = new Int32Array(5);
class WriteWrap {}
class ShutdownWrap {}
class LibuvStreamWrap {}
const streamWrapBinding = {
  kReadBytesOrError, kArrayBufferOffset, kBytesWritten, kLastWriteWasAsync, streamBaseState,
  WriteWrap, ShutdownWrap, LibuvStreamWrap,
};

// ---- the stream handles (tcp_wrap / pipe_wrap) -------------------------------------------------

// Common to TCP and Pipe: the StreamBase read/write/shutdown surface and the server accept loop.
class StreamHandle {
  constructor(type) {
    this._type = type;
    this._id = null; // native socket id (net.rs NetRegistry)
    this._serverIds = null; // native listener ids while listening
    this._closed = false;
    this._resetting = false;
    this._reading = false;
    this._readInFlight = false;
    this._eof = false;
    this._held = []; // reads that completed while stopped: [chunk | null | error]
    this._refed = true;
    this._asyncId = newAsyncId();
    this._sockname = null;
    this._peername = null;
    this._writesInFlight = 0;
    this._writeQueue = [];
    this._writing = false;
    this._queuedBytes = 0;
    this._drainWaiters = [];
    this._userBuf = null;
    this.reading = false;
    this.bytesRead = 0;
    this.bytesWritten = 0;
    this.onread = null;
    this.onconnection = null;
  }

  getAsyncId() { return this._asyncId; }
  getProviderType() { return 0; }
  isStreamBase = false;
  get writeQueueSize() { return this._queuedBytes; }

  // Adopt a connected native stream: `[id, localAddress, localPort, remoteAddress, remotePort, family]`.
  _adopt(desc) {
    this._id = desc[0];
    if (desc[1] !== undefined) {
      this._sockname = { address: desc[1], family: desc[5], port: desc[2] };
      this._peername = { address: desc[3], family: desc[5], port: desc[4] };
    }
    if (!this._refed) __net.socketRef(this._id, true);
  }

  readStart() {
    if (this._closed) return UV_EBADF;
    if (this._id === null) return UV_ENOTCONN;
    this._reading = true;
    if (this._held.length !== 0) process.nextTick(() => this._drainHeld());
    else this._armRead();
    return 0;
  }

  readStop() {
    this._reading = false;
    return 0;
  }

  _drainHeld() {
    // An exception out of onread (a throwing 'data' or response handler) still leaves the
    // stream reading, as libuv keeps its read going whatever the JS callback did.
    try {
      while (this._reading && !this._closed && this._held.length !== 0) this._deliver(this._held.shift());
    } finally {
      this._armRead();
    }
  }

  _armRead() {
    if (!this._reading || this._readInFlight || this._closed || this._eof || this._id === null) return;
    if (this._held.length !== 0) return;
    this._readInFlight = true;
    __net.read(
      this._id,
      (chunk) => this._onRead(chunk),
      (error) => this._onRead(error instanceof Error ? error : Object.assign(new Error("read"), { code: "UNKNOWN" })),
    );
  }

  _onRead(result) {
    this._readInFlight = false;
    if (this._closed) return;
    this._held.push(result);
    if (this._reading) this._drainHeld();
  }

  // One read result into onread, the way LibuvStreamWrap::OnUvRead reports it.
  _deliver(result) {
    if (typeof this.onread !== "function") return;
    if (result === null) {
      this._eof = true;
      streamBaseState[kReadBytesOrError] = UV_EOF;
      streamBaseState[kArrayBufferOffset] = 0;
      this.onread(undefined);
    } else if (result instanceof Error) {
      this._eof = true;
      streamBaseState[kReadBytesOrError] = errnoOf(result);
      streamBaseState[kArrayBufferOffset] = 0;
      this.onread(undefined);
    } else if (this._userBuf !== null) {
      // Node's onread with a user buffer: the bytes land in that buffer, and whatever does not
      // fit is delivered by the next call.
      const target = this._userBuf;
      const n = Math.min(result.length, target.length);
      target.set(result.subarray(0, n));
      if (n < result.length) this._held.unshift(result.subarray(n));
      this.bytesRead += n;
      streamBaseState[kReadBytesOrError] = n;
      streamBaseState[kArrayBufferOffset] = 0;
      const next = this.onread(undefined);
      if (next instanceof Uint8Array) this._userBuf = next;
    } else {
      this.bytesRead += result.length;
      streamBaseState[kReadBytesOrError] = result.length;
      streamBaseState[kArrayBufferOffset] = result.byteOffset;
      this.onread(result.buffer);
    }
  }

  useUserBuffer(buf) {
    this._userBuf = buf;
  }

  // Writes go out one at a time, in order (the native write runs on a worker thread).
  writeBuffer(req, data) {
    if (this._closed || this._id === null) return UV_EBADF;
    let bytes = data instanceof Uint8Array ? data : new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
    streamBaseState[kBytesWritten] = bytes.length;
    // LibuvStreamWrap::DoTryWrite: with nothing queued, whatever the kernel takes right now is
    // written synchronously (the write then completes without a callback, req.async false).
    if (!this._writing && this._writeQueue.length === 0 && bytes.length !== 0) {
      const n = __net.tryWrite(this._id, bytes);
      if (n === bytes.length) {
        this.bytesWritten += n;
        streamBaseState[kLastWriteWasAsync] = 0;
        return 0;
      }
      if (n > 0) {
        this.bytesWritten += n;
        bytes = bytes.subarray(n);
      }
    }
    streamBaseState[kLastWriteWasAsync] = 1;
    this._writeQueue.push({ req, bytes });
    this._writesInFlight++;
    // libuv counts a write as written once it is dispatched; writeQueueSize is what is still queued.
    this.bytesWritten += bytes.length;
    this._queuedBytes += bytes.length;
    if (!this._writing) this._writeNext();
    return 0;
  }
  _writeNext() {
    const entry = this._writeQueue[0];
    this._writing = entry !== undefined;
    if (entry === undefined) {
      const waiters = this._drainWaiters;
      this._drainWaiters = [];
      for (const fn of waiters) fn();
      return;
    }
    const done = (status) => {
      this._writeQueue.shift();
      this._writesInFlight--;
      this._writing = false;
      this._queuedBytes -= entry.bytes.length;
      if (typeof entry.req.oncomplete === "function") entry.req.oncomplete(status);
      if (!this._writing) this._writeNext();
    };
    if (this._id === null) {
      process.nextTick(done, UV_EBADF);
      return;
    }
    __net.write(this._id, entry.bytes, () => done(0), (error) => done(errnoOf(error)));
  }
  _whenDrained(fn) {
    if (this._writeQueue.length === 0) fn();
    else this._drainWaiters.push(fn);
  }
  writeUtf8String(req, s) { return this.writeBuffer(req, Buffer.from(s, "utf8")); }
  writeLatin1String(req, s) { return this.writeBuffer(req, Buffer.from(s, "latin1")); }
  writeAsciiString(req, s) { return this.writeBuffer(req, Buffer.from(s, "latin1")); }
  writeUcs2String(req, s) { return this.writeBuffer(req, Buffer.from(s, "utf16le")); }
  writev(req, chunks, allBuffers) {
    const parts = [];
    if (allBuffers) {
      for (let i = 0; i < chunks.length; i++) parts.push(chunks[i]);
    } else {
      for (let i = 0; i < chunks.length; i += 2) {
        const chunk = chunks[i];
        parts.push(typeof chunk === "string" ? Buffer.from(chunk, chunks[i + 1]) : chunk);
      }
    }
    return this.writeBuffer(req, Buffer.concat(parts));
  }

  shutdown(req) {
    if (this._closed || this._id === null) return UV_ENOTCONN;
    this._whenDrained(() => {
      if (!this._closed && this._id !== null) __net.endWritable(this._id);
      process.nextTick(() => {
        if (typeof req.oncomplete === "function") req.oncomplete(0);
      });
    });
    return 0;
  }

  close(callback) {
    if (this._closed) return;
    this._closed = true;
    this._reading = false;
    this.reading = false;
    if (this._id !== null) {
      if (this._writeQueue.length !== 0 && !this._resetting) {
        // libuv writes what it can synchronously (uv_try_write) before a close, so a response
        // written just before destroy() still reaches the peer: let queued writes finish first.
        this._whenDrained(() => {
          if (this._id !== null) __net.close(this._id);
          this._id = null;
        });
      } else {
        __net.close(this._id);
        this._id = null;
      }
    }
    if (this._serverIds !== null) {
      for (const id of this._serverIds) __net.closeServer(id);
      this._serverIds = null;
    }
    if (typeof callback === "function") setImmediate(() => callback.call(this));
  }

  reset(callback) {
    this._resetting = true;
    this.close(callback);
    return 0;
  }

  ref() {
    this._refed = true;
    if (this._id !== null) __net.socketRef(this._id, false);
    if (this._serverIds !== null) for (const id of this._serverIds) __net.serverRef(id, false);
  }
  unref() {
    this._refed = false;
    if (this._id !== null) __net.socketRef(this._id, true);
    if (this._serverIds !== null) for (const id of this._serverIds) __net.serverRef(id, true);
  }
  hasRef() { return this._refed && !this._closed; }

  setBlocking() { return 0; }
  fchmod() { return 0; }
  open(_fd) { return UV_ENOTSUP; }

  _connectWith(req, start) {
    start(
      (...desc) => {
        if (this._closed) {
          __net.close(desc[0]);
          return;
        }
        this._adopt(desc);
        req.oncomplete(0, this, req, true, true);
      },
      (error) => {
        if (this._closed) return;
        req.oncomplete(errnoOf(error), this, req, false, false);
      },
    );
    return 0;
  }

  // The accept loop: one blocking accept per listener, each connection handed to onconnection.
  _acceptLoop(serverId) {
    if (this._closed || this._serverIds === null) return;
    __net.accept(
      serverId,
      (...desc) => {
        if (desc.length < 2) return; // listener closed
        if (this._closed) {
          __net.close(desc[0]);
          return;
        }
        const handle = new this.constructor(this.constructor === TCP ? TCPConstants.SOCKET : PipeConstants.SOCKET);
        handle._adopt(desc);
        this.onconnection(0, handle);
        this._acceptLoop(serverId);
      },
      (error) => {
        if (this._closed) return;
        this.onconnection(errnoOf(error));
        this._acceptLoop(serverId);
      },
    );
  }
}

const TCPConstants = { SOCKET: 0, SERVER: 1, UV_TCP_IPV6ONLY: 1 };
class TCP extends StreamHandle {
  constructor(type) {
    super(type);
    this._bindAddress = null;
    this._bindPort = 0;
    this._bindFlags = 0;
  }
  getsockname(out) {
    let name = this._sockname;
    if (this._serverIds !== null && name === null) name = __net.serverAddress(this._serverIds[0]);
    if (!name) {
      if (this._bindAddress === null) return UV_EINVAL;
      name = { address: this._bindAddress, family: this._bindAddress.includes(":") ? "IPv6" : "IPv4", port: this._bindPort };
    }
    out.address = name.address;
    out.family = name.family;
    out.port = name.port;
    return 0;
  }
  getpeername(out) {
    if (this._peername === null) return UV_ENOTCONN;
    out.address = this._peername.address;
    out.family = this._peername.family;
    out.port = this._peername.port;
    return 0;
  }
  setNoDelay(enable) {
    if (this._id !== null) __net.setNoDelay(this._id, !!enable);
    return 0;
  }
  setKeepAlive(enable, initialDelaySecs) {
    if (this._id !== null) __net.setKeepAlive(this._id, !!enable, (Number(initialDelaySecs) || 0) * 1000);
    return 0;
  }
  setSimultaneousAccepts() {}
  bind(address, port) {
    this._bindAddress = address;
    this._bindPort = port | 0;
    this._bindFlags = 0;
    return 0;
  }
  bind6(address, port, flags) {
    this._bindAddress = address;
    this._bindPort = port | 0;
    this._bindFlags = flags | 0;
    return 0;
  }
  // The listener binds here (std binds and listens in one step, so EADDRINUSE surfaces from
  // listen, as it does for libuv on Linux). An unspecified IPv6 address is dual-stack in Node;
  // where the OS keeps "::" IPv6-only (Windows), a second IPv4 listener on the same port covers
  // IPv4 clients.
  listen(backlog) {
    if (this._closed) return UV_EBADF;
    const address = this._bindAddress ?? "0.0.0.0";
    let info;
    try {
      info = __net.listen(address, this._bindPort, backlog | 0);
    } catch (error) {
      return errnoOf(error);
    }
    this._serverIds = [info.serverId];
    this._sockname = { address: info.address, family: info.family, port: info.port };
    if (address === "::" && !(this._bindFlags & TCPConstants.UV_TCP_IPV6ONLY)) {
      try {
        const v4 = __net.listen("0.0.0.0", info.port, backlog | 0);
        this._serverIds.push(v4.serverId);
      } catch {
        // Already dual-stack (the OS maps IPv4 onto "::"), or the IPv4 port is taken.
      }
    }
    if (!this._refed) for (const id of this._serverIds) __net.serverRef(id, true);
    for (const id of this._serverIds) this._acceptLoop(id);
    return 0;
  }
  connect(req, address, port) {
    return this._connectWith(req, (ok, fail) => __net.connect(address, port, ok, fail));
  }
  connect6(req, address, port) {
    return this.connect(req, address, port);
  }
}

const PipeConstants = { SOCKET: 0, SERVER: 1, IPC: 2, UV_READABLE: 1, UV_WRITABLE: 2 };
class Pipe extends StreamHandle {
  constructor(type) {
    super(type);
    this._path = null;
  }
  bind(path) {
    this._path = path;
    return 0;
  }
  listen(_backlog) {
    if (this._closed) return UV_EBADF;
    let info;
    try {
      info = __net.listenPath(this._path);
    } catch (error) {
      return error && error.code ? errnoOf(error) : UV_ENOTSUP;
    }
    this._serverIds = [info.serverId];
    if (!this._refed) __net.serverRef(info.serverId, true);
    this._acceptLoop(info.serverId);
    return 0;
  }
  connect(req, path) {
    return this._connectWith(req, (ok, fail) => {
      try {
        __net.connectPath(path, ok, fail);
      } catch (error) {
        fail(Object.assign(error, { code: error.code || "ENOTSUP" }));
      }
    });
  }
  setPendingInstances() {}
  getsockname(out) {
    if (this._path === null) return UV_EINVAL;
    out.address = this._path;
    return 0;
  }
}

class TCPConnectWrap {}
class PipeConnectWrap {}

// ---- internalBinding('block_list') -------------------------------------------------------------

const AF_INET = 2;
const AF_INET6 = isWindows ? 23 : process.platform === "darwin" ? 30 : 10;

function parseIPv4(s) {
  const parts = s.split(".");
  if (parts.length !== 4) return null;
  let n = 0n;
  for (const p of parts) {
    if (!/^\d{1,3}$/.test(p)) return null;
    const v = Number(p);
    if (v > 255) return null;
    n = (n << 8n) | BigInt(v);
  }
  return n;
}
function parseIPv6(s) {
  const pct = s.indexOf("%");
  if (pct >= 0) s = s.slice(0, pct);
  let tail4 = null;
  const lastColon = s.lastIndexOf(":");
  if (s.includes(".", lastColon)) {
    tail4 = parseIPv4(s.slice(lastColon + 1));
    if (tail4 === null) return null;
    s = s.slice(0, lastColon + 1) + "0:0";
  }
  const halves = s.split("::");
  if (halves.length > 2) return null;
  const head = halves[0] ? halves[0].split(":") : [];
  const tail = halves.length === 2 && halves[1] ? halves[1].split(":") : [];
  const missing = 8 - head.length - tail.length;
  if (halves.length === 2 ? missing < 1 : missing !== 0) return null;
  const groups = [...head, ...Array(halves.length === 2 ? missing : 0).fill("0"), ...tail];
  let n = 0n;
  for (const g of groups) {
    if (!/^[0-9a-fA-F]{1,4}$/.test(g)) return null;
    n = (n << 16n) | BigInt(parseInt(g, 16));
  }
  if (tail4 !== null) n = (n & ~0xffffffffn) | tail4;
  return n;
}
function formatIPv6(n) {
  const groups = [];
  for (let i = 7; i >= 0; i--) groups.push(Number((n >> BigInt(i * 16)) & 0xffffn));
  let bestStart = -1, bestLen = 0;
  for (let i = 0; i < 8;) {
    if (groups[i] !== 0) { i++; continue; }
    let j = i;
    while (j < 8 && groups[j] === 0) j++;
    if (j - i > bestLen && j - i > 1) { bestStart = i; bestLen = j - i; }
    i = j;
  }
  const hex = groups.map((g) => g.toString(16));
  if (bestStart < 0) return hex.join(":");
  return `${hex.slice(0, bestStart).join(":")}::${hex.slice(bestStart + bestLen).join(":")}`;
}
const v4MappedPrefix = 0xffffn << 32n;

class SocketAddressHandle {
  constructor(address, port, type, flowlabel) {
    const value = type === AF_INET ? parseIPv4(address) : parseIPv6(address);
    // An unparsable address yields a handle whose detail() is undefined (SocketAddress throws).
    this._valid = value !== null;
    this._family = type;
    this._value = value;
    this._address = value === null ? "" : type === AF_INET ? address : formatIPv6(value);
    this._port = port | 0;
    this._flowlabel = flowlabel >>> 0;
  }
  detail(out) {
    if (!this._valid) return undefined;
    out.address = this._address;
    out.port = this._port;
    out.family = this._family;
    out.flowlabel = this._flowlabel;
    return out;
  }
  flowlabel() { return this._flowlabel; }
  // The address as a 128-bit value (IPv4 mapped into ::ffff:0:0/96) for cross-family checks.
  _as6() { return this._family === AF_INET ? v4MappedPrefix | this._value : this._value; }
}

class BlockListHandle {
  constructor() { this._rules = []; }
  addAddress(address) {
    this._rules.push({ kind: "address", family: address._family, value: address._value, text: address._address });
  }
  addRange(start, end) {
    if (start._family !== end._family) return false;
    if (end._value < start._value) return false;
    this._rules.push({ kind: "range", family: start._family, start: start._value, end: end._value,
                       text: `${start._address}-${end._address}` });
    return true;
  }
  addSubnet(network, prefix) {
    const bits = network._family === AF_INET ? 32 : 128;
    const full = (1n << BigInt(bits)) - 1n;
    const mask = prefix === 0 ? 0n : (full << BigInt(bits - prefix)) & full;
    this._rules.push({ kind: "subnet", family: network._family, base: network._value & mask, mask, bits,
                       text: `${network._address}/${prefix}` });
  }
  check(address) {
    for (const rule of this._rules) {
      let value = address._value;
      if (rule.family !== address._family) {
        // IPv4 and IPv4-mapped IPv6 addresses match across families.
        if (address._family === AF_INET6 && (value >> 32n) === 0xffffn) value &= 0xffffffffn;
        else if (address._family === AF_INET) value = v4MappedPrefix | value;
        else continue;
        if (rule.family === AF_INET && value > 0xffffffffn) continue;
      }
      if (rule.kind === "address" && value === rule.value) return true;
      if (rule.kind === "range" && value >= rule.start && value <= rule.end) return true;
      if (rule.kind === "subnet" && (value & rule.mask) === rule.base) return true;
    }
    return false;
  }
  getRules() {
    const label = (family) => (family === AF_INET ? "IPv4" : "IPv6");
    const kind = { address: "Address", range: "Range", subnet: "Subnet" };
    return this._rules.map((r) => `${kind[r.kind]}: ${label(r.family)} ${r.text}`).reverse();
  }
}

const blockListBinding = { SocketAddress: SocketAddressHandle, BlockList: BlockListHandle, AF_INET, AF_INET6 };

// ---- internalBinding() --------------------------------------------------------------------------

const bindings = {
  __proto__: null,
  uv: uvBinding,
  stream_wrap: streamWrapBinding,
  tcp_wrap: { TCP, TCPConnectWrap, constants: TCPConstants },
  pipe_wrap: { Pipe, PipeConnectWrap, constants: PipeConstants },
  block_list: blockListBinding,
  symbols: { owner_symbol: asyncHookSymbols.owner_symbol, async_id_symbol: asyncHookSymbols.async_id_symbol },
  // Only the fd-socket sync write path (makeSyncWrite) reaches this; lumen wraps no raw fds.
  fs: { writeBuffer() { throw new Error("lumen net: synchronous fd writes are not supported"); } },
  constants: { get os() { return __builtins.get("os").constants; } },
  trace_events: { trace() {}, isTraceCategoryEnabled: () => false, getCategoryEnabledBuffer: () => new Uint8Array(1) },
  // http_parser is defined further down (after the llhttp port).
};
function internalBinding(name) {
  const binding = bindings[name];
  if (binding === undefined) throw new Error(`lumen net: internalBinding('${name}') is not available`);
  return binding;
}

