// Node's test runner: node:test, node:test/reporters and the `--test` command-line mode.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/testrunnergen/gen.js (see tools/README.md).
//
// Node 20.11's lib/internal/test_runner sources, plus the internal modules they need that no
// other glue file carries (internal/error_serdes, internal/watch_mode/files_watcher), run
// verbatim apart from `lumen:` edits in the module table below. The other internal modules come
// from internals.js (internal/errors, internal/util, internal/validators, ...) or from the small
// adapters over lumen's public modules defined here.

const primordials = __primordials;

const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}

function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {}, id };
    moduleCache.set(id, module);
    try {
      fn(module, module.exports, require, internalBinding, primordials);
    } catch (error) {
      moduleCache.delete(id);
      throw error;
    }
    return module.exports;
  }
  if (id.startsWith("internal/")) return __internals.get("exposedInternals").require(id);
  const builtin = __builtins.get(id);
  if (builtin === undefined) throw new Error(`lumen: module '${id}' is not available`);
  return builtin;
}

// ---- internalBinding() ------------------------------------------------------------------------

// Node's GetCallerLocation: [line, column, file] of the code that called the function calling
// this one.
function getCallerLocation() {
  const holder = {};
  const { stackTraceLimit, prepareStackTrace } = Error;
  Error.stackTraceLimit = 2;
  Error.prepareStackTrace = undefined;
  try {
    Error.captureStackTrace(holder, getCallerLocation);
  } finally {
    Error.stackTraceLimit = stackTraceLimit;
    Error.prepareStackTrace = prepareStackTrace;
  }
  const frames = `${holder.stack}`.split("\n").filter((line) => /^\s+at /.test(line));
  const match = frames[1] && /\(?([^()]*?):(\d+):(\d+)\)?$/.exec(frames[1].replace(/^\s+at\s+(?:async\s+)?/, ""));
  if (!match) return undefined;
  return [Number(match[2]), Number(match[3]), match[1]];
}

const bindingMakers = {
  __proto__: null,
  util: () => ({ __proto__: null, getCallerLocation }),
  errors: () => ({
    __proto__: null,
    exitCodes: { __proto__: null, kNoFailure: 0, kGenericUserError: 1 },
    triggerUncaughtException(error) {
      process.nextTick(() => {
        throw error;
      });
    },
  }),
};
const bindingCache = new Map();
function internalBinding(name) {
  let binding = bindingCache.get(name);
  if (binding === undefined) {
    const make = bindingMakers[name];
    binding = make !== undefined ? make() : __internals.get("internalBinding")(name);
    bindingCache.set(name, binding);
  }
  return binding;
}

// ---- adapters ---------------------------------------------------------------------------------

defineModule("internal/options", function (module) {
  const base = __internals.get("exposedInternals").require("internal/options");
  const defaults = {
    __proto__: null,
    "--test": false,
    "--test-only": false,
    "--experimental-test-coverage": false,
    "--watch": false,
    "--test-concurrency": 0,
    "--test-timeout": 0,
    "--test-shard": "",
    "--test-name-pattern": [],
    "--test-reporter": [],
    "--test-reporter-destination": [],
  };
  const numbers = ["--test-concurrency", "--test-timeout"];
  function getOptionValue(name) {
    if (!(name in defaults)) return base.getOptionValue(name);
    const parsed = process[Symbol.for("lumen.options")] || {};
    if (!Object.hasOwn(parsed, name)) {
      const value = defaults[name];
      return Array.isArray(value) ? [] : value;
    }
    const value = parsed[name];
    if (Array.isArray(defaults[name])) return Array.isArray(value) ? [...value] : [value];
    if (numbers.includes(name)) return Number(value);
    return value;
  }
  module.exports = { ...base, getOptionValue };
});

defineModule("internal/timers", function (module) {
  module.exports = { TIMEOUT_MAX: 2 ** 31 - 1 };
});

defineModule("internal/streams/readable", function (module) {
  module.exports = __builtins.get("stream").Readable;
});

defineModule("internal/streams/transform", function (module) {
  module.exports = __builtins.get("stream").Transform;
});

defineModule("internal/streams/end-of-stream", function (module) {
  const stream = __builtins.get("stream");
  function eos(...args) {
    return stream.finished(...args);
  }
  eos.finished = __builtins.get("stream/promises").finished;
  module.exports = eos;
});

defineModule("internal/console/global", function (module) {
  module.exports = __builtins.get("console");
});

defineModule("internal/abort_controller", function (module) {
  module.exports = { AbortController, AbortSignal };
});

defineModule("internal/event_target", function (module) {
  module.exports = { kResistStopPropagation: Symbol("kResistStopPropagation") };
});

defineModule("internal/url", function (module) {
  const url = __builtins.get("url");
  module.exports = { URL: url.URL, pathToFileURL: url.pathToFileURL, fileURLToPath: url.fileURLToPath };
});

defineModule("internal/util/debuglog", function (module) {
  module.exports = { debuglog: __builtins.get("util").debuglog };
});

// lumen has no inspector: no test process is ever started with one.
defineModule("internal/util/inspector", function (module) {
  const kInspectMsgRegex = /^Debugger listening on ws:\/\/\[?(.+?)\]?:(\d+)\/|^For help, see: https:\/\/nodejs\.org\/en\/docs\/inspector|^Debugger attached|^Waiting for the debugger to disconnect\.\.\./;
  module.exports = {
    getInspectPort: (inspectPort) => inspectPort ?? process.debugPort,
    isUsingInspector: () => false,
    isInspectorMessage: (string) => kInspectMsgRegex.test(string),
  };
});

defineModule("internal/process/pre_execution", function (module) {
  module.exports = { prepareMainThreadExecution() {}, markBootstrapComplete() {} };
});

defineModule("internal/process/esm_loader", function (module) {
  const url = __builtins.get("url");
  async function importFrom(specifier, parentURL) {
    let target = specifier;
    if (/^\.{0,2}\//.test(specifier)) {
      target = new url.URL(specifier, parentURL).href;
    } else if (!/^[a-z][a-z0-9+.-]*:/i.test(specifier)) {
      const resolved = __builtins.get("module").createRequire(url.fileURLToPath(parentURL)).resolve(specifier);
      target = url.pathToFileURL(resolved).href;
    }
    return import(target);
  }
  module.exports = { esmLoader: { import: importFrom } };
});

