[package]
name = "lumen-html-text"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
lumen-html = { path = "../lumen-html" }
lumen-common = { path = "../lumen-common" }
fontdue = "0.9"
rustybuzz = { version = "0.20", default-features = false }
ttf-parser = { version = "0.25", default-features = false, features = ["opentype-layout", "no-std-float"] }

[lints]
workspace = true
