// node:tls, node:_tls_wrap, node:_tls_common and node:https — Node 20.11's lib/tls.js,
// lib/_tls_wrap.js, lib/_tls_common.js and the internal modules they use, run as-is over a JS
// TLSWrap and a native OpenSSL engine (`__tls` ops, crates/lumen-tls).
//
// DO NOT EDIT: generated by crates/lumen-node/tools/tlsgen/gen.js (see tools/README.md).
//
// Generated: the Node sources below are verbatim, each wrapped as a CommonJS-style module; the
// few edits are marked `lumen:`. The module table and the stream bindings are shared with
// net.js (the netgen output), so a TLS socket wraps the same handles node:net creates:
//   - tls_wrap: TLSWrap, a stream handle that encrypts writes and decrypts what its parent
//     handle (TCP, Pipe or JSStream) reads, moving bytes through the engine's memory buffers.
//   - crypto: SecureContext over the native SSL_CTX registry, plus the cipher and root lists.
//   - js_stream: a handle whose I/O is JS callbacks, for TLS over arbitrary duplex streams.

const primordials = __primordials;
const netRequire = __internals.get("netRequire");
const netBinding = __internals.get("netBinding");
const tlsOps = __tls;
const { Buffer } = __builtins.get("buffer");
const codes = __errors;

// ---- the module table -------------------------------------------------------------------------
// Modules defined here are evaluated on first `require`; everything else (net, http, events,
// the internal helpers) comes from net.js's table.
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}
function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {} };
    moduleCache.set(id, module);
    fn(module, module.exports, require, internalBinding, primordials);
    return module.exports;
  }
  const value = id === "crypto" || id === "fs" ? __builtins.get(id) : netRequire(id);
  moduleCache.set(id, { exports: value });
  return value;
}

// ---- errors, options and small internal helpers -------------------------------------------------

{
  const format = (...args) => __builtins.get("util").format(...args);
  const define = (key, message, Base) => {
    codes[key] = {
      [key]: function (...args) {
        const props = {};
        const text = typeof message === "function" ? Reflect.apply(message, props, args)
          : args.length ? format(message, ...args) : message;
        const err = __nodeError(Base, key, text);
        for (const name of Object.keys(props)) err[name] = props[name];
        return err;
      },
    }[key];
  };
  define("ERR_TLS_CERT_ALTNAME_INVALID", function (reason, host, cert) {
    this.reason = reason;
    this.host = host;
    this.cert = cert;
    return `Hostname/IP does not match certificate's altnames: ${reason}`;
  }, Error);
  define("ERR_TLS_CERT_ALTNAME_FORMAT", "Invalid subject alternative name string", SyntaxError);
  define("ERR_TLS_ALPN_CALLBACK_INVALID_RESULT",
    (value, protocols) => `ALPN callback returned a value (${value}) that doesn't match any of the client's ALPNProtocols (${protocols.join(", ")}).`, Error);
  define("ERR_TLS_ALPN_CALLBACK_WITH_PROTOCOLS", "The ALPNCallback and ALPNProtocols TLS options are mutually exclusive", TypeError);
  define("ERR_TLS_DH_PARAM_SIZE", "DH parameter size %s is less than 2048", Error);
  define("ERR_TLS_HANDSHAKE_TIMEOUT", "TLS handshake timeout", Error);
  define("ERR_TLS_INVALID_CONTEXT", "%s must be a SecureContext", TypeError);
  define("ERR_TLS_INVALID_PROTOCOL_VERSION", "%j is not a valid %s TLS protocol version", TypeError);
  define("ERR_TLS_INVALID_STATE", "TLS socket connection must be securely established", Error);
  define("ERR_TLS_PROTOCOL_VERSION_CONFLICT", "TLS protocol version %j conflicts with secureProtocol %j", TypeError);
  define("ERR_TLS_PSK_SET_IDENTIY_HINT_FAILED", "Failed to set PSK identity hint", Error);
  define("ERR_TLS_RENEGOTIATION_DISABLED", "TLS session renegotiation disabled for this socket", Error);
  define("ERR_TLS_REQUIRED_SERVER_NAME", '"servername" is required parameter for Server.addContext', Error);
  define("ERR_TLS_SESSION_ATTACK", "TLS session renegotiation attack detected", Error);
  define("ERR_TLS_SNI_FROM_SERVER", "Cannot issue SNI from a TLS server-side socket", Error);
  define("ERR_STREAM_WRAP", "Stream has StringDecoder set or is in objectMode", Error);
  define("ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED", "Custom engine not supported by this OpenSSL", Error);
}

const DEFAULT_CIPHER_LIST = "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:" +
  "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:" +
  "ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:" +
  "DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:" +
  "DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA";

const netGetOptionValue = netRequire("internal/options").getOptionValue;
const tlsOptionDefaults = {
  "--tls-cipher-list": DEFAULT_CIPHER_LIST,
  "--tls-min-v1.0": false,
  "--tls-min-v1.1": false,
  "--tls-min-v1.2": false,
  "--tls-min-v1.3": false,
  "--tls-max-v1.2": false,
  "--tls-max-v1.3": false,
  "--tls-keylog": "",
  "--trace-tls": false,
};
function getOptionValue(name) {
  const value = netGetOptionValue(name);
  return value !== undefined ? value : tlsOptionDefaults[name];
}
let warnOnAllowUnauthorized = true;
function getAllowUnauthorized() {
  const allowUnauthorized = process.env.NODE_TLS_REJECT_UNAUTHORIZED === "0";
  if (allowUnauthorized && warnOnAllowUnauthorized) {
    warnOnAllowUnauthorized = false;
    process.emitWarning("Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS " +
      "connections and HTTPS requests insecure by disabling certificate verification.");
  }
  return allowUnauthorized;
}

function cachedResult(fn) {
  let result;
  return () => {
    if (result === undefined) result = fn();
    return result.slice();
  };
}
function filterDuplicateStrings(items, low) {
  const map = new Map();
  for (const item of items) {
    const key = item.toLowerCase();
    map.set(key, low ? key : item);
  }
  return Array.from(map.values()).sort();
}

{
  const internalUtil = Object.setPrototypeOf({ cachedResult, filterDuplicateStrings }, netRequire("internal/util"));
  const toBuf = (value, encoding) => {
    if (typeof value === "string") return Buffer.from(value, encoding === "buffer" ? "utf8" : encoding);
    return value;
  };
  class InternalX509Certificate {
    constructor(der) {
      return new (__builtins.get("crypto").X509Certificate)(der);
    }
  }
  const shims = {
    "internal/util": internalUtil,
    "internal/options": { getOptionValue, getAllowUnauthorized },
    "internal/crypto/util": { toBuf },
    "internal/crypto/x509": { InternalX509Certificate },
  };
  for (const id of Object.keys(shims)) moduleCache.set(id, { exports: shims[id] });
}

// ---- stream bindings shared with net.js --------------------------------------------------------

const { streamBaseState, kReadBytesOrError, kArrayBufferOffset, kBytesWritten, kLastWriteWasAsync, WriteWrap } =
  netBinding("stream_wrap");
const uvBinding = netBinding("uv");
const UV_EOF = uvBinding.UV_EOF;
const UV_EPROTO = uvBinding.UV_EPROTO;
const UV_ECANCELED = uvBinding.UV_ECANCELED;
const newAsyncId = netRequire("internal/async_hooks").newAsyncId;

