// node:url and node:querystring — Node 20.11's lib/url.js, lib/querystring.js,
// lib/internal/querystring.js and the helper half of lib/internal/url.js, run as-is.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/urlgen/gen.js (see tools/README.md).
//
// Generated: the Node sources below are verbatim, each wrapped as a CommonJS-style module; edits
// are marked `lumen:`. The WHATWG `URL`/`URLSearchParams` classes are the globals lumen-web
// installs (its js/url.js is a port of Node's classes over the ada-derived parser in url.rs);
// `internalBinding('url')` hands out that parser's extra entry points (format, domainTo*), which
// lumen-web's URL keeps under a private symbol.

const primordials = __primordials;

// ---- the module table -------------------------------------------------------------------------
// `defineModule(id, fn)` registers a module body, which is evaluated on its first `require`.
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}
function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {} };
    moduleCache.set(id, module);
    fn(module, module.exports, require, internalBinding, primordials);
    return module.exports;
  }
  const value = builtinModule(id);
  moduleCache.set(id, { exports: value });
  return value;
}

const webUrl = globalThis.URL[Symbol.for("lumen.url.internals")];

function spliceOne(list, index) {
  for (; index + 1 < list.length; index++) list[index] = list[index + 1];
  list.pop();
}

function builtinModule(id) {
  switch (id) {
    case "buffer":
    case "path":
      return __builtins.get(id);
    case "internal/errors":
      return { codes: __errors };
    case "internal/validators":
      return __validators;
    case "internal/util":
      return { spliceOne, toUSVString: webUrl.toUSVString };
    case "internal/options":
      // `--pending-deprecation` is the only option lib/url.js reads.
      return {
        getOptionValue: (name) =>
          name === "--pending-deprecation" &&
          (process.execArgv.includes(name) || /(^|\s)--pending-deprecation(\s|$)/.test(process.env.NODE_OPTIONS || "")),
      };
    case "internal/idna":
      return { toASCII: webUrl.idnaToASCII, toUnicode: webUrl.idnaToUnicode };
  }
  throw new Error(`lumen url: internal module '${id}' is not available`);
}

function internalBinding(name) {
  if (name === "url") {
    return {
      URL: globalThis.URL,
      URLSearchParams: globalThis.URLSearchParams,
      updateActions: webUrl.updateActions,
      domainToASCII: webUrl.domainToASCII,
      domainToUnicode: webUrl.domainToUnicode,
      format: webUrl.format,
    };
  }
  throw new Error(`lumen url: internalBinding('${name}') is not available`);
}

