import math, itertools
from collections import deque

def t(f):
    try:
        f()
    except Exception as e:
        print(type(e).__name__ + ":", e)

t(lambda: math.floor())
t(lambda: math.floor(1, 2))
t(lambda: math.floor(x=1))
t(lambda: math.floor('a'))
t(lambda: math.sqrt('a'))
t(lambda: math.pow(1))
t(lambda: math.pow(1, 2, 3))
t(lambda: math.pow(x=1, y=2))
t(lambda: math.log())
t(lambda: math.log(1, 2, 3))
t(lambda: math.isclose(1))
t(lambda: math.isclose(1, 2, 3))
t(lambda: math.isclose(1, 2, foo=3))
t(lambda: math.isclose(1, 2, rel_tol='x'))
t(lambda: math.isclose(1, b=2, a=3))
t(lambda: math.isclose(a=1))
t(lambda: math.prod())
t(lambda: math.prod([1], 2))
t(lambda: math.prod([1], start=2, x=1))
t(lambda: math.factorial(1.5))
t(lambda: math.factorial('a'))
t(lambda: math.factorial(10**30))
t(lambda: math.comb(1))
t(lambda: math.comb(1, 2, 3))
t(lambda: math.perm())
t(lambda: math.gcd(1.5))
t(lambda: math.ldexp(1.0, 'a'))
t(lambda: math.ldexp(1.0, 10**30))
t(lambda: math.hypot('a'))
t(lambda: math.fsum(1))
t(lambda: math.dist([1], 2))
t(lambda: math.trunc('a'))
t(lambda: math.ceil(None))
t(lambda: math.isqrt(-1))
t(lambda: math.isqrt(1.5))
t(lambda: math.log(-1))
t(lambda: math.log(0))
t(lambda: math.exp(1000))
t(lambda: deque().append())
t(lambda: deque().append(1, 2))
t(lambda: deque().append(x=1))
t(lambda: deque().pop(1))
t(lambda: deque().pop())
t(lambda: deque().rotate('a'))
t(lambda: deque().rotate(1, 2))
t(lambda: deque().index())
t(lambda: deque().insert(1))
t(lambda: deque(1, 2, 3))
t(lambda: deque([], maxlen='a'))
t(lambda: deque([], -1))
t(lambda: deque([], foo=1))
t(lambda: deque.append(1, 2))
t(lambda: deque()[1])
t(lambda: deque()['a'])
t(lambda: deque().__len__(1))
t(lambda: deque().maxlen.__class__)
t(lambda: setattr(deque(), 'maxlen', 3))
t(lambda: itertools.count('a'))
t(lambda: itertools.count(1, 2, 3))
t(lambda: itertools.count(foo=1))
t(lambda: itertools.repeat())
t(lambda: itertools.repeat(1, 'a'))
t(lambda: itertools.cycle())
t(lambda: itertools.cycle(1))
t(lambda: itertools.cycle([], x=1))
t(lambda: itertools.chain(x=1))
t(lambda: itertools.islice([]))
t(lambda: itertools.islice([], 1, 2, 3, 4))
t(lambda: itertools.islice([], 'a'))
t(lambda: itertools.accumulate())
t(lambda: itertools.accumulate([], foo=1))
t(lambda: itertools.compress([]))
t(lambda: itertools.dropwhile(1))
t(lambda: itertools.starmap(1))
t(lambda: itertools.pairwise())
t(lambda: itertools.batched([], 0))
t(lambda: itertools.batched([]))
t(lambda: itertools.tee([], -1))
t(lambda: itertools.tee())
t(lambda: itertools.product([], foo=1))
t(lambda: itertools.permutations())
t(lambda: itertools.combinations([]))
t(lambda: itertools.combinations([], -1))
t(lambda: itertools.combinations_with_replacement([], 'a'))
t(lambda: itertools.groupby())
t(lambda: itertools.zip_longest(foo=1))
t(lambda: itertools.chain.from_iterable())
t(lambda: next(itertools.chain.from_iterable([1])))
t(lambda: math.isclose(1, a=1))
t(lambda: math.isclose(1, 2, 3, 4, 5))
t(lambda: math.nextafter(1.0, 2.0, steps=-1))
t(lambda: math.sumprod([1, 2], [3]))
t(lambda: deque().__getitem__())
t(lambda: deque().__setitem__(0, 1, x=2))
t(lambda: deque().index(1, 2, 3, 4))

def mutate():
    d = deque([1])
    i = iter(d)
    d.append(2)
    next(i)
t(mutate)

print(math.nextafter(1.0, 2.0, steps=3) - 1.0, math.ulp(1.0), math.sumprod([1, 2], [3, 4]))
print(math.floor.__text_signature__, math.isclose.__text_signature__, math.log.__text_signature__)
print(deque.append.__text_signature__, itertools.count.__text_signature__)
print(math.gcd.__text_signature__, deque.__add__.__text_signature__, deque.__setitem__.__text_signature__)
print(repr(math.floor), repr(deque.append), repr(deque().append)[:40])
print(math.floor.__name__, math.floor.__qualname__, math.floor.__module__, deque.append.__qualname__)
