import warnings, _warnings, sys
print(warnings.warn is _warnings.warn, warnings.warn_explicit is _warnings.warn_explicit, warnings.filters is _warnings.filters)
print(warnings._lock.__class__.__name__, warnings._warnings_context is _warnings._warnings_context)
print(warnings.defaultaction, warnings.onceregistry is _warnings._onceregistry)
def f(n):
    for i in range(n):
        warnings.warn("hello", UserWarning)
with warnings.catch_warnings(record=True) as w:
    warnings.simplefilter("default")
    f(3)
    print(len(w), w[0].filename == __file__, w[0].lineno, str(w[0].message))
    warnings.simplefilter("default")
    f(1)
    print(len(w))
    warnings.simplefilter("once")
    f(3)
    print(len(w))
    warnings.simplefilter("error")
    try: f(1)
    except UserWarning as e: print("raised", e)
    warnings.simplefilter("always")
    warnings.warn("x", DeprecationWarning, stacklevel=2)
    warnings.warn("y", skip_file_prefixes=(__file__,))
    print([(str(x.message), x.category.__name__, x.lineno) for x in w[-2:]])
    warnings.warn_explicit("msg", RuntimeWarning, "foo.py", 12, module="mod", registry={})
    print(w[-1].filename, w[-1].lineno, w[-1].category.__name__)
    try: warnings.warn("x", 5)
    except TypeError as e: print(e)
    try: warnings.warn("x", skip_file_prefixes="a")
    except TypeError as e: print(e)
    import array
    a = array.array('u', 'x')
    print(str(w[-1].message), w[-1].filename == __file__)
print(len(warnings.filters))
with warnings.catch_warnings(record=True) as w:
    warnings.resetwarnings()
    warnings.filterwarnings("ignore", message="foo.*")
    warnings.warn("foobar")
    warnings.warn("bar")
    print([str(x.message) for x in w])
print(warnings.formatwarning("m", UserWarning, "f.py", 3, "line"))
warnings.warn("to stderr")
import os
print(sorted(n for n in dir(_warnings) if not n.startswith('__')))
