print(list(zip([1, 2, 3], "ab")))
print(list(zip([1], "abc", [True, False])))
print(list(zip(range(3))))
print(list(zip("ab", "cd", strict=True)))
try:
    list(zip("ab", "c", strict=True))
except ValueError as e:
    print("ValueError", e)
print(list(enumerate("abc")), list(enumerate("abc", 1)), list(enumerate("a", start=-5)))
for i, (a, b) in enumerate(zip("xy", [10, 20])):
    print(i, a, b)
print(list(map(abs, [-1, 2, -3])))
print(list(map(pow, [2, 3], [3, 2])))
print(list(map(str.upper, ["a", "b"])))
print(list(map(lambda x, y: x + y, "ab", "cd")))
print(list(filter(lambda x: x % 2, range(10))))
print(list(filter(None, [0, 1, 2, None, "", "x"])))
print(any([]), all([]), any([0, 1]), all([1, 0]), any("a"), all(""))
print(any(x > 2 for x in [1, 2, 3]), all(x > 0 for x in [1, 2, 3]))
print(list(map(len, ["a", "bb", ""])), sum(map(int, "12345")))
print(dict(enumerate("ab")), dict(zip("ab", [1, 2])))
keys, vals = zip(*{"a": 1, "b": 2}.items())
print(keys, vals)
print(list(zip(*[(1, 2), (3, 4), (5, 6)])))
print(list(map(None.__class__, [])) if False else "skip")
print([*map(chr, range(97, 100))], [*filter(str.isdigit, "a1b2")])
print(len(list(zip(range(1000), range(500)))))
print(list(range(5))[::-1], list(range(10, 0, -4)))
print(list(zip(range(2), range(2), range(2))))
e = enumerate(["a"])
print(next(e), type(e).__name__)
print(list(reversed(list(enumerate("ab")))))
print(max(enumerate([3, 9, 2]), key=lambda p: p[1]))
print(sorted(zip([3, 1, 2], "abc")))
