// node:http2 — Node 20.11's lib/http2.js and lib/internal/http2/{core,compat,util}.js, run as-is
// over an nghttp2-compatible binding written in JS (frames, HPACK, flow control, settings, ping,
// priority, push) on top of lumen's sockets.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/http2gen/gen.js (see tools/README.md).
//
// Generated: the Node sources below are verbatim, each wrapped as a CommonJS-style module; the
// few edits are marked `lumen:`. They reach the platform only through the internalBinding()
// objects this file implements:
//   - http2: Http2Session / Http2Stream handles with nghttp2's behaviour. A session consumes any
//     Duplex socket (net, tls, or a user stream) through its 'data' events and writes frames
//     with `socket.write`.
//   - stream_wrap, uv, fs (FileHandle), stream_pipe: the pieces of Node's StreamBase protocol the
//     http2 core uses to write a file into a stream.

const primordials = new Proxy(__primordials, {
  get: (target, name) => (name === "Proxy" ? Proxy : target[name]),
});

// ---- the module table -------------------------------------------------------------------------
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}
function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {} };
    moduleCache.set(id, module);
    fn(module, module.exports, require, internalBinding, primordials);
    return module.exports;
  }
  const value = builtinModule(id);
  moduleCache.set(id, { exports: value });
  return value;
}
function builtinModule(id) {
  switch (id) {
    case "buffer": case "events": case "stream": case "timers": case "util": case "tls": case "net":
    case "http": case "fs": case "assert": case "path": case "_http_common": case "_http_server":
      return __builtins.get(id);
    case "internal/util/types":
      return __builtins.get("util").types;
    case "internal/url": {
      return { URL, getURLOrigin: (text) => new URL(text).origin };
    }
  }
  throw new Error(`lumen http2: internal module '${id}' is not available`);
}

const { Buffer } = __builtins.get("buffer");
const { codes: baseCodes } = { codes: __errors };

// ---- internal/errors --------------------------------------------------------------------------

const errorMessages = new Map();
const codes = { __proto__: null, ...baseCodes };
function E(key, msg, Base, ...otherBases) {
  errorMessages.set(key, msg);
  const make = (B) => ({
    [key]: function (...args) {
      const props = {};
      const message = typeof msg === "function" ? Reflect.apply(msg, props, args) :
        args.length ? __builtins.get("util").format(msg, ...args) : msg;
      const err = __nodeError(B, key, message);
      for (const k of Object.keys(props)) err[k] = props[k];
      return err;
    },
  })[key];
  codes[key] = make(Base);
  for (const B of otherBases) codes[key][B.name] = make(B);
}
E("ERR_HTTP2_ALTSVC_INVALID_ORIGIN", "HTTP/2 ALTSVC frames require a valid origin", TypeError);
E("ERR_HTTP2_ALTSVC_LENGTH", "HTTP/2 ALTSVC frames are limited to 16382 bytes", TypeError);
E("ERR_HTTP2_CONNECT_AUTHORITY", ":authority header is required for CONNECT requests", Error);
E("ERR_HTTP2_CONNECT_PATH", "The :path header is forbidden for CONNECT requests", Error);
E("ERR_HTTP2_CONNECT_SCHEME", "The :scheme header is forbidden for CONNECT requests", Error);
E("ERR_HTTP2_ERROR", "%s", Error);
E("ERR_HTTP2_GOAWAY_SESSION", "New streams cannot be created after receiving a GOAWAY", Error);
E("ERR_HTTP2_HEADERS_AFTER_RESPOND", "Cannot specify additional headers after response initiated", Error);
E("ERR_HTTP2_HEADERS_SENT", "Response has already been initiated.", Error);
E("ERR_HTTP2_HEADER_SINGLE_VALUE", 'Header field "%s" must only have a single value', TypeError);
E("ERR_HTTP2_INFO_STATUS_NOT_ALLOWED", "Informational status codes cannot be used", RangeError);
E("ERR_HTTP2_INVALID_CONNECTION_HEADERS", 'HTTP/1 Connection specific headers are forbidden: "%s"', TypeError);
E("ERR_HTTP2_INVALID_HEADER_VALUE", 'Invalid value "%s" for header "%s"', TypeError);
E("ERR_HTTP2_INVALID_INFO_STATUS", "Invalid informational status code: %s", RangeError);
E("ERR_HTTP2_INVALID_ORIGIN", "HTTP/2 ORIGIN frames require a valid origin", TypeError);
E("ERR_HTTP2_INVALID_PACKED_SETTINGS_LENGTH", "Packed settings length must be a multiple of six", RangeError);
E("ERR_HTTP2_INVALID_PSEUDOHEADER", '"%s" is an invalid pseudoheader or is used incorrectly', TypeError);
E("ERR_HTTP2_INVALID_SESSION", "The session has been destroyed", Error);
E("ERR_HTTP2_INVALID_SETTING_VALUE", function (name, actual, min = undefined, max = undefined) {
  this.actual = actual;
  if (min !== undefined) {
    this.min = min;
    this.max = max;
  }
  return `Invalid value for setting "${name}": ${actual}`;
}, TypeError, RangeError);
E("ERR_HTTP2_INVALID_STREAM", "The stream has been destroyed", Error);
E("ERR_HTTP2_MAX_PENDING_SETTINGS_ACK", "Maximum number of pending settings acknowledgements", Error);
E("ERR_HTTP2_NESTED_PUSH", "A push stream cannot initiate another push stream.", Error);
E("ERR_HTTP2_NO_MEM", "Out of memory", Error);
E("ERR_HTTP2_NO_SOCKET_MANIPULATION",
  "HTTP/2 sockets should not be directly manipulated (e.g. read and written)", Error);
E("ERR_HTTP2_ORIGIN_LENGTH", "HTTP/2 ORIGIN frames are limited to 16382 bytes", TypeError);
E("ERR_HTTP2_OUT_OF_STREAMS", "No stream ID is available because maximum stream ID has been reached", Error);
E("ERR_HTTP2_PAYLOAD_FORBIDDEN", "Responses with %s status must not have a payload", Error);
E("ERR_HTTP2_PING_CANCEL", "HTTP2 ping cancelled", Error);
E("ERR_HTTP2_PING_LENGTH", "HTTP2 ping payload must be 8 bytes", RangeError);
E("ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED", "Cannot set HTTP/2 pseudo-headers", TypeError);
E("ERR_HTTP2_PUSH_DISABLED", "HTTP/2 client has disabled push streams", Error);
E("ERR_HTTP2_SEND_FILE", "Directories cannot be sent", Error);
E("ERR_HTTP2_SEND_FILE_NOSEEK", "Offset or length can only be specified for regular files", Error);
E("ERR_HTTP2_SESSION_ERROR", "Session closed with error code %s", Error);
E("ERR_HTTP2_SETTINGS_CANCEL", "HTTP2 session settings canceled", Error);
E("ERR_HTTP2_SOCKET_BOUND", "The socket is already bound to an Http2Session", Error);
E("ERR_HTTP2_SOCKET_UNBOUND", "The socket has been disconnected from the Http2Session", Error);
E("ERR_HTTP2_STATUS_101", "HTTP status code 101 (Switching Protocols) is forbidden in HTTP/2", Error);
E("ERR_HTTP2_STATUS_INVALID", "Invalid status code: %s", RangeError);
E("ERR_HTTP2_STREAM_CANCEL", function (error) {
  let msg = "The pending stream has been canceled";
  if (error) {
    this.cause = error;
    if (typeof error.message === "string") msg += ` (caused by: ${error.message})`;
  }
  return msg;
}, Error);
E("ERR_HTTP2_STREAM_ERROR", "Stream closed with error code %s", Error);
E("ERR_HTTP2_STREAM_SELF_DEPENDENCY", "A stream cannot depend on itself", Error);
E("ERR_HTTP2_TOO_MANY_CUSTOM_SETTINGS", "Number of custom settings exceeds MAX_ADDITIONAL_SETTINGS", Error);
E("ERR_HTTP2_TOO_MANY_INVALID_FRAMES", "Too many invalid HTTP/2 frames", Error);
E("ERR_HTTP2_TRAILERS_ALREADY_SENT", "Trailing headers have already been sent", Error);
E("ERR_HTTP2_TRAILERS_NOT_READY",
  "Trailing headers cannot be sent until after the wantTrailers event is emitted", Error);
E("ERR_HTTP2_UNSUPPORTED_PROTOCOL", 'protocol "%s" is unsupported.', Error);

const kIsNodeError = Symbol("kIsNodeError");
function getMessage(key, args, self) {
  const msg = errorMessages.get(key);
  if (typeof msg === "function") return Reflect.apply(msg, self, args);
  return args.length ? __builtins.get("util").format(msg, ...args) : msg;
}
class AbortError extends Error {
  constructor(message = "The operation was aborted", options = undefined) {
    if (options !== undefined && typeof options !== "object") {
      throw new codes.ERR_INVALID_ARG_TYPE("options", "Object", options);
    }
    super(message, options);
    this.code = "ABORT_ERR";
    this.name = "AbortError";
  }
}
function aggregateTwoErrors(innerError, outerError) {
  if (innerError && outerError && innerError !== outerError) {
    if (Array.isArray(outerError.errors)) {
      outerError.errors.push(innerError);
      return outerError;
    }
    const err = new AggregateError([outerError, innerError], outerError.message);
    err.code = outerError.code;
    return err;
  }
  return innerError || outerError;
}
const uvUnmappedError = ["UNKNOWN", "unknown error"];
function getSystemErrorName(errno) {
  const entry = __uvErrmap.get(errno);
  return entry ? entry[0] : `Unknown system error ${errno}`;
}
function errnoException(err, syscall, original) {
  const code = getSystemErrorName(err);
  const message = original ? `${syscall} ${code} ${original}` : `${syscall} ${code}`;
  const ex = new Error(message);
  ex.errno = err;
  ex.code = code;
  ex.syscall = syscall;
  return ex;
}
const internalErrors = {
  codes, aggregateTwoErrors, AbortError, getMessage, kIsNodeError, errnoException,
  hideStackFrames: (fn) => fn,
  captureLargerStackTrace: (err) => { Error.captureStackTrace(err); return err; },
};

// ---- internal/util, internal/async_hooks, internal/timers and friends ---------------------------

const kEmptyObject = Object.freeze({ __proto__: null });
function normalizeEncoding(enc) {
  if (enc == null || enc === "utf8" || enc === "utf-8") return "utf8";
  switch (String(enc).toLowerCase()) {
    case "utf8": case "utf-8": return "utf8";
    case "ucs2": case "ucs-2": case "utf16le": case "utf-16le": return "utf16le";
    case "latin1": case "binary": return "latin1";
    case "base64": case "base64url": case "hex": case "ascii":
      return String(enc).toLowerCase();
    default: return undefined;
  }
}
const internalUtil = {
  kEmptyObject,
  customInspectSymbol: Symbol.for("nodejs.util.inspect.custom"),
  normalizeEncoding,
  assertCrypto() {},
  get promisify() { return __builtins.get("util").promisify; },
};

let asyncIdCounter = 1000;
const newAsyncId = () => ++asyncIdCounter;
const asyncHookSymbols = {
  async_id_symbol: Symbol("asyncId"),
  trigger_async_id_symbol: Symbol("triggerAsyncId"),
  owner_symbol: Symbol("owner_symbol"),
};
const internalAsyncHooks = {
  newAsyncId,
  defaultTriggerAsyncIdScope: (asyncId, fn, ...args) => Reflect.apply(fn, null, args),
  symbols: asyncHookSymbols,
};

const TIMEOUT_MAX = 2 ** 31 - 1;
const internalTimers = {
  kTimeout: Symbol("timeout"),
  setUnrefTimeout(callback, after) {
    const timer = setTimeout(callback, after);
    if (timer && typeof timer.unref === "function") timer.unref();
    return timer;
  },
  getTimerDuration(msecs, name) {
    require("internal/validators").validateNumber(msecs, name);
    if (msecs < 0 || !Number.isFinite(msecs)) {
      throw new codes.ERR_OUT_OF_RANGE(name, "a non-negative finite number", msecs);
    }
    if (msecs > TIMEOUT_MAX) {
      process.emitWarning(`${msecs} does not fit into a 32-bit signed integer.` +
                          `\nTimer duration was truncated to ${TIMEOUT_MAX}.`, "TimeoutOverflowWarning");
      return TIMEOUT_MAX;
    }
    return msecs;
  },
};

function internalAssert(value, message) {
  if (!value) throw new codes.ERR_INTERNAL_ASSERTION(message);
}
internalAssert.fail = (message) => {
  throw new codes.ERR_INTERNAL_ASSERTION(message);
};

const bufferReaders = {
  readUInt16BE(offset = 0) { return (this[offset] << 8) | this[offset + 1]; },
  readUInt32BE(offset = 0) {
    return this[offset] * 0x1000000 + ((this[offset + 1] << 16) | (this[offset + 2] << 8) | this[offset + 3]);
  },
};

let cachedDate = "";
let cachedDateAt = 0;
function utcDate() {
  const now = Date.now();
  if (now - cachedDateAt >= 1000 || cachedDate === "") {
    cachedDate = new Date(now).toUTCString();
    cachedDateAt = now;
  }
  return cachedDate;
}

// `fd instanceof FileHandle` for the fs.promises FileHandle class, which lumen's fs builds
// internally: any object that holds a numeric `fd` and a close() is one.
const FileHandleShim = {
  [Symbol.hasInstance](value) {
    return value !== null && typeof value === "object" && typeof value.fd === "number" &&
      typeof value.close === "function";
  },
};

const shims = {
  __proto__: null,
  "internal/errors": internalErrors,
  "internal/util": internalUtil,
  "internal/async_hooks": internalAsyncHooks,
  "internal/timers": internalTimers,
  "internal/assert": internalAssert,
  "internal/http": { utcDate },
  "internal/fs/promises": { FileHandle: FileHandleShim },
  "internal/util/debuglog": {
    debuglog: (set, cb) => __builtins.get("util").debuglog(set, cb),
  },
  "internal/util/inspect": { format: (...args) => __builtins.get("util").format(...args) },
  "internal/buffer": {
    FastBuffer: function FastBuffer(arrayBuffer, byteOffset, length) {
      return Buffer.from(arrayBuffer, byteOffset, length);
    },
    readUInt16BE: bufferReaders.readUInt16BE,
    readUInt32BE: bufferReaders.readUInt32BE,
  },
};
for (const id of Object.keys(shims)) moduleCache.set(id, { exports: shims[id] });

// ---- internalBinding('uv') and ('stream_wrap') ---------------------------------------------------

const uvBinding = { errname: getSystemErrorName, getErrorMap: () => __uvErrmap };
for (const [errno, [name]] of __uvErrmap) uvBinding[`UV_${name}`] = errno;
const UV_EOF = uvBinding.UV_EOF;
const UV_ECANCELED = uvBinding.UV_ECANCELED;

const kReadBytesOrError = 0;
const kArrayBufferOffset = 1;
const kBytesWritten = 2;
const kLastWriteWasAsync = 3;
const streamBaseState = new Int32Array(5);
class WriteWrap {}
class ShutdownWrap {}
const streamWrapBinding = {
  kReadBytesOrError, kArrayBufferOffset, kBytesWritten, kLastWriteWasAsync, streamBaseState,
  WriteWrap, ShutdownWrap,
};

const bindings = {
  __proto__: null,
  uv: uvBinding,
  stream_wrap: streamWrapBinding,
  fs: { FileHandle: FileHandleShim },
  constants: { get os() { return { signals: __builtins.get("os").constants.signals }; } },
};
function internalBinding(name) {
  const binding = bindings[name];
  if (binding === undefined) throw new Error(`lumen http2: internalBinding('${name}') is not available`);
  return binding;
}

