// Node's internal modules and bindings, for `--expose-internals` (Node's test suite requires
// `internal/...` and `internal/test/binding`). module.js asks `exposedInternals` whether an id is
// provided and loads it from here; without the flag nothing reaches this file.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/internalsgen/gen.js (see tools/README.md).
//
// Three kinds of module live in the table:
//   - Node 20.11's own sources for self-contained modules (internal/errors, internal/util,
//     internal/validators, the queues and lists...), verbatim apart from `lumen:` edits, over the
//     bindings below;
//   - adapters that hand out lumen's implementation of a module under Node's internal name and
//     shape (internal/util/inspect, internal/event_target, internal/timers, ...);
//   - the internal modules the other generated glue files already run (net.js, fs.js,
//     webstreams.js, http2.js, tls.js, url.js, crypto.js), served from their module tables so a
//     test sees the very objects the public modules use.
// internalBinding() serves the bindings lumen implements: the handle and parser bindings of
// net.js/tls.js/http2.js, the constants and uv tables, and JS versions of small native helpers.
// Bindings over libuv/V8 machinery lumen does not have are not provided (requiring one throws).

const primordials = __primordials;

// ---- the module table -------------------------------------------------------------------------
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}

// Internal modules owned by another glue file's module table: id -> the `__internals` name of
// that table's `require`.
const foreignModules = new Map();
for (const [table, ids] of [
  ["netRequire", "internal/net internal/stream_base_commons internal/socketaddress internal/blocklist " +
    "internal/freelist internal/http internal/dgram internal/dns/utils internal/dns/promises " +
    "internal/dns/callback_resolver"],
  ["webstreamsRequire", "internal/webstreams/util internal/webstreams/queuingstrategies " +
    "internal/webstreams/readablestream internal/webstreams/writablestream internal/webstreams/transformstream " +
    "internal/webstreams/encoding internal/webstreams/compression"],
  ["fsRequire", "internal/fs/utils internal/fs/promises internal/fs/streams internal/fs/dir " +
    "internal/fs/read/context internal/fs/rimraf internal/fs/cp/cp internal/fs/cp/cp-sync internal/fs/watchers " +
    "internal/fs/recursive_watch"],
  ["http2Require", "internal/http2/util internal/http2/compat internal/http2/core"],
  ["tlsRequire", "internal/js_stream_socket internal/tls/secure-context internal/tls/secure-pair"],
]) {
  for (const id of ids.split(" ")) foreignModules.set(id, table);
}

function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {}, id, isPreloading: false };
    moduleCache.set(id, module);
    try {
      fn(module, module.exports, require, internalBinding, primordials);
    } catch (error) {
      moduleCache.delete(id);
      throw error;
    }
    return module.exports;
  }
  const table = foreignModules.get(id);
  if (table !== undefined) {
    const exports = __internals.get(table)(id);
    moduleCache.set(id, { exports });
    return exports;
  }
  if (!id.startsWith("internal/") && __builtins.has(id)) return __builtins.get(id);
  throw new Error(`lumen: internal module '${id}' is not available`);
}

function hasModule(id) {
  return moduleDefs.has(id) || foreignModules.has(id);
}

// ---- internalBinding() ------------------------------------------------------------------------
// name -> () => binding, built on first use.
const bindingMakers = { __proto__: null };
const bindingCache = new Map();
function internalBinding(name) {
  name = `${name}`;
  let binding = bindingCache.get(name);
  if (binding === undefined) {
    const make = bindingMakers[name];
    if (make === undefined) throw new Error(`No such binding: ${name}`);
    binding = make();
    bindingCache.set(name, binding);
  }
  return binding;
}

const netBinding = (name) => __internals.get("netBinding")(name);
for (const name of ["uv", "tcp_wrap", "pipe_wrap", "stream_wrap", "udp_wrap", "block_list", "cares_wrap",
  "http_parser"]) {
  bindingMakers[name] = () => netBinding(name);
}
bindingMakers.tls_wrap = () => __internals.get("tlsBinding")("tls_wrap");
bindingMakers.js_stream = () => __internals.get("tlsBinding")("js_stream");
bindingMakers.http2 = () => __internals.get("http2Binding")("http2");
bindingMakers.trace_events = () => __internals.get("trace_events").binding;

const nullProto = (object) => Object.assign({ __proto__: null }, object);
const pick = (object, test) =>
  nullProto(Object.fromEntries(Object.entries(object).filter(([key]) => test(key))));

// Node's src/node_constants.cc, from the values lumen's os/fs/crypto/zlib modules carry.
bindingMakers.constants = () => {
  const os = __builtins.get("os").constants;
  const flat = __builtins.get("constants");
  const trace = nullProto({});
  "BEGIN:B END:E COMPLETE:X INSTANT:I ASYNC_BEGIN:S ASYNC_STEP_INTO:T ASYNC_STEP_PAST:p ASYNC_END:F " +
    "NESTABLE_ASYNC_BEGIN:b NESTABLE_ASYNC_END:e NESTABLE_ASYNC_INSTANT:n FLOW_BEGIN:s FLOW_STEP:t FLOW_END:f " +
    "METADATA:M COUNTER:C SAMPLE:P CREATE_OBJECT:N SNAPSHOT_OBJECT:O DELETE_OBJECT:D MEMORY_DUMP:v MARK:R " +
    "CLOCK_SYNC:c ENTER_CONTEXT:( LEAVE_CONTEXT:) LINK_IDS:=".split(" ").forEach((entry) => {
    const [name, phase] = entry.split(":");
    trace[`TRACE_EVENT_PHASE_${name}`] = phase.charCodeAt(0);
  });
  return nullProto({
    os: nullProto({
      UV_UDP_REUSEADDR: 4,
      dlopen: pick(flat, (key) => key.startsWith("RTLD_")),
      errno: nullProto(os.errno),
      signals: nullProto(os.signals),
      priority: pick(flat, (key) => key.startsWith("PRIORITY_")),
    }),
    fs: nullProto(__builtins.get("fs").constants),
    crypto: nullProto(__builtins.get("crypto").constants),
    zlib: nullProto(__builtins.get("zlib").constants),
    trace,
  });
};

// Private symbols: V8 hides them from reflection; plain symbols are the closest lumen has.
const privateSymbols = nullProto({
  arrow_message_private_symbol: Symbol("node:arrowMessage"),
  contextify_context_private_symbol: Symbol("node:contextify:context"),
  decorated_private_symbol: Symbol("node:decorated"),
  host_defined_option_symbol: Symbol("node:host_defined_option_symbol"),
  napi_type_tag: Symbol("node:napi:type_tag"),
  napi_wrapper: Symbol("node:napi:wrapper"),
  untransferable_object_private_symbol: Symbol("node:untransferableObject"),
  exit_info_private_symbol: Symbol("node:exit_info_private_symbol"),
  promise_trace_id: Symbol("node:promise_trace_id"),
});

const kPending = 0;
const kFulfilled = 1;
const kRejected = 2;

// Node's src/node_util.cc.
bindingMakers.util = () => {
  const ALL_PROPERTIES = 0;
  const ONLY_ENUMERABLE = 2;
  const sleepCell = new Int32Array(new SharedArrayBuffer(4));
  return {
    constants: nullProto({
      kPending, kFulfilled, kRejected,
      kExiting: 0, kExitCode: 1, kHasExitCode: 2,
      ALL_PROPERTIES, ONLY_WRITABLE: 1, ONLY_ENUMERABLE, ONLY_CONFIGURABLE: 4, SKIP_STRINGS: 8, SKIP_SYMBOLS: 16,
      kDisallowCloneAndTransfer: 0, kTransferable: 1, kCloneable: 2,
    }),
    privateSymbols,
    getPromiseDetails(promise) {
      const state = __node.promiseState(promise);
      if (state === undefined) return undefined;
      const code = state[0] === "pending" ? kPending : state[0] === "fulfilled" ? kFulfilled : kRejected;
      return code === kPending ? [code] : [code, state[1]];
    },
    getProxyDetails(value, showProxy = true) {
      const parts = __node.proxyParts(value);
      if (parts === undefined || parts === null) return undefined;
      return showProxy ? [parts[0], parts[1]] : parts[0];
    },
    previewEntries(iterator, isIterator) {
      return __node.previewEntries(iterator, isIterator);
    },
    getOwnNonIndexProperties(object, filter) {
      const keys = filter === ONLY_ENUMERABLE ? Object.keys(object) : Reflect.ownKeys(object);
      return keys.filter((key) => {
        if (typeof key === "symbol") return filter !== ONLY_ENUMERABLE ||
          Object.prototype.propertyIsEnumerable.call(object, key);
        const index = Number(key);
        return !(String(index >>> 0) === key && index >>> 0 !== 2 ** 32 - 1);
      });
    },
    getConstructorName(object) {
      for (let o = object; o !== null && o !== undefined; o = Object.getPrototypeOf(o)) {
        const descriptor = Object.getOwnPropertyDescriptor(o, "constructor");
        if (descriptor !== undefined && typeof descriptor.value === "function" && descriptor.value.name !== "") {
          return descriptor.value.name;
        }
      }
      return "";
    },
    sleep(msec) {
      Atomics.wait(sleepCell, 0, 0, msec);
    },
    isArrayBufferDetached(value) {
      return value instanceof ArrayBuffer && value.detached === true;
    },
    arrayBufferViewHasBuffer() {
      // V8 allocates small typed arrays on-heap until `.buffer` is first read; lumen always
      // allocates the ArrayBuffer up front.
      return true;
    },
    guessHandleType(fd) {
      return guessHandleType(fd);
    },
    toUSVString(string, start) {
      return string.slice(0, start) + string.slice(start).toWellFormed();
    },
    isInsideNodeModules() {
      return false;
    },
    defineLazyProperties(target, id, keys, enumerable = true) {
      for (const key of keys) {
        let value;
        let set = false;
        Object.defineProperty(target, key, {
          __proto__: null,
          enumerable,
          configurable: true,
          get() {
            if (!set) value = require(id)[key];
            return value;
          },
          set(v) {
            value = v;
            set = true;
          },
        });
      }
    },
    shouldAbortOnUncaughtToggle: new Int32Array(1),
    WeakReference: class WeakReference {
      #ref;
      #strong = null;
      #count = 0;
      constructor(object) {
        this.#ref = new WeakRef(object);
      }
      get() {
        return this.#ref.deref();
      }
      incRef() {
        if (this.#count++ === 0) this.#strong = this.#ref.deref();
        return this.#count;
      }
      decRef() {
        if (--this.#count === 0) this.#strong = null;
        return this.#count;
      }
    },
  };
};

function guessHandleType(fd) {
  if (!Number.isInteger(fd) || fd < 0) return "INVALID";
  if (__builtins.get("tty").isatty(fd)) return "TTY";
  let stats;
  try {
    stats = __builtins.get("fs").fstatSync(fd);
  } catch {
    return "INVALID";
  }
  if (stats.isFile() || stats.isCharacterDevice() || stats.isBlockDevice()) return "FILE";
  if (stats.isFIFO() || stats.isSocket()) return "PIPE";
  return "UNKNOWN";
}

bindingMakers.types = () => {
  const types = __builtins.get("util/types");
  return { __proto__: null, ...types, isNativeError: types.isNativeError };
};

bindingMakers.errors = () => ({
  noSideEffectsToString: (value) => String(value),
  triggerUncaughtException(error) {
    throw error;
  },
  exitCodes: nullProto({ kNoFailure: 0, kGenericUserError: 1 }),
  setPrepareStackTraceCallback() {},
  setGetSourceMapErrorSource() {},
  setSourceMapsEnabled() {},
  setMaybeCacheGeneratedSourceMap() {},
  setEnhanceStackForFatalException() {},
});

bindingMakers.os = () => ({
  getOSInformation() {
    const os = __builtins.get("os");
    return [os.type(), os.version(), os.release(), os.machine()];
  },
});

// Node's src/node_credentials.cc: the variable unless the process runs set-uid/set-gid.
bindingMakers.credentials = () => ({
  safeGetenv(name) {
    return process.env[name];
  },
  implementsPosixCredentials: typeof process.getuid === "function",
});

bindingMakers.config = () => ({
  hasIntl: typeof Intl === "object",
  hasSmallICU: false,
  hasInspector: false,
  hasNodeOptions: true,
  noBrowserGlobals: false,
  bits: 64,
  isDebugBuild: false,
  hasOpenSSL: true,
  fipsMode: false,
});

// The options as the command line set them (lumen-cli parses Node's grammar into
// `process[Symbol.for("lumen.options")]`).
function cliOptions() {
  return process[Symbol.for("lumen.options")] || {};
}

// ---- adapters ---------------------------------------------------------------------------------

defineModule("internal/test/binding", function (module) {
  process.emitWarning("These APIs are for internal testing only. Do not use them.", "internal/test/binding");
  module.exports = { internalBinding, primordials };
});

defineModule("internal/util/inspect", function (module) {
  const util = __builtins.get("util");
  const { getStringWidth } = __internals.get("util_inspect");
  module.exports = {
    inspect: util.inspect,
    inspectDefaultOptions: util.inspect.defaultOptions,
    format: util.format,
    formatWithOptions: util.formatWithOptions,
    getStringWidth,
    stripVTControlCharacters: util.stripVTControlCharacters,
    isError: (e) => util.types.isNativeError(e) || e instanceof Error,
  };
});

defineModule("internal/util/types", function (module) {
  module.exports = __builtins.get("util/types");
});

defineModule("internal/options", function (module) {
  // Defaults of the options lumen's runtime reads; an option the command line did not set and
  // that is not listed here reads as undefined.
  const defaults = {
    __proto__: null,
    "--network-family-autoselection": true,
    "--network-family-autoselection-attempt-timeout": 250,
    "--max-http-header-size": 16 * 1024,
    "--stack-trace-limit": 10,
    "--unhandled-rejections": "",
    "--dns-result-order": "",
    "--diagnostic-dir": "",
    "--redirect-warnings": "",
    "--title": "",
    "--input-type": "",
    "--experimental-default-type": "",
    "--trace-event-categories": "",
    "--trace-event-file-pattern": "node_trace.${rotation}.log",
    "--require": [],
    "--import": [],
    "--conditions": [],
    "--env-file": [],
  };
  const lists = ["--require", "--import", "--conditions", "--env-file"];
  function getOptionValue(name) {
    const parsed = cliOptions();
    if (name.startsWith("--no-")) {
      const value = getOptionValue("--" + name.slice(5));
      return value === undefined ? undefined : !value;
    }
    if (Object.hasOwn(parsed, name)) {
      const value = parsed[name];
      if (name === "--max-http-header-size" || name === "--stack-trace-limit" ||
          name === "--network-family-autoselection-attempt-timeout") {
        return Number(value);
      }
      if (lists.includes(name) && !Array.isArray(value)) return [value];
      return value;
    }
    if (name === "--pending-deprecation") return process.env.NODE_PENDING_DEPRECATION?.[0] === "1";
    if (name in defaults) return defaults[name];
    return name.startsWith("--") ? false : undefined;
  }
  module.exports = {
    getOptionValue,
    getAllowUnauthorized: () => process.env.NODE_TLS_REJECT_UNAUTHORIZED === "0",
    getEmbedderOptions: () => ({ shouldNotRegisterESMLoader: false, noGlobalSearchPaths: false, hasEmbedderPreload: false }),
    refreshOptions() {},
  };
});

defineModule("internal/timers", function (module) {
  const net = __internals.get("netRequire")("internal/timers");
  module.exports = {
    kTimeout: net.kTimeout,
    TIMEOUT_MAX: 2 ** 31 - 1,
    setUnrefTimeout: net.setUnrefTimeout,
    getTimerDuration: net.getTimerDuration,
  };
});

defineModule("internal/async_hooks", function (module) {
  module.exports = __internals.get("netRequire")("internal/async_hooks");
});

defineModule("internal/streams/state", function (module) {
  const stream = __builtins.get("stream");
  module.exports = {
    getDefaultHighWaterMark: stream.getDefaultHighWaterMark,
    setDefaultHighWaterMark: stream.setDefaultHighWaterMark,
  };
});

defineModule("internal/v8/startup_snapshot", function (module) {
  const v8 = __builtins.get("v8");
  module.exports = { namespace: v8.startupSnapshot };
});

defineModule("internal/streams/compose", function (module) {
  module.exports = __internals.get("streamsInternal").compose;
});

defineModule("internal/streams/add-abort-signal", function (module) {
  module.exports = __internals.get("streamsInternal").addAbortSignal;
});

// Node's adapters also convert to and from StreamBase handles (newReadableStreamFromStreamBase,
// ...); lumen's handles are not StreamBase, so only the stream <-> web stream adapters exist.
defineModule("internal/webstreams/adapters", function (module) {
  module.exports = __internals.get("streamsInternal").adapters;
});

