// Node's internal modules and bindings, for `--expose-internals` (Node's test suite requires
// `internal/...` and `internal/test/binding`). module.js asks `exposedInternals` whether an id is
// provided and loads it from here; without the flag nothing reaches this file.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/internalsgen/gen.js (see tools/README.md).
//
// Three kinds of module live in the table:
//   - Node 20.11's own sources for self-contained modules (internal/errors, internal/util,
//     internal/validators, the queues and lists...), verbatim apart from `lumen:` edits, over the
//     bindings below;
//   - adapters that hand out lumen's implementation of a module under Node's internal name and
//     shape (internal/util/inspect, internal/event_target, internal/timers, ...);
//   - the internal modules the other generated glue files already run (net.js, fs.js,
//     webstreams.js, http2.js, tls.js, url.js, crypto.js), served from their module tables so a
//     test sees the very objects the public modules use.
// internalBinding() serves the bindings lumen implements: the handle and parser bindings of
// net.js/tls.js/http2.js, the constants and uv tables, and JS versions of small native helpers.
// Bindings over libuv/V8 machinery lumen does not have are not provided (requiring one throws).

const primordials = __primordials;

// ---- the module table -------------------------------------------------------------------------
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}

// Internal modules owned by another glue file's module table: id -> the `__internals` name of
// that table's `require`.
const foreignModules = new Map();
for (const [table, ids] of [
  ["netRequire", "internal/net internal/stream_base_commons internal/socketaddress internal/blocklist " +
    "internal/freelist internal/http internal/dgram internal/dns/utils internal/dns/promises " +
    "internal/dns/callback_resolver"],
  ["webstreamsRequire", "internal/webstreams/util internal/webstreams/queuingstrategies " +
    "internal/webstreams/readablestream internal/webstreams/writablestream internal/webstreams/transformstream " +
    "internal/webstreams/encoding internal/webstreams/compression"],
  ["fsRequire", "internal/fs/utils internal/fs/promises internal/fs/streams internal/fs/dir " +
    "internal/fs/read/context internal/fs/rimraf internal/fs/cp/cp internal/fs/cp/cp-sync internal/fs/watchers " +
    "internal/fs/recursive_watch"],
  ["http2Require", "internal/http2/util internal/http2/compat internal/http2/core"],
  ["tlsRequire", "internal/js_stream_socket internal/tls/secure-context internal/tls/secure-pair"],
  ["readlineRequire", "internal/readline/utils internal/readline/callbacks internal/readline/interface " +
    "internal/readline/emitKeypressEvents internal/readline/promises"],
  ["testRunnerRequire", "internal/error_serdes internal/watch_mode/files_watcher internal/test_runner/tests_stream " +
    "internal/test_runner/utils internal/test_runner/test internal/test_runner/harness internal/test_runner/runner " +
    "internal/test_runner/coverage internal/test_runner/mock/mock internal/test_runner/mock/mock_timers " +
    "internal/test_runner/reporter/dot internal/test_runner/reporter/junit internal/test_runner/reporter/lcov " +
    "internal/test_runner/reporter/spec internal/test_runner/reporter/tap internal/test_runner/reporter/v8-serializer"],
  ["urlRequire", "internal/url internal/querystring"],
  ["cryptoRequire", "internal/crypto/aes internal/crypto/argon2 internal/crypto/certificate internal/crypto/cfrg " +
    "internal/crypto/cipher internal/crypto/diffiehellman internal/crypto/ec internal/crypto/hash " +
    "internal/crypto/hashnames internal/crypto/hkdf internal/crypto/keygen internal/crypto/keys " +
    "internal/crypto/mac internal/crypto/pbkdf2 internal/crypto/random internal/crypto/rsa internal/crypto/scrypt " +
    "internal/crypto/sig internal/crypto/util internal/crypto/webcrypto internal/crypto/webidl internal/crypto/x509"],
  ["builtinInternals", "internal/child_process internal/cluster/round_robin_handle " +
    "internal/cluster/shared_handle internal/cluster/worker internal/cluster/utils"],
]) {
  for (const id of ids.split(" ")) foreignModules.set(id, table);
}

__internals.set("builtinInternals", (id) => __builtins.get(id));

function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {}, id, isPreloading: false };
    moduleCache.set(id, module);
    try {
      fn(module, module.exports, require, internalBinding, primordials);
    } catch (error) {
      moduleCache.delete(id);
      throw error;
    }
    return module.exports;
  }
  const table = foreignModules.get(id);
  if (table !== undefined) {
    const exports = __internals.get(table)(id);
    moduleCache.set(id, { exports });
    return exports;
  }
  if (!id.startsWith("internal/") && __builtins.has(id)) return __builtins.get(id);
  throw new Error(`lumen: internal module '${id}' is not available`);
}

function hasModule(id) {
  return moduleDefs.has(id) || foreignModules.has(id);
}

// ---- internalBinding() ------------------------------------------------------------------------
// name -> () => binding, built on first use.
const bindingMakers = { __proto__: null };
const bindingCache = new Map();
function internalBinding(name) {
  name = `${name}`;
  let binding = bindingCache.get(name);
  if (binding === undefined) {
    const make = bindingMakers[name];
    if (make === undefined) throw new Error(`No such binding: ${name}`);
    binding = make();
    bindingCache.set(name, binding);
  }
  return binding;
}

const netBinding = (name) => __internals.get("netBinding")(name);
for (const name of ["uv", "tcp_wrap", "pipe_wrap", "stream_wrap", "udp_wrap", "block_list", "cares_wrap",
  "http_parser"]) {
  bindingMakers[name] = () => netBinding(name);
}
bindingMakers.tls_wrap = () => __internals.get("tlsBinding")("tls_wrap");
bindingMakers.js_stream = () => __internals.get("tlsBinding")("js_stream");
bindingMakers.http2 = () => __internals.get("http2Binding")("http2");
bindingMakers.crypto = () => __internals.get("cryptoBinding");
bindingMakers.trace_events = () => __internals.get("trace_events").binding;

const nullProto = (object) => Object.assign({ __proto__: null }, object);
const pick = (object, test) =>
  nullProto(Object.fromEntries(Object.entries(object).filter(([key]) => test(key))));

// Node's src/node_constants.cc, from the values lumen's os/fs/crypto/zlib modules carry.
bindingMakers.constants = () => {
  const os = __builtins.get("os").constants;
  const flat = __builtins.get("constants");
  const trace = nullProto({});
  "BEGIN:B END:E COMPLETE:X INSTANT:I ASYNC_BEGIN:S ASYNC_STEP_INTO:T ASYNC_STEP_PAST:p ASYNC_END:F " +
    "NESTABLE_ASYNC_BEGIN:b NESTABLE_ASYNC_END:e NESTABLE_ASYNC_INSTANT:n FLOW_BEGIN:s FLOW_STEP:t FLOW_END:f " +
    "METADATA:M COUNTER:C SAMPLE:P CREATE_OBJECT:N SNAPSHOT_OBJECT:O DELETE_OBJECT:D MEMORY_DUMP:v MARK:R " +
    "CLOCK_SYNC:c ENTER_CONTEXT:( LEAVE_CONTEXT:) LINK_IDS:=".split(" ").forEach((entry) => {
    const [name, phase] = entry.split(":");
    trace[`TRACE_EVENT_PHASE_${name}`] = phase.charCodeAt(0);
  });
  return nullProto({
    os: nullProto({
      UV_UDP_REUSEADDR: 4,
      dlopen: pick(flat, (key) => key.startsWith("RTLD_")),
      errno: nullProto(os.errno),
      signals: nullProto(os.signals),
      priority: pick(flat, (key) => key.startsWith("PRIORITY_")),
    }),
    fs: nullProto(__builtins.get("fs").constants),
    crypto: nullProto(__builtins.get("crypto").constants),
    zlib: nullProto(__builtins.get("zlib").constants),
    trace,
  });
};

// Private symbols: V8 hides them from reflection; plain symbols are the closest lumen has.
const privateSymbols = nullProto({
  arrow_message_private_symbol: Symbol("node:arrowMessage"),
  contextify_context_private_symbol: Symbol("node:contextify:context"),
  decorated_private_symbol: Symbol("node:decorated"),
  host_defined_option_symbol: Symbol("node:host_defined_option_symbol"),
  napi_type_tag: Symbol("node:napi:type_tag"),
  napi_wrapper: Symbol("node:napi:wrapper"),
  untransferable_object_private_symbol: Symbol("node:untransferableObject"),
  exit_info_private_symbol: Symbol("node:exit_info_private_symbol"),
  promise_trace_id: Symbol("node:promise_trace_id"),
});

const kPending = 0;
const kFulfilled = 1;
const kRejected = 2;

// Node's src/node_util.cc.
bindingMakers.util = () => {
  const ALL_PROPERTIES = 0;
  const ONLY_ENUMERABLE = 2;
  const sleepCell = new Int32Array(new SharedArrayBuffer(4));
  return {
    constants: nullProto({
      kPending, kFulfilled, kRejected,
      kExiting: 0, kExitCode: 1, kHasExitCode: 2,
      ALL_PROPERTIES, ONLY_WRITABLE: 1, ONLY_ENUMERABLE, ONLY_CONFIGURABLE: 4, SKIP_STRINGS: 8, SKIP_SYMBOLS: 16,
      kDisallowCloneAndTransfer: 0, kTransferable: 1, kCloneable: 2,
    }),
    privateSymbols,
    getPromiseDetails(promise) {
      const state = __node.promiseState(promise);
      if (state === undefined) return undefined;
      const code = state[0] === "pending" ? kPending : state[0] === "fulfilled" ? kFulfilled : kRejected;
      return code === kPending ? [code] : [code, state[1]];
    },
    getProxyDetails(value, showProxy = true) {
      const parts = __node.proxyParts(value);
      if (parts === undefined || parts === null) return undefined;
      return showProxy ? [parts[0], parts[1]] : parts[0];
    },
    previewEntries(iterator, isIterator) {
      return __node.previewEntries(iterator, isIterator);
    },
    getOwnNonIndexProperties(object, filter) {
      const keys = filter === ONLY_ENUMERABLE ? Object.keys(object) : Reflect.ownKeys(object);
      return keys.filter((key) => {
        if (typeof key === "symbol") return filter !== ONLY_ENUMERABLE ||
          Object.prototype.propertyIsEnumerable.call(object, key);
        const index = Number(key);
        return !(String(index >>> 0) === key && index >>> 0 !== 2 ** 32 - 1);
      });
    },
    getConstructorName(object) {
      for (let o = object; o !== null && o !== undefined; o = Object.getPrototypeOf(o)) {
        const descriptor = Object.getOwnPropertyDescriptor(o, "constructor");
        if (descriptor !== undefined && typeof descriptor.value === "function" && descriptor.value.name !== "") {
          return descriptor.value.name;
        }
      }
      return "";
    },
    sleep(msec) {
      Atomics.wait(sleepCell, 0, 0, msec);
    },
    isArrayBufferDetached(value) {
      return value instanceof ArrayBuffer && value.detached === true;
    },
    arrayBufferViewHasBuffer() {
      // V8 allocates small typed arrays on-heap until `.buffer` is first read; lumen always
      // allocates the ArrayBuffer up front.
      return true;
    },
    guessHandleType(fd) {
      return guessHandleType(fd);
    },
    toUSVString(string, start) {
      return string.slice(0, start) + string.slice(start).toWellFormed();
    },
    isInsideNodeModules() {
      return false;
    },
    defineLazyProperties(target, id, keys, enumerable = true) {
      for (const key of keys) {
        let value;
        let set = false;
        Object.defineProperty(target, key, {
          __proto__: null,
          enumerable,
          configurable: true,
          get() {
            if (!set) value = require(id)[key];
            return value;
          },
          set(v) {
            value = v;
            set = true;
          },
        });
      }
    },
    shouldAbortOnUncaughtToggle: new Int32Array(1),
    WeakReference: class WeakReference {
      #ref;
      #strong = null;
      #count = 0;
      constructor(object) {
        this.#ref = new WeakRef(object);
      }
      get() {
        return this.#ref.deref();
      }
      incRef() {
        if (this.#count++ === 0) this.#strong = this.#ref.deref();
        return this.#count;
      }
      decRef() {
        if (--this.#count === 0) this.#strong = null;
        return this.#count;
      }
    },
  };
};

function guessHandleType(fd) {
  if (!Number.isInteger(fd) || fd < 0) return "INVALID";
  if (__builtins.get("tty").isatty(fd)) return "TTY";
  let stats;
  try {
    stats = __builtins.get("fs").fstatSync(fd);
  } catch {
    return "INVALID";
  }
  if (stats.isFile() || stats.isCharacterDevice() || stats.isBlockDevice()) return "FILE";
  if (stats.isFIFO() || stats.isSocket()) return "PIPE";
  return "UNKNOWN";
}

bindingMakers.types = () => {
  const types = __builtins.get("util/types");
  return { __proto__: null, ...types, isNativeError: types.isNativeError };
};

bindingMakers.errors = () => ({
  noSideEffectsToString: (value) => String(value),
  triggerUncaughtException(error) {
    throw error;
  },
  exitCodes: nullProto({ kNoFailure: 0, kGenericUserError: 1 }),
  setPrepareStackTraceCallback() {},
  setGetSourceMapErrorSource() {},
  setSourceMapsEnabled() {},
  setMaybeCacheGeneratedSourceMap() {},
  setEnhanceStackForFatalException() {},
});

bindingMakers.os = () => ({
  getOSInformation() {
    const os = __builtins.get("os");
    return [os.type(), os.version(), os.release(), os.machine()];
  },
});

// Node's src/node_credentials.cc: the variable unless the process runs set-uid/set-gid.
bindingMakers.credentials = () => ({
  safeGetenv(name) {
    return process.env[name];
  },
  implementsPosixCredentials: typeof process.getuid === "function",
});

bindingMakers.config = () => ({
  hasIntl: typeof Intl === "object",
  hasSmallICU: false,
  hasInspector: false,
  hasNodeOptions: true,
  noBrowserGlobals: false,
  bits: 64,
  isDebugBuild: false,
  hasOpenSSL: true,
  fipsMode: false,
});

bindingMakers.contextify = () => ({
  startSigintWatchdog: () => __node.sigintWatchdogStart(),
  stopSigintWatchdog: () => __node.sigintWatchdogStop(),
  watchdogHasPendingSigint: () => __node.sigintWatchdogPending(),
});

// Node's src/signal_wrap.cc: a handle that delivers one signal to `onsignal`.
bindingMakers.signal_wrap = () => {
  const names = new Map(Object.entries(__builtins.get("os").constants.signals).map(([name, number]) => [number, name]));
  const kEINVAL = -22;
  class Signal {
    #key;
    #refed = true;
    #closed = false;
    static #check(self) {
      if (typeof self !== "object" || self === null || !(#refed in self)) throw new TypeError("Illegal invocation");
    }
    start(signum) {
      Signal.#check(this);
      const name = names.get(signum);
      if (name === undefined || this.#closed) return kEINVAL;
      this.#stop();
      try {
        this.#key = __node.signalWatch(name, (number) => this.onsignal?.(number));
      } catch {
        return kEINVAL;
      }
      return 0;
    }
    #stop() {
      if (this.#key !== undefined) __node.signalUnwatch(this.#key);
      this.#key = undefined;
    }
    stop() {
      Signal.#check(this);
      this.#stop();
      return 0;
    }
    close(callback) {
      Signal.#check(this);
      this.#stop();
      this.#closed = true;
      if (typeof callback === "function") process.nextTick(callback);
    }
    ref() {
      Signal.#check(this);
      this.#refed = true;
    }
    unref() {
      Signal.#check(this);
      this.#refed = false;
    }
    hasRef() {
      Signal.#check(this);
      return this.#refed;
    }
    getAsyncId() {
      Signal.#check(this);
      return 0;
    }
  }
  return { Signal };
};

// The options as the command line set them (lumen-cli parses Node's grammar into
// `process[Symbol.for("lumen.options")]`).
function cliOptions() {
  return process[Symbol.for("lumen.options")] || {};
}

bindingMakers.timers = () => {
  const start = performance.now();
  return {
    getLibuvNow: () => Math.floor(performance.now() - start),
    setupTimers() {},
    scheduleTimer() {},
    toggleTimerRef() {},
    toggleImmediateRef() {},
    immediateInfo: new Uint32Array(3),
    timerInfo: new Int32Array(1),
  };
};

bindingMakers.async_wrap = () => {
  return {
    queueDestroyAsyncId: (id) => __internals.get("asyncHookRuntime").destroy(id),
    async_hook_fields: new Uint32Array(8),
    async_id_fields: new Float64Array(4),
    async_ids_stack: new Float64Array(32),
    execution_async_resources: [],
    constants: { kInit: 0, kBefore: 1, kAfter: 2, kDestroy: 3, kPromiseResolve: 4, kTotals: 5, kCheck: 6,
      kStackLength: 7, kUsesExecutionAsyncResource: 8, kExecutionAsyncId: 0, kTriggerAsyncId: 1,
      kAsyncIdCounter: 2, kDefaultTriggerAsyncId: 3 },
  };
};

// The StreamBase accessors throw on a receiver that is not a handle, yet stay visible to
// getOwnPropertyDescriptor.
bindingMakers.tty_wrap = () => {
  class LibuvStreamWrap {
    #handle = true;
    static #check(self) {
      if (typeof self !== "object" || self === null || !(#handle in self)) throw new TypeError("Illegal invocation");
    }
    static {
      for (const name of ["bytesRead", "fd", "_externalStream"]) {
        Object.defineProperty(LibuvStreamWrap.prototype, name, {
          configurable: true,
          get() {
            LibuvStreamWrap.#check(this);
            return name === "fd" ? this.fdValue : 0;
          },
        });
      }
    }
  }
  class TTY extends LibuvStreamWrap {
    constructor(fd) {
      super();
      this.fdValue = fd;
    }
  }
  return { TTY, isTTY: (fd) => __builtins.get("tty").isatty(fd) };
};

// ---- adapters ---------------------------------------------------------------------------------

defineModule("internal/worker/js_transferable", function (module) {
  const kClone = Symbol.for("lumen.transferable.clone");
  const kDeserialize = Symbol.for("lumen.transferable.deserialize");
  class JSTransferable {
    // Node's is a native class: objects it deserializes are not instances of it.
    static [Symbol.hasInstance](value) {
      return this !== JSTransferable && Function.prototype[Symbol.hasInstance].call(this, value);
    }
  }
  module.exports = {
    JSTransferable,
    kClone,
    kDeserialize,
    kTransfer: Symbol("kTransfer"),
    kTransferList: Symbol("kTransferList"),
    kDisallowCloneAndTransfer: Symbol("kDisallowCloneAndTransfer"),
    makeTransferable: (object) => object,
    markTransferMode() {},
    setup() {},
  };
});

__internals.set("cloneModule:internal/test", (id, name) => require(id)[name]);
defineModule("internal/test/transfer", function (module) {
  const { JSTransferable, kClone, kDeserialize } = require("internal/worker/js_transferable");
  class E extends JSTransferable {
    constructor(b) {
      super();
      this.b = b;
    }
    [kClone]() {
      return { data: { b: this.b }, deserializeInfo: "internal/test/transfer:E" };
    }
    [kDeserialize]({ b }) {
      this.b = b;
    }
  }
  class F extends E {
    [kClone]() {
      return { data: { b: this.b }, deserializeInfo: "internal/test/transfer:F" };
    }
  }
  module.exports = { E, F };
});

defineModule("internal/test/binding", function (module) {
  process.emitWarning("These APIs are for internal testing only. Do not use them.", "internal/test/binding");
  module.exports = { internalBinding, primordials };
});

defineModule("internal/event_target", function (module) {
  const e = __eventTargetInternals;
  module.exports = {
    Event: e.Event,
    CustomEvent: e.CustomEvent,
    EventTarget: e.EventTarget,
    NodeEventTarget: e.NodeEventTarget,
    defineEventHandler: e.defineEventHandler,
    initEventTarget: e.initEventTarget,
    initNodeEventTarget: e.initEventTarget,
    isEventTarget: (value) => e.isEventTarget(value),
    kCreateEvent: e.kCreateEvent,
    kEvents: e.kEvents,
    kHybridDispatch: e.kHybridDispatch,
    kIsNodeStyleListener: e.kIsNodeStyleListener,
    kMaxEventTargetListeners: e.kMaxEventTargetListeners,
    kMaxEventTargetListenersWarned: e.kMaxEventTargetListenersWarned,
    kNewListener: e.kNewListener,
    kRemoveListener: e.kRemoveListener,
    kResistStopPropagation: e.kResistStopPropagation,
    kTrustEvent: e.kTrustEvent,
    kWeakHandler: e.kWeakHandler,
  };
});

defineModule("internal/webidl", function (module) {
  const kEmptyObject = Object.freeze({ __proto__: null });
  const censorNegativeZero = (x) => (x === 0 ? 0 : x);
  const integerPart = (n) => censorNegativeZero(Math.trunc(n));
  function evenRound(x) {
    if ((x > 0 && (x % 1) === 0.5 && (x & 1) === 0) || (x < 0 && (x % 1) === -0.5 && (x & 1) === 1)) {
      return censorNegativeZero(Math.floor(x));
    }
    return censorNegativeZero(Math.round(x));
  }
  function convertToInt(name, value, bitLength, options = kEmptyObject) {
    const { signed = false, enforceRange = false, clamp = false } = options;
    let upperBound;
    let lowerBound;
    if (bitLength === 64) {
      upperBound = Number.MAX_SAFE_INTEGER;
      lowerBound = signed ? Number.MIN_SAFE_INTEGER : 0;
    } else if (!signed) {
      lowerBound = 0;
      upperBound = 2 ** bitLength - 1;
    } else {
      lowerBound = -(2 ** (bitLength - 1));
      upperBound = 2 ** (bitLength - 1) - 1;
    }
    const { codes: { ERR_INVALID_ARG_VALUE } } = require("internal/errors");
    let x = censorNegativeZero(Number(value));
    if (enforceRange) {
      if (!Number.isFinite(x)) throw new ERR_INVALID_ARG_VALUE(name, value, "is not a finite number");
      x = integerPart(x);
      if (x < lowerBound || x > upperBound) {
        throw new ERR_INVALID_ARG_VALUE(name, value, `is outside the accepted range of ${lowerBound} to ${upperBound}`);
      }
      return x;
    }
    if (!Number.isNaN(x) && clamp) {
      x = Math.min(Math.max(x, lowerBound), upperBound);
      return censorNegativeZero(evenRound(x));
    }
    if (!Number.isFinite(x) || x === 0) return 0;
    x = integerPart(x);
    if (x >= lowerBound && x <= upperBound) return x;
    x = ((x % 2 ** bitLength) + 2 ** bitLength) % 2 ** bitLength;
    if (signed && x >= 2 ** (bitLength - 1)) return x - 2 ** bitLength;
    return x;
  }
  module.exports = { convertToInt, evenRound, integerPart, censorNegativeZero };
});

defineModule("internal/console/constructor", function (module) {
  const pad = (value) => String(value).padStart(2, "0");
  function formatTime(ms) {
    let hours = 0;
    let minutes = 0;
    let seconds = 0;
    if (ms >= 1000) {
      if (ms >= 60000) {
        if (ms >= 3600000) {
          hours = Math.floor(ms / 3600000);
          ms %= 3600000;
        }
        minutes = Math.floor(ms / 60000);
        ms %= 60000;
      }
      seconds = ms / 1000;
    }
    if (hours !== 0 || minutes !== 0) {
      [seconds, ms] = seconds.toFixed(3).split(".");
      const res = hours !== 0 ? `${hours}:${pad(minutes)}` : minutes;
      return `${res}:${pad(seconds)}.${ms} (${hours !== 0 ? "h:m" : ""}m:ss.mmm)`;
    }
    if (seconds !== 0) return `${seconds.toFixed(3)}s`;
    return `${Number(ms.toFixed(3))}ms`;
  }
  module.exports = { formatTime, Console: console.Console };
});

defineModule("internal/fs/sync_write_stream", function (module) {
  const { Writable } = __builtins.get("stream");
  const fs = __builtins.get("fs");
  function SyncWriteStream(fd, options) {
    Reflect.apply(Writable, this, [{ autoDestroy: true }]);
    options = options || {};
    this.fd = fd;
    this.readable = false;
    this.autoClose = options.autoClose === undefined ? true : options.autoClose;
  }
  Object.setPrototypeOf(SyncWriteStream.prototype, Writable.prototype);
  Object.setPrototypeOf(SyncWriteStream, Writable);
  SyncWriteStream.prototype._write = function (chunk, encoding, cb) {
    try {
      fs.writeSync(this.fd, chunk);
    } catch (error) {
      cb(error);
      return;
    }
    cb();
    return true;
  };
  SyncWriteStream.prototype._destroy = function (err, cb) {
    if (this.fd === null) return cb(err);
    if (this.autoClose) fs.closeSync(this.fd);
    this.fd = null;
    cb(err);
  };
  SyncWriteStream.prototype.destroySoon = SyncWriteStream.prototype.destroy;
  module.exports = SyncWriteStream;
});

defineModule("internal/util/inspect", function (module) {
  const util = __builtins.get("util");
  const { getStringWidth } = __internals.get("util_inspect");
  module.exports = {
    inspect: util.inspect,
    inspectDefaultOptions: util.inspect.defaultOptions,
    format: util.format,
    formatWithOptions: util.formatWithOptions,
    getStringWidth,
    stripVTControlCharacters: util.stripVTControlCharacters,
    isError: (e) => util.types.isNativeError(e) || e instanceof Error,
  };
});

defineModule("internal/util/types", function (module) {
  module.exports = __builtins.get("util/types");
});

defineModule("internal/options", function (module) {
  // Defaults of the options lumen's runtime reads; an option the command line did not set and
  // that is not listed here reads as undefined.
  const defaults = {
    __proto__: null,
    "--network-family-autoselection": true,
    "--network-family-autoselection-attempt-timeout": 250,
    "--max-http-header-size": 16 * 1024,
    "--stack-trace-limit": 10,
    "--unhandled-rejections": "",
    "--dns-result-order": "",
    "--diagnostic-dir": "",
    "--redirect-warnings": "",
    "--title": "",
    "--input-type": "",
    "--experimental-default-type": "",
    "--trace-event-categories": "",
    "--trace-event-file-pattern": "node_trace.${rotation}.log",
    "--require": [],
    "--import": [],
    "--conditions": [],
    "--env-file": [],
  };
  const lists = ["--require", "--import", "--conditions", "--env-file"];
  function getOptionValue(name) {
    const parsed = cliOptions();
    if (name.startsWith("--no-")) {
      const value = getOptionValue("--" + name.slice(5));
      return value === undefined ? undefined : !value;
    }
    if (Object.hasOwn(parsed, name)) {
      const value = parsed[name];
      if (name === "--max-http-header-size" || name === "--stack-trace-limit" ||
          name === "--network-family-autoselection-attempt-timeout") {
        return Number(value);
      }
      if (lists.includes(name) && !Array.isArray(value)) return [value];
      return value;
    }
    if (name === "--pending-deprecation") return process.env.NODE_PENDING_DEPRECATION?.[0] === "1";
    if (name in defaults) return defaults[name];
    return name.startsWith("--") ? false : undefined;
  }
  module.exports = {
    getOptionValue,
    getAllowUnauthorized: () => process.env.NODE_TLS_REJECT_UNAUTHORIZED === "0",
    getEmbedderOptions: () => ({ shouldNotRegisterESMLoader: false, noGlobalSearchPaths: false, hasEmbedderPreload: false }),
    refreshOptions() {},
  };
});

defineModule("internal/timers", function (module) {
  const net = __internals.get("netRequire")("internal/timers");
  module.exports = {
    kTimeout: net.kTimeout,
    TIMEOUT_MAX: 2 ** 31 - 1,
    setUnrefTimeout: net.setUnrefTimeout,
    getTimerDuration: net.getTimerDuration,
  };
});

defineModule("internal/async_hooks", function (module) {
  module.exports = __internals.get("netRequire")("internal/async_hooks");
});

defineModule("internal/streams/state", function (module) {
  const stream = __builtins.get("stream");
  module.exports = {
    getDefaultHighWaterMark: stream.getDefaultHighWaterMark,
    setDefaultHighWaterMark: stream.setDefaultHighWaterMark,
  };
});

defineModule("internal/v8/startup_snapshot", function (module) {
  const v8 = __builtins.get("v8");
  module.exports = { namespace: v8.startupSnapshot };
});

defineModule("internal/streams/compose", function (module) {
  module.exports = __internals.get("streamsInternal").compose;
});

defineModule("internal/streams/add-abort-signal", function (module) {
  module.exports = __internals.get("streamsInternal").addAbortSignal;
});

// Node's adapters also convert to and from StreamBase handles (newReadableStreamFromStreamBase,
// ...); lumen's handles are not StreamBase, so only the stream <-> web stream adapters exist.
defineModule("internal/webstreams/adapters", function (module) {
  module.exports = __internals.get("streamsInternal").adapters;
});

