print("a\nb\r\nc\rd".splitlines())
print("a\nb\n".splitlines(), "a\nb\n".splitlines(True), "".splitlines())
print(repr("a\tb\tc".expandtabs()), repr("a\tb".expandtabs(4)), repr("ab\tc".expandtabs(2)))
t = str.maketrans("abc", "xyz")
print(t[97], "aabbcc".translate(t))
t2 = str.maketrans("", "", "aeiou")
print("education".translate(t2))
t3 = str.maketrans({"a": "AA", "b": None, "c": 99})
print("abcd".translate(t3))
print("123".isdigit(), "12.3".isdigit(), "".isdigit(), "٣".isdigit(), "²".isdigit(), "²".isdecimal())
print("abc".isalpha(), "abc ".isalpha(), "é".isalpha(), "a1".isalnum(), "_".isidentifier(), "1a".isidentifier())
print("ß".casefold(), "ß".lower(), "ß".upper(), "HELLO".casefold())
print("a b c d".rsplit(None, 1), "a b c d".rsplit(" ", 2), "a,b,c".rsplit(",", 1), "a,b,c".rsplit(","))
print("a b c d".split(None, 2), "  a  b  ".split(None, 1))
b = "héllo wörld".encode("utf-8")
print(b, len(b), b.decode("utf-8"))
print("héllo".encode("ascii", "replace"), "héllo".encode("ascii", "ignore"))
print(b"abc".decode(), "€".encode("utf-8"), len("€".encode("utf-8")))
try:
    "é".encode("ascii")
except UnicodeEncodeError as e:
    print(type(e).__name__)
try:
    b"\xff".decode("utf-8")
except UnicodeDecodeError as e:
    print(type(e).__name__)
print(b"\xff".decode("utf-8", "replace") == "�")
print(ord("a"), ord("€"), chr(97), chr(8364), chr(0x1F600) == "\U0001F600")
print([ord(c) for c in "aé€"], "".join(chr(i) for i in range(65, 70)))
print(len("\U0001F600"), len("é"), "é" == "é")
print("É".lower(), "é".upper(), "İ".lower() == "i̇")
print("abc".ljust(2), "abc".rjust(6, "ab"[0]))
print("Hello".swapcase().swapcase())
print("a-b-c".split("-", maxsplit=1), "a-b-c".rsplit("-", maxsplit=1))
print("x".isprintable(), "\n".isprintable(), "".isprintable())
print("abc".isascii(), "é".isascii(), "".isascii())
print("  ".strip() == "", repr("\t\n x \r".strip()))
print("one two".partition(" "), "one".partition(" "))
print("ab".encode().hex(), bytes.fromhex("6162").decode())
print(str(b"abc", "utf-8"), str(123), str(None), str(True), str([1, "a"]))
print("tEsT sTrInG".title(), "x1y2".title(), "o'neil".title())
print("%d items" % 3, "abc".format())
print(sorted(["b", "A", "a", "B"]), sorted(["b", "A", "a", "B"], key=str.lower))
