s = "  hello world  foo\tbar\n"
print(s.split(), s.split(" "), s.split(None, 1), s.rsplit(None, 1))
print("a,b,,c".split(","), "a,b,,c".split(",", 1), "a,b,,c".rsplit(",", 1), "".split(","), "".split(), ",".split(","))
print("a--b--c".split("--"), "abc".split("abc"), "abcabc".split("bc"), "  x ".split(" "))
print("line1\nline2\r\nline3\rline4\n".splitlines(), "a\nb\n".splitlines(True), "".splitlines(), "\n".splitlines())
print(",".join(["a", "b", "c"]), "".join(["x"] * 3), "-".join("abc"), ", ".join(str(i) for i in range(4)), "x".join([]), "x".join(["y"]))
print(repr("  pad  ".strip()), repr("  pad  ".lstrip()), repr("  pad  ".rstrip()), repr("xxhixx".strip("x")), repr("xyhiyx".strip("xy")), repr("abc".strip("")))
print(repr("\t\n x \r\n".strip()), repr("www.example.com".lstrip("w.")), repr("file.txt".rstrip("txt")))
print("a b c".partition(" "), "a b c".rpartition(" "), "abc".partition("x"), "abc".rpartition("x"), "abc".partition("abc"))
print("hello".removeprefix("he"), "hello".removesuffix("lo"), "hello".removeprefix("x"), "hello".removesuffix(""))
print("abc".center(9, "*"), "abc".center(8, "*"), "abc".center(2), "abc".ljust(6, "."), "abc".rjust(6, "."), "42".zfill(6), "-42".zfill(6), "+4".zfill(4), "abc".zfill(2))
print("a\tb\tc".expandtabs(4), "ab\tc".expandtabs(), "a\nb\tc".expandtabs(2))
print("Hello World".swapcase(), "hello world".title(), "HELLO".lower(), "hello".upper(), "hello World".capitalize(), "hELLO".casefold(), "they're bob's".title())
print("a-b_c d".replace("-", "+"), "aaaa".replace("aa", "b"), "aaaa".replace("a", "bb", 2), "abc".replace("", "-"), "abc".replace("b", ""), "".replace("", "x"))
print("one two  three".split(" "), " ".join("one two  three".split()))
print("a,b;c d".replace(",", " ").replace(";", " ").split())
words = "the quick brown fox".split()
print([w[0].upper() + w[1:] for w in words], max(words, key=len), sorted(words), sorted(words, key=lambda w: (len(w), w)))
print("abc".isalpha(), "ab1".isalpha(), "123".isdigit(), "12.3".isdigit(), "abc1".isalnum(), "  ".isspace(), "".isspace(), "ABC".isupper(), "abc".islower(), "Ab".istitle(), "".isalpha())
print("x".isidentifier(), "1x".isidentifier(), "_x1".isidentifier(), "abc".isascii(), "é".isascii(), "123".isnumeric(), "12".isdecimal(), "abc".isprintable(), "a\nb".isprintable())
print("%s" % "x" * 3, "ab" * 3, "ab" * 0, "ab" * -1, 3 * "ab")
print("abc" < "abd", "abc" < "ab", "B" < "a", "" < "a", "abc" == "abc", "a" in "abc", "" in "abc", "ac" in "abc")
