"""Generate crates/lumen-common/src/tzdata.rs: per-zone UTC-offset transition tables read from a
compiled zoneinfo tree (TZif v2+ files, the system's /usr/share/zoneinfo by default).

Every TZif file under the tree is a zone name. Files with identical contents are one zone whose
canonical name is `UTC` if present, else the first name listed in zone1970.tab / zone.tab, else
the alphabetically first; the others become `LINKS` to it. A zone's `initial` offset is its
first local-time type; its transitions are the 64-bit data block's
(epoch_seconds, utc_offset_seconds) pairs, without those that repeat the previous offset.

Usage: python3 scripts/gen-tzdata.py [ZONEINFO_DIR]
"""

import os
import re
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEST = os.path.join(ROOT, "crates", "lumen-common", "src", "tzdata.rs")
# Subtrees that hold other variants of the same zones, not zones of their own.
SKIP_DIRS = {"posix", "right", "SystemV"}
SKIP_NAMES = {"localtime"}

HEADER = """//! IANA time-zone offset tables — GENERATED by scripts/gen-tzdata.py. DO NOT EDIT.
//!
//! Each zone lists its UTC-offset transitions as (epoch_seconds, utc_offset_seconds),
//! sorted ascending; `initial` is the offset before the first transition.

pub struct Zone {
    pub name: &'static str,
    pub initial: i32,
    pub transitions: &'static [(i64, i32)],
}

"""


def parse_tzif(data):
    """`(initial, [(time, utoff), ...])` from the version-2+ (64-bit) block of a TZif file."""
    def header(at):
        if data[at:at + 4] != b"TZif":
            raise ValueError("not a TZif file")
        version = data[at + 4:at + 5]
        counts = struct.unpack(">6l", data[at + 20:at + 44])
        return version, counts

    version, (isutcnt, isstdcnt, leapcnt, timecnt, typecnt, charcnt) = header(0)
    if version == b"\0":
        raise ValueError("TZif version 1 has no 64-bit data")
    # Skip the version-1 block to the second header.
    at = 44 + timecnt * 4 + timecnt + typecnt * 6 + charcnt + leapcnt * 8 + isstdcnt + isutcnt
    _, (isutcnt, isstdcnt, leapcnt, timecnt, typecnt, charcnt) = header(at)
    at += 44
    times = struct.unpack(f">{timecnt}q", data[at:at + timecnt * 8])
    at += timecnt * 8
    idxs = data[at:at + timecnt]
    at += timecnt
    types = [struct.unpack(">lBB", data[at + i * 6:at + i * 6 + 6])[0] for i in range(typecnt)]
    initial = types[0]
    transitions = []
    for t, i in zip(times, idxs):
        # Only offset changes matter: a transition that changes just the abbreviation or the
        # DST flag is dropped.
        if not transitions or types[i] != transitions[-1][1]:
            transitions.append((t, types[i]))
    return initial, transitions


def scan(zoneinfo):
    files = {}
    for dirpath, dirnames, filenames in os.walk(zoneinfo):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for f in filenames:
            path = os.path.join(dirpath, f)
            name = os.path.relpath(path, zoneinfo).replace(os.sep, "/")
            if name in SKIP_NAMES:
                continue
            with open(path, "rb") as fh:
                data = fh.read()
            if data[:4] == b"TZif":
                files[name] = data
    return files


def tab_zones(zoneinfo):
    """Zone names of zone1970.tab (or zone.tab where the tree has no zone1970.tab)."""
    for tab in ("zone1970.tab", "zone.tab"):
        path = os.path.join(zoneinfo, tab)
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                return {line.split("\t")[2].strip() for line in fh
                        if line.strip() and not line.startswith("#")}
    return set()


def ident(name):
    return "TZ_" + re.sub(r"[^A-Z0-9]", "_", name.upper().replace("+", "P").replace("-", "M"))


def main():
    zoneinfo = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/zoneinfo"
    files = scan(zoneinfo)
    listed = tab_zones(zoneinfo)
    groups = {}
    for name, data in files.items():
        groups.setdefault(data, []).append(name)
    zones, links = {}, []
    for data, names in groups.items():
        names.sort()
        canonical = "UTC" if "UTC" in names else next((n for n in names if n in listed), names[0])
        zones[canonical] = parse_tzif(data)
        links += [(alias, canonical) for alias in names if alias != canonical]

    out = [HEADER]
    for name in sorted(zones):
        _, transitions = zones[name]
        body = ", ".join(f"({t},{o})" for t, o in transitions)
        out.append(f"static {ident(name)}: &[(i64, i32)] = &[{body}];\n")
    out.append("\n/// Canonical zones, sorted by name.\npub static ZONES: &[Zone] = &[\n")
    for name in sorted(zones):
        initial, _ = zones[name]
        out.append(f'    Zone {{ name: "{name}", initial: {initial}, transitions: {ident(name)} }},\n')
    out.append("];\n\n/// (alias, canonical) links, sorted by alias.\npub static LINKS: &[(&str, &str)] = &[\n")
    for alias, canonical in sorted(links):
        out.append(f'    ("{alias}", "{canonical}"),\n')
    out.append("];\n\n")
    with open(DEST, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(out))
    print(f"tzdata: {len(zones)} zones, {len(links)} links", file=sys.stderr)


if __name__ == "__main__":
    main()
