#!/usr/bin/env python3
"""Generate crates/lumen-py/src/builtins/astnodes.rs, the node classes of the `_ast` module, from
CPython's Parser/Python.asdl (scripts/cpython-fetch.sh), following Parser/asdl_c.py: the class
docstrings (`asdl_of`), which classes carry `_attributes`, and which fields default to None."""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARSER = os.path.join(ROOT, "cpython", "Parser")
OUT = os.path.join(ROOT, "crates", "lumen-py", "src", "builtins", "astnodes.rs")

sys.path.insert(0, PARSER)
import asdl  # noqa: E402


def is_simple(sum_type):
    return not (sum_type.attributes or any(c.fields for c in sum_type.types))


def asdl_of(name, obj):
    if isinstance(obj, (asdl.Product, asdl.Constructor)):
        fields = ", ".join(map(str, obj.fields))
        if fields:
            fields = "({})".format(fields)
        return "{}{}".format(name, fields)
    if is_simple(obj):
        types = " | ".join(t.name for t in obj.types)
    else:
        sep = "\n{}| ".format(" " * (len(name) + 1))
        types = sep.join(asdl_of(t.name, t) for t in obj.types)
    return "{} = {}".format(name, types)


def kind(field):
    if field.seq:
        return "Seq"
    if field.opt:
        return "Opt"
    return "One"


def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def strs(names):
    return "&[" + ", ".join(rust_str(n) for n in names) + "]"


def fields(fs):
    return "&[" + ", ".join("({}, {}, FieldKind::{})".format(rust_str(f.name), rust_str(f.type), kind(f)) for f in fs) + "]"


def node(name, base, fs, attributes, defaults, doc, simple=False):
    attrs = "None" if attributes is None else "Some({})".format(strs(attributes))
    return (
        "    NodeType {{ name: {}, base: {}, fields: {}, attributes: {}, none_defaults: {}, simple: {}, doc: {} }},".format(
            rust_str(name), rust_str(base), fields(fs), attrs, strs(defaults), "true" if simple else "false", rust_str(doc)
        )
    )


def main():
    mod = asdl.parse(os.path.join(PARSER, "Python.asdl"))
    rows = []
    for dfn in mod.dfns:
        name, value = dfn.name, dfn.value
        if isinstance(value, asdl.Product):
            defaults = [f.name for f in value.fields if f.opt] + [f.name for f in value.attributes if f.opt]
            rows.append(node(name, "AST", value.fields, [a.name for a in value.attributes], defaults, asdl_of(name, value)))
        else:
            defaults = [f.name for f in value.attributes if f.opt]
            rows.append(node(name, "AST", [], [a.name for a in value.attributes], defaults, asdl_of(name, value)))
            simple = is_simple(value)
            for c in value.types:
                rows.append(node(c.name, name, c.fields, None, [f.name for f in c.fields if f.opt], asdl_of(c.name, c), simple))
    with open(OUT, "w") as f:
        f.write("//! The node classes of `_ast` — GENERATED by scripts/gen-py-ast.py from CPython's\n")
        f.write("//! Parser/Python.asdl. DO NOT EDIT.\n\n")
        f.write("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n")
        f.write("pub enum FieldKind {\n    One,\n    Opt,\n    Seq,\n}\n\n")
        f.write("pub struct NodeType {\n")
        f.write("    pub name: &'static str,\n")
        f.write("    /// `AST` for a sum or product type, the sum type for a constructor.\n")
        f.write("    pub base: &'static str,\n")
        f.write("    /// `(name, asdl type, kind)`.\n")
        f.write("    pub fields: &'static [(&'static str, &'static str, FieldKind)],\n")
        f.write("    /// `_attributes`, set on sum and product types only.\n")
        f.write("    pub attributes: Option<&'static [&'static str]>,\n")
        f.write("    /// Optional fields and attributes: a class attribute `None`.\n")
        f.write("    pub none_defaults: &'static [&'static str],\n")
        f.write("    /// A constructor of a sum without fields or attributes (`Load`, `Add`, ...).\n")
        f.write("    pub simple: bool,\n")
        f.write("    pub doc: &'static str,\n")
        f.write("}\n\n")
        f.write("/// In CPython's creation order (a base before its constructors).\n")
        f.write("#[rustfmt::skip]\n")
        f.write("pub static NODE_TYPES: &[NodeType] = &[\n")
        f.write("\n".join(rows))
        f.write("\n];\n")


main()
