"""Generate crates/lumen/src/tznames.rs: the en-US display names of every zone in tzdata.rs
(rows in `ZONES` order).

Asks a Node.js built with full ICU (`node` on PATH) for each zone's long/short specific names
(standard and daylight) and long/short generic names. Names ICU renders as a localized GMT
offset ("GMT+03:00", "GMT-5") are stored empty: the engine formats those from the offset.

Usage: python3 scripts/gen-tz-names.py
"""

import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from cldr_pack import emit  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "crates", "lumen", "src")

NODE_SCRIPT = r"""
const zones = JSON.parse(require('fs').readFileSync(0, 'utf8'));
const jan = Date.UTC(2025, 0, 15, 12), jul = Date.UTC(2025, 6, 15, 12);
const name = (tz, style, t) => new Intl.DateTimeFormat('en-US', { timeZone: tz, timeZoneName: style })
  .formatToParts(t).find(p => p.type === 'timeZoneName').value;
const off = (tz, t) => {
  const s = name(tz, 'longOffset', t);
  const m = /GMT([+-])(\d\d):(\d\d)/.exec(s);
  return m ? (m[1] === '-' ? -1 : 1) * (+m[2] * 60 + +m[3]) : 0;
};
const known = tz => { try { new Intl.DateTimeFormat('en-US', { timeZone: tz }); return true; } catch { return false; } };
const gmt = /^GMT([+-]\d{1,2}(:\d\d)?)?$/;
const names = tz => {
  if (!known(tz)) return [tz, '', '', '', '', '', ''];
  const lo = off(tz, jan) <= off(tz, jul) ? jan : jul;
  const hi = lo === jan ? jul : jan;
  return [tz, name(tz, 'long', lo), name(tz, 'long', hi), name(tz, 'short', lo), name(tz, 'short', hi),
    name(tz, 'longGeneric', jan), name(tz, 'shortGeneric', jan)];
};
const score = r => r.slice(1).filter(v => v && !gmt.test(v)).length;
// A zone's aliases can carry names ICU lacks for the zone itself (Europe/London for the
// Europe/Guernsey the table keys London's rules under).
const rows = zones.map(([tz, ...aliases]) => {
  let best = names(tz);
  for (const a of aliases) {
    const r = names(a);
    if (score(r) > score(best)) best = r;
  }
  return best;
});
process.stdout.write(JSON.stringify(rows));
"""

FNS = [
    "/// The en-US names of the zone at `index` in `tzdata::ZONES`: `[long standard, long daylight,",
    "/// short standard, short daylight, long generic, short generic]` (\"standard\" is the lower of",
    "/// the zone's current offsets). An empty name means ICU shows a GMT offset there.",
    "pub fn zone_names(index: usize) -> [&'static str; 6] {",
    "    match ROWS.get(index * 6..index * 6 + 6) {",
    "        Some(r) => std::array::from_fn(|k| POOL.get(r[k])),",
    "        None => [\"\"; 6],",
    "    }",
    "}",
]

GMT = re.compile(r"^GMT([+-]\d{1,2}(:\d\d)?)?$")


def main():
    text = open(os.path.join(SRC, "tzdata.rs"), encoding="utf-8").read()
    links = re.findall(r'^    \("([^"]+)", "([^"]+)"\),$', text, re.M)
    zones = [[z] + [a for a, c in links if c == z]
             for z in re.findall(r'Zone \{ name: "([^"]+)"', text)]
    out = subprocess.run(["node", "-e", NODE_SCRIPT], input=json.dumps(zones),
                         capture_output=True, text=True, check=True).stdout
    rows = []
    for r in json.loads(out):
        rows.append(tuple("" if GMT.match(v) else v for v in r[1:]))
    hdr = ["//! en-US time-zone display names, generated by scripts/gen-tz-names.py. DO NOT EDIT."]
    dest = os.path.join(SRC, "tznames.rs")
    open(dest, "w", encoding="utf-8", newline="\n").write(emit(hdr, [("ROWS", rows, ())], FNS))
    print(f"tznames: {len(rows)} zones", file=sys.stderr)


if __name__ == "__main__":
    main()
