r = range(10, 0, -3)
print(list(r), len(r), r[0], r[-1], 7 in r, 8 in r)
print(range(5)[1:4], list(range(5)[::2]), range(0), range(1, 5, 2))
print(list(enumerate("ab", start=5)))
print(list(zip("abc", [1, 2], (9, 8, 7))))
print(list(zip()))
print(list(map(lambda a, b: a * b, [1, 2, 3], [4, 5, 6, 7])))
print(list(filter(None, [0, 1, "", "a", None, [], [0]])))
print(list(filter(lambda x: x > 1, (1, 2, 3))))
m = map(str, [1, 2])
print(next(m), next(m), list(m))
d = {"b": 2, "a": 1}
print(list(d), list(d.keys()), list(d.values()), list(d.items()))
ki = iter(d)
print(next(ki), next(ki))
it = iter("hello")
print("".join(it), list(it))
l = [1, 2, 3]
i1, i2 = iter(l), iter(l)
print(next(i1), next(i1), next(i2))
print(sorted(iter([3, 1, 2]), reverse=True))
print(list(zip(*zip("ab", "cd"))))
z = zip([1, 2], "ab")
print(type(z).__name__, next(z), list(z))
s = iter([1, 2])
print(iter(s) is s)
print(dict(zip("ab", range(2))), set(zip([1], [2])))
print(list(enumerate([])), list(map(int, "123")))
print(all(iter([1, 2])), any(iter([0, 0])), sum(iter(range(4))))
print(min(iter([4, 2, 8])), max(iter("abc")))
print(" ".join(map(str, range(5))))
print(list(range(-3)), list(range(3, 1)), list(range(0, -4, -2)))
print(len(range(0, 100, 7)), range(3) == range(3), range(0) == range(5, 5))
