// Generated host-independent WHATWG streams extension.
// DO NOT EDIT: generated by crates/lumen-node/tools/webstreamsgen/gen.js.
// Minimal browser-hosted environment for the WHATWG stream algorithms. The Node
// algorithms are generated below from the same upstream sources as webstreams.js; this file only
// supplies their internal Node compatibility shims and deliberately has no fs/net/crypto hooks.
const __builtins = new Map();
const __internals = new Map();
const __node = {
  promiseState(value) {
    if (value === null || (typeof value !== 'object' && typeof value !== 'function')) return undefined;
    return typeof value.then === 'function' ? [0, undefined] : undefined;
  },
};
/* INSERT_CANONICAL_MODULE_LOADER */

function __streamError(code, Base, message) {
  const CodedError = class extends Base {
    constructor(...args) {
      const rendered = typeof message === 'function' ? message(...args) : message;
      super(rendered ?? args.map(String).join(' '));
      this.name = Base.name;
      this.code = code;
    }
  };
  Object.defineProperty(CodedError, 'name', { value: code });
  CodedError.TypeError = __streamErrorVariant(code, TypeError, message);
  CodedError.RangeError = __streamErrorVariant(code, RangeError, message);
  return CodedError;
}
function __streamErrorVariant(code, Base, message) {
  return class extends Base {
    constructor(...args) {
      super(typeof message === 'function' ? message(...args) : message ?? args.map(String).join(' '));
      this.name = Base.name;
      this.code = code;
    }
  };
}

const __errors = {
  ERR_ILLEGAL_CONSTRUCTOR: __streamError('ERR_ILLEGAL_CONSTRUCTOR', TypeError, 'Illegal constructor'),
  ERR_INVALID_ARG_TYPE: __streamError('ERR_INVALID_ARG_TYPE', TypeError,
    (name, expected) => `The "${name}" argument must be ${Array.isArray(expected) ? expected.join(' or ') : expected}`),
  ERR_INVALID_ARG_VALUE: __streamError('ERR_INVALID_ARG_VALUE', TypeError,
    (name, value, reason = 'is invalid') => `The argument '${name}' ${reason}. Received ${String(value)}`),
  ERR_INVALID_THIS: __streamError('ERR_INVALID_THIS', TypeError,
    (name) => `Value of "this" must be of type ${name}`),
  ERR_MISSING_OPTION: __streamError('ERR_MISSING_OPTION', TypeError,
    (name) => `${name} is required`),
  ERR_OPERATION_FAILED: __streamError('ERR_OPERATION_FAILED', Error,
    (message) => `Operation failed: ${message}`),
};
class __AbortError extends Error {
  constructor(message = 'The operation was aborted', options = undefined) {
    super(message, options);
    this.name = 'AbortError';
    this.code = 'ABORT_ERR';
  }
  static [Symbol.hasInstance](value) {
    return value instanceof Error && value.name === 'AbortError' && value.code === 'ABORT_ERR';
  }
}
const InvalidStateError = __streamError('ERR_INVALID_STATE', Error,
  (message) => `Invalid state: ${message}`);
InvalidStateError.TypeError = __streamError('ERR_INVALID_STATE', TypeError,
  (message) => `Invalid state: ${message}`);
InvalidStateError.RangeError = __streamError('ERR_INVALID_STATE', RangeError,
  (message) => `Invalid state: ${message}`);
__errors.ERR_INVALID_STATE = InvalidStateError;

const __validators = {
  validateFunction(value, name) {
    if (typeof value !== 'function') throw new __errors.ERR_INVALID_ARG_TYPE(name, 'Function');
  },
  validateObject(value, name, options = 0) {
    const nullable = (options & 1) !== 0;
    const allowArray = (options & 2) !== 0;
    const allowFunction = (options & 4) !== 0;
    if (value === null && nullable) return;
    if (value === null || typeof value !== 'object' && !(allowFunction && typeof value === 'function') ||
        (!allowArray && Array.isArray(value))) {
      throw new __errors.ERR_INVALID_ARG_TYPE(name, 'Object');
    }
  },
  validateAbortSignal(signal, name) {
    if (signal !== undefined && (signal === null || typeof signal !== 'object' || !('aborted' in signal)))
      throw new __errors.ERR_INVALID_ARG_TYPE(name, 'AbortSignal');
  },
  validateBuffer(value, name = 'buffer') {
    if (!ArrayBuffer.isView(value)) throw new __errors.ERR_INVALID_ARG_TYPE(name, ['TypedArray', 'DataView']);
  },
  kValidateObjectAllowNullable: 1,
  kValidateObjectAllowArray: 2,
  kValidateObjectAllowFunction: 4,
};

/* INSERT_CANONICAL_PRIMORDIALS */
const primordials = __primordials;

function builtinModule(id) {
  switch (id) {
    case 'buffer':
      return { Buffer: globalThis.Buffer, constants: {} };
    case 'events':
      return {
        addAbortListener(signal, listener) {
          signal.addEventListener('abort', listener, { once: true });
          return { [Symbol.dispose]() { signal.removeEventListener('abort', listener); } };
        },
      };
    case 'util':
      return {
        inspect(value) { return String(value); },
        customInspectSymbol: Symbol.for('nodejs.util.inspect.custom'),
        kEnumerableProperty: Object.freeze({ enumerable: true }),
      };
    case 'internal/errors': return { codes: __errors, AbortError: __AbortError };
    case 'internal/validators': return __validators;
    case 'internal/util/types':
      return {
        isArrayBufferView: (value) => ArrayBuffer.isView(value),
        isDataView(value) {
          if (!ArrayBuffer.isView(value)) return false;
          try { Reflect.apply(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get, value, []); return true; }
          catch { return false; }
        },
        isPromise: (value) => value !== null && (typeof value === 'object' || typeof value === 'function') &&
          typeof value.then === 'function',
      };
    case 'internal/util':
      return {
        customInspectSymbol: Symbol.for('nodejs.util.inspect.custom'),
        kEmptyObject: Object.freeze({ __proto__: null }),
        kEnumerableProperty: Object.freeze({ __proto__: null, enumerable: true }),
        createDeferredPromise() {
          let resolve, reject;
          const promise = new Promise((res, rej) => { resolve = res; reject = rej; });
          return { promise, resolve, reject };
        },
        customInspect(_depth, _options, name) { return name; },
        isArrayBufferDetached: (buffer) => buffer.byteLength === 0 && buffer.detached === true,
        SideEffectFreeRegExpPrototypeSymbolReplace: (regexp, string, replacement) =>
          typeof string === 'string' ? RegExp.prototype[Symbol.replace].call(regexp, string, replacement) : string,
      };
    case 'internal/assert':
      return (value, message) => { if (!value) throw new Error(message ?? 'internal assertion failed'); };
    case 'internal/process/task_queues': return { queueMicrotask: globalThis.queueMicrotask };
    case 'internal/worker/io': return { MessageChannel: globalThis.MessageChannel };
    case 'internal/worker/js_transferable':
      return { kDeserialize: Symbol('kDeserialize'), kTransfer: Symbol('kTransfer'),
        kTransferList: Symbol('kTransferList'), makeTransferable: (value) => value };
    case 'internal/streams/utils':
      return {
        kIsDisturbed: Symbol.for('nodejs.stream.kIsDisturbed'),
        kIsErrored: Symbol.for('nodejs.stream.kIsErrored'),
        kIsReadable: Symbol.for('nodejs.stream.kIsReadable'),
        kIsWritable: Symbol.for('nodejs.stream.kIsWritable'),
        kIsClosedPromise: Symbol.for('nodejs.webstream.isClosedPromise'),
        kControllerErrorFunction: Symbol.for('nodejs.webstream.controllerErrorFunction'),
      };
    case 'internal/abort_controller': return { AbortController: globalThis.AbortController };
    case 'internal/encoding': return { TextDecoder: globalThis.TextDecoder, TextEncoder: globalThis.TextEncoder };
    case 'internal/webstreams/transfer':
      throw new TypeError('Transferring web streams is not supported by this host');
  }
  throw new Error(`web streams: internal module '${id}' is unavailable in this host`);
}

function internalBinding(name) {
  switch (name) {
    case 'messaging': return {
      DOMException: globalThis.DOMException ?? Error,
      structuredClone: (value, options) => globalThis.structuredClone(value, options),
    };
    case 'buffer':
      return {
        copyArrayBuffer(destination, destinationOffset, source, sourceOffset, bytesToCopy) {
          new Uint8Array(destination, destinationOffset, bytesToCopy)
            .set(new Uint8Array(source, sourceOffset, bytesToCopy));
        },
        detachArrayBuffer(buffer) {
          if (!(buffer instanceof ArrayBuffer) || typeof buffer.transfer !== 'function') return undefined;
          try { return buffer.transfer(); } catch { return undefined; }
        },
      };
    case 'util':
      return { constants: { kPending: 0 }, getPromiseDetails: (promise) => __node.promiseState(promise) };
  }
  throw new Error(`web streams: internal binding '${name}' is unavailable in this host`);
}
