// node:stream/web and the WHATWG stream globals — Node 20.11's lib/internal/webstreams/*.js and
// lib/stream/web.js, run as-is.
//
// DO NOT EDIT: generated by crates/lumen-node/tools/webstreamsgen/gen.js (see tools/README.md).
//
// The Node sources below are verbatim, each wrapped as a CommonJS-style module; the few edits are
// marked `lumen:`. The internals they import (errors, validators, util, the buffer/util/messaging
// bindings) are the small shims in this header. Transferring streams through postMessage
// (internal/webstreams/transfer) is not supported. The file loads on first use: the stream
// globals are accessors that run it, then become plain data properties, as Node's lazy
// interfaces do.

const primordials = __primordials;

// ---- the module table -------------------------------------------------------------------------
// `defineModule(id, fn)` registers a module body, which is evaluated on its first `require`.
// Cycles resolve as in CommonJS: a module is cached before its body runs.
const moduleDefs = new Map();
const moduleCache = new Map();
function defineModule(id, fn) {
  moduleDefs.set(id, fn);
}
function require(id) {
  const cached = moduleCache.get(id);
  if (cached !== undefined) return cached.exports;
  const fn = moduleDefs.get(id);
  if (fn !== undefined) {
    const module = { exports: {} };
    moduleCache.set(id, module);
    fn(module, module.exports, require, internalBinding, primordials);
    return module.exports;
  }
  const value = builtinModule(id);
  moduleCache.set(id, { exports: value });
  return value;
}

// Node's internal AbortError: the glue's builtins each define their own class, so recognise any of
// them by shape.
class AbortError extends Error {
  constructor(message = "The operation was aborted", options = undefined) {
    super(message, options);
    this.code = "ABORT_ERR";
    this.name = "AbortError";
  }
  static [Symbol.hasInstance](value) {
    return value instanceof Error && value.name === "AbortError" && value.code === "ABORT_ERR";
  }
}

const kEmptyObject = Object.freeze({ __proto__: null });
const isArrayBufferDetached = (value) => value.byteLength === 0 && value.detached === true;

const isDataView = (() => {
  const byteLength = Object.getOwnPropertyDescriptor(DataView.prototype, "byteLength").get;
  return (value) => {
    if (!ArrayBuffer.isView(value)) return false;
    try {
      Reflect.apply(byteLength, value, []);
      return true;
    } catch {
      return false;
    }
  };
})();

function builtinModule(id) {
  switch (id) {
    case "buffer": case "zlib":
      return __builtins.get(id);
    case "events":
      return { get addAbortListener() { return __builtins.get("events").addAbortListener; } };
    case "util":
      return { inspect: (value, options) => __builtins.get("util").inspect(value, options) };
    case "internal/errors":
      return { codes: __errors, AbortError };
    case "internal/validators":
      return __validators;
    case "internal/util/types":
      return {
        isArrayBufferView: (value) => ArrayBuffer.isView(value),
        isDataView,
        isPromise: (value) => value !== null && (typeof value === "object" || typeof value === "function") &&
          __node.promiseState(value) !== undefined,
      };
    case "internal/util":
      return {
        createDeferredPromise() {
          let resolve, reject;
          const promise = new Promise((res, rej) => {
            resolve = res;
            reject = rej;
          });
          return { promise, resolve, reject };
        },
        customInspectSymbol: Symbol.for("nodejs.util.inspect.custom"),
        isArrayBufferDetached,
        kEmptyObject,
        kEnumerableProperty: Object.freeze({ __proto__: null, enumerable: true }),
        SideEffectFreeRegExpPrototypeSymbolReplace(regexp, string, replacement) {
          return typeof string === "string" ? RegExp.prototype[Symbol.replace].call(regexp, string, replacement) : string;
        },
      };
    case "internal/assert": {
      const fail = (message) => {
        const error = new Error(message === undefined ?
          "This is caused by either a bug in Node.js or incorrect usage of Node.js internals.\n" +
          "Please open an issue with this stack trace at https://github.com/nodejs/node/issues\n" :
          message);
        error.code = "ERR_INTERNAL_ASSERTION";
        throw error;
      };
      const assert = (value, message) => {
        if (!value) fail(message);
      };
      assert.fail = fail;
      return assert;
    }
    case "internal/worker/io":
      return { MessageChannel: globalThis.MessageChannel };
    case "internal/worker/js_transferable":
      return {
        kDeserialize: Symbol("kDeserialize"),
        kTransfer: Symbol("kTransfer"),
        kTransferList: Symbol("kTransferList"),
        makeTransferable: (obj) => obj,
      };
    case "internal/webstreams/transfer":
      throw new __errors.ERR_INVALID_STATE.TypeError("Transferring web streams is not supported");
    case "internal/process/task_queues":
      return { queueMicrotask: globalThis.queueMicrotask };
    case "internal/streams/utils":
      // Shared with node:stream (stream.js), which reads these off web streams.
      return {
        kIsDisturbed: Symbol.for("nodejs.stream.kIsDisturbed"),
        kIsErrored: Symbol.for("nodejs.stream.kIsErrored"),
        kIsReadable: Symbol.for("nodejs.stream.kIsReadable"),
        kIsWritable: Symbol.for("nodejs.stream.kIsWritable"),
        kIsClosedPromise: Symbol.for("nodejs.webstream.isClosedPromise"),
        kControllerErrorFunction: Symbol.for("nodejs.webstream.controllerErrorFunction"),
      };
    case "internal/abort_controller":
      return { AbortController: globalThis.AbortController };
    case "internal/encoding":
      return { TextDecoder: globalThis.TextDecoder, TextEncoder: globalThis.TextEncoder };
    case "internal/webstreams/adapters":
      return {
        newReadableWritablePairFromDuplex: (duplex) => __builtins.get("stream").Duplex.toWeb(duplex),
      };
  }
  throw new Error(`lumen stream/web: internal module '${id}' is not available`);
}

function internalBinding(name) {
  switch (name) {
    case "messaging":
      return { DOMException: globalThis.DOMException };
    case "buffer":
      return {
        copyArrayBuffer(destination, destinationOffset, source, sourceOffset, bytesToCopy) {
          new Uint8Array(destination, destinationOffset, bytesToCopy)
            .set(new Uint8Array(source, sourceOffset, bytesToCopy));
        },
        // Node's C++ returns a new ArrayBuffer over the detached one's memory, or undefined when
        // the buffer cannot be detached (a SharedArrayBuffer, a wasm memory).
        detachArrayBuffer(buffer) {
          if (!(buffer instanceof ArrayBuffer)) return undefined;
          try {
            return buffer.transfer();
          } catch {
            return undefined;
          }
        },
      };
    case "util":
      return {
        constants: { kPending: 0 },
        getPromiseDetails: (promise) => __node.promiseState(promise),
      };
  }
  throw new Error(`lumen stream/web: internal binding '${name}' is not available`);
}

