import itertools as it

print(list(it.islice(it.count(5, 2), 4)))
print(list(it.islice(it.cycle("ab"), 5)))
print(list(it.repeat("x", 3)))
print(list(it.chain([1, 2], (3,), "ab")), list(it.chain.from_iterable([[1], [2, 3]])))
print(list(it.accumulate([1, 2, 3, 4])), list(it.accumulate([1, 2, 3], lambda a, b: a * b)))
print(list(it.zip_longest("ab", [1, 2, 3], fillvalue="-")))
print(list(it.product("ab", [1, 2])), list(it.product([0, 1], repeat=2)))
print(list(it.permutations([1, 2, 3], 2)))
print(list(it.combinations("abcd", 2)), list(it.combinations_with_replacement("ab", 2)))
print([(k, list(g)) for k, g in it.groupby("aabbbc")])
print([(k, len(list(g))) for k, g in it.groupby([1, 1, 2, 3, 3, 3])])
print(list(it.takewhile(lambda x: x < 3, [1, 2, 3, 1])), list(it.dropwhile(lambda x: x < 3, [1, 2, 3, 1])))
print(list(it.filterfalse(lambda x: x % 2, range(6))), list(it.compress("abcd", [1, 0, 1, 0])))
print(list(it.starmap(pow, [(2, 3), (3, 2)])), list(it.islice(range(10), 2, 8, 3)))
a, b = it.tee([1, 2, 3])
print(list(a), list(b))
print(list(it.pairwise([1, 2, 3, 4])))
