import random

random.seed(42)
print(random.random())
print(random.randint(1, 100))
print(random.randrange(0, 1000, 7))
print(random.randrange(10))
print(random.choice("abcdef"))
print(random.choice([10, 20, 30, 40]))
items = list(range(10))
random.shuffle(items)
print(items)
print(random.sample(range(100), 5))
print(random.sample("abcdefgh", 3))
print(random.choices("abc", k=6))
print(random.choices([1, 2, 3], weights=[5, 1, 1], k=6))
print(random.getrandbits(8), random.getrandbits(32), random.getrandbits(33), random.getrandbits(100))
print(random.uniform(1, 2))
print(random.gauss(0, 1))
print(random.normalvariate(5, 2))
print(random.expovariate(1.5))
print(random.triangular(0, 10, 3))
print(random.betavariate(2, 3))
print(random.gammavariate(2.0, 1.5))
print(random.lognormvariate(0, 1))
print(random.vonmisesvariate(1, 2))
print(random.paretovariate(3))
print(random.weibullvariate(1, 2))
print(random.randbytes(6))

random.seed(1234)
state = random.getstate()
a = [random.random() for _ in range(5)]
random.setstate(state)
b = [random.random() for _ in range(5)]
print(a == b, len(state), state[0], len(state[1]), state[1][-1])

for seed in (0, 1, -5, 2**70, -(2**100), "hello", b"bytes", bytearray(b"ba"), 3.25, None.__class__ and 7):
    r = random.Random(seed)
    print(repr(seed)[:20], r.random(), r.getrandbits(40))

r = random.Random(99)
print(r.random(), r.randint(0, 10**30))
r.seed(99)
print(r.random(), r.randint(0, 10**30))
r.seed("x", version=1)
print(r.random())
r.seed(5, version=2)
print(r.random())
